### ISSUE TITLE
The Naming of Things

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#1]
It's important. I put in "The LSST Observing Strategy" and "MAF Workshop" as placeholders for the names of the white paper and the Seattle workshop respectively, but these need thought. Comments welcome below, especially from people who have thought more about this than I have!

**Comment by drphilmarshall** [comment]
From Zeljko, a few possible paper titles:

* *“Current Baseline Design for LSST Deployment and Further Optimization”*
* *“Optimization Strategies for LSST Deployment”*
* *“Towards Optimal LSST Deployment”*
* *“Science Driven Optimization of LSST Deployment”*

**Comment by StephenRidgway** [comment]
The 2014 workshop was named "LSST and NOAO Observing Cadences Workshop".  The 2015 plan is so far almost identical to the 2014, so the only title that makes sense is the same words with II or 2015 appended.

**Comment by lmwalkowicz** [comment]
I think though @StephenRidgway that the structure is actually a bit different: here we have a white paper effort that is related-to-yet-independent-of the Seattle MAF hack session. Personally I prefer "Observing Strategy" to the other phrase @ivezic uses ("deployment") as I find observing strategy to be a more specific descriptor. For a similar reason I might suggest changing the word "workshop"-- I think that sounds like we will be teaching people to use MAF (similar to what we did in 2014), when in fact what we want is for people to come prepared to code... correct? So maybe what we want is "MAF Hack Day" (which also has the added benefit of sounding fun... well, to me anyway).

**Comment by bethwillman** [comment]
A strong second to Lucianne's suggestion of "Observing Strategy" instead of "Deployment".

Science Driven Optimization of LSST's Observing Strategy

**Comment by bethwillman** [comment]
[Sorry, hit "comment" too soon.]

Regarding the title of the entire set of festivities - I'm still unclear on a very basic point: Is this event to attract and engage the general community?  Or is it to engage preferentially junior and technically oriented people who want to get their hands dirty?  Those aren't the same crowds.  MAF should appear almost nowhere, and most participants should not get MAF training if we are aiming to directly engage more of the general community here.
