### ISSUE TITLE
Chapter 6 section titles (star vs event vs ? )

### ISSUE THREAD

**Issue by lundmb** [LSSTScienceCollaborations/ObservingStrategy#104]
Looking over chapter 6's subsections, there seems to be an inconsistency in how sections have been named. The current sections are 6.2 Periodic Variable Stars; 6.3 Non-periodic Variable Stars; 6.4: Periodic Transient Events, 6.5: Transient Events

In particular, the first two are explicitly specify stars, while the latter two do not. However, the targets are not limited to stellar sources. My interpretation of this is that the first two are dealing with sources that have no quiescent period while the latter two are dealing with sources that do have quiescent periods. If this seems to be the distinction, is there a better way that these categories can be labeled to reflect this? Constantly varying periodic sources and constantly varying non-periodic sources? Something else that would be more intuitive?

**Comment by StephenRidgway** [comment]
Agreed, the layout has problems - and as you note, suffers from having been used differently than defined : )

Your comment on quiescent periods is a good distinction - though objects that vary only due to transits may be mostly “quiescent”.  Trying to do a 1D organization with several parameters.

**Comment by lundmb** [comment]
I'd say considering transiting events as periodic transient events, where
they are mostly quiescent, is a reasonable category that would put them in
section 6.4.

Maybe Sources of periodically interrupted quiescence and Sources of
non-periodically interrupted quiescence? Then the first two being
Periodically varying sources and non-periodically varying sources.

**Comment by StephenRidgway** [comment]
Ah, now I get it, I think that looks good.  So move transiting and some eclipsing events.

**Comment by drphilmarshall** [comment]
@lundmb @lmwalkowicz @StephenRidgway @AshishMahabal Has the Variables and Transients chapter structure settled down now? Next week we'll need sections with associated MAF metric suggestions (if not actual metrics)...

**Comment by ebellm** [comment]
(See the discussion on issue #152 )
