### ISSUE TITLE
Metric nomenclature

### ISSUE THREAD

**Issue by lundmb** [LSSTScienceCollaborations/ObservingStrategy#105]
This is a broad question but I think it will benefit from consistency: how do we want to refer to specific metrics in the paper?

On one hand, I would think that it would be very useful to provide the specific metric to use, and the relevant parameters. However, this runs the risk of quickly becoming very technical and not as accessible to someone not familiar with the metrics. If the metrics are being referred to by name, I'm also less sure what the best way would be to refer to metrics that are *not* currently written and have only been outlined conceptually.

Would the goal be that by the final paper, all metrics will exist in some form, or does there need to be a way to discuss conceptual metrics that have not yet been written as well?

A related point of clarification is if enigma 1189 should be the opsim run used for any analysis, or if the specific opsim can vary so long as it is stated.

**Comment by rhiannonlynne** [comment]
I'm hoping that people provide a 'recipe' that we can use to evaluate *any* opsim run, so while it may be useful to illustrate metric results using enigma_1189, I want to be sure I can do whatever you are describing and apply it to any run. 
I think this is also a vote to use real metric names where applicable.

**Comment by drphilmarshall** [comment]
Yes, I agree with @rhiannonlynne - let's write our sections referring to the names of actual MAF metrics, whether or not they have been written. That way, the metrics that don't exist yet will have a recipe for how to write them. We'll have to decide next week what state we want the metrics to be in by the time of arxiv posting, but I think we already know that not all science sections will have coded up MAF metrics by that time. That's OK - it just means that those science cases will not be able to argue for themselves very strongly yet.
