### ISSUE TITLE
Metric testing

### ISSUE THREAD

**Issue by tmatheson** [LSSTScienceCollaborations/ObservingStrategy#106]
Is there a simple, small-scale database that mimics OpSim output that can be used to debug metrics?  For a relatively complex calculation, it would be useful to have a way to check that the end result is really what I think it should be.

**Comment by StephenRidgway** [comment]
I guess you mean something other than just taking the first night from 10 years.  So…..what do you mean?

**Comment by tmatheson** [comment]
I mean something even smaller than a night.  Just a way to do quick sanity checks on the calculations done in the metric.

**Comment by AshishMahabal** [comment]
So, just a file in the right format should be good.

**Comment by tmatheson** [comment]
Peter Yoachim pointed me to the 'Tests' section of sims_maf.  This routine illustrates how to test a metric with known inputs: https://github.com/lsst/sims_maf/blob/master/tests/testTechnicalMetrics.py

This answers the question for me.
