### ISSUE TITLE
Weak Lensing Section

### ISSUE THREAD

**Issue by jmeyers314** [LSSTScienceCollaborations/ObservingStrategy#107]
We need a weak lensing section (and metric)!

I suggest we focus on systematics, not statistics, so something like sigma^2_sys (i.e., the integrated spurious correlation function) from Amara+Refregier08 may be appropriate.  The hard part, of course, is to actually estimate sigma^2_sys given OpSim output.

A (non-exhaustive) list of ObservingStrategy items we definitely care about includes:
- uniformity (i.e., dithering, including [rotational dithering](https://github.com/LSST-nonproject/sims_maf_contrib/pull/19))
- photometric redshift systematics
- airmass (b/c DCR)

More input appreciated.

**Comment by michaelstrauss** [comment]
I believe there was been quite a bit of thinking about this last year at the cadence workshop, and there has been additional work within the DESC.  Rachel Mandelbaum (cc'ed here) will know more.

**Comment by jmeyers314** [comment]
>I believe there was been quite a bit of thinking about this last year at the cadence workshop, and there has been additional work within the DESC.  Rachel Mandelbaum (cc'ed here) will know more.

Yes, good point.  There are notes from last year's workshop on the [DESC confluence page.](https://confluence.slac.stanford.edu/display/LSSTDESC/WL+Cadence+Issues)

**Comment by jmeyers314** [comment]
For a quick look at rotational dithering results from OpSim, take a look [here](https://github.com/jmeyers314/sims_maf_contrib/blob/master/science/static/Angular%20Spread.ipynb)

**Comment by StephenRidgway** [comment]
Following the Cosmology discussion yesterday, I added a “Suppressing systematics” section.  This attempts to give enough context to stand on its own, but specifically addresses only the detector angle randomization.  The section will be superceded, but the paragraph on RotSkyPos may remain valid.

**Comment by knutago** [comment]
Has anyone looked at dithering strategies that preserve uniformity in the case that one or more detectors are inoperable?

**Comment by StephenRidgway** [comment]
Hmm, looks like it was superceded already.

**Comment by jmeyers314** [comment]
![rotdith](https://cloud.githubusercontent.com/assets/3650485/9425037/f90a45d0-48b6-11e5-8ee9-fec013085975.png)

**Comment by rmandelb** [comment]
Apologies for the slow response.  I am just catching up on this now, and subscribed to this github conversation so I will get further updates.

@jmeyers314 - I completely agree about focusing on systematics, evaluated at certain intervals (e.g., after 1st year, 3rd year, 5th year, etc.).  But the main difficulty will be going from the OpSim outputs to the quantities that we actually care about. For example, it's all well and good to say we'll make a histogram of the PSF FWHM values at various positions and make sure they are converging to the same thing, but how close do they actually need to be to give an amount of inhomogeneity that is problematic from a systematics perspective?

I think it would be worth making two lists:
- The low-level things we care about, e.g., seeing distributions, rotation angle distributions -- the kinds of things that we can get from OpSim.
- The high-level quantities that determine our systematics, e.g., PSF shear correlation function.

Then think about which low-level things go into which high-level things, and what other information do we need to connect them (sims?  simple analytic prescriptions?).  This might result in a set of information we need to gather to make further progress. 

Another DESC WL discussion on this topic would not be a bad idea.  Also, if this is going to be significant work, there should be something about it in the DESC science roadmap, so if there is not something for it then it's worth pinging the weak lensing conveners.

**Comment by drphilmarshall** [comment]
@jmeyers314 @rmandelb I just did some tidying up, making an actual WL section and putting in some notes about figures of merit vs metrics. I think we want to at least be working in terms of $\sigma_{\rm sys}$, as a function of our three diagnostic metrics ("RotSkyPosUniformity", "RotTelPosUniformity" and "WLDepthUniformity"). This functional form is to be derived, by any means available. For now though, thanks to some hard work by Josh and others at Bremerton, we have a Weak Lensing section :-) Thanks!
