### ISSUE TITLE
Should science sections comment on the alternative strategies?

### ISSUE THREAD

**Issue by ctslater** [LSSTScienceCollaborations/ObservingStrategy#108]
Thinking of the Milky Way section and the Pan-STARRS-like cadence in particular, I can think of reasons why topics like increased area coverage might deserve some qualitative discussion in specific science sections. The basic metric in this case is somewhat obvious (area coverage) and a few other parameters will scale semi-directly with that, such as the observed volume of the halo, number of detected dwarfs, etc. It seems like this is therefore more of a discussion than a computation. Is this appropriate for the science sections?

**Comment by ivezic** [comment]
I think so. It'd be great to use other simple metrics (sky coverage and depth in particular)
to cook up a new metric, even if still simple, for this science case (e.g. we can easily compute 
halo volume for, say, blue turn-off stars with Mr~5, or for RR Lyrae, if we add some temporal metric).
