### ISSUE TITLE
Documenting MAF maps capabilities

### ISSUE THREAD

**Issue by yoachim** [LSSTScienceCollaborations/ObservingStrategy#110]
Right now, we have an Easter egg in MAF. There is often information you would like at higher resolution than a single field of view.  We added the functionality in MAF that you can pass in a map, and then additional information from the map will get passed to your metric via the slicePoint dict.

Here's an example of using our regular coadded depth and ExgalM5 metric that uses the SFD dustmaps:
https://github.com/yoachim/ObservingStrategy/blob/master/notebooks/MapExample.ipynb

(note, while making this example I found a bug with the dustmaps, I'll fix it in MAF soon)

During the meeting, we came up with some other metrics that would benefit from using MAF maps, e.g., a map of stellar density on the sky (including LMC&SMC), so @knutago can compute a confusion limit metric.
![dustmap](https://cloud.githubusercontent.com/assets/3673733/9424855/a81e2b92-48b0-11e5-83ba-b6c759081d16.png)

**Comment by drphilmarshall** [comment]
Ooooooh I think @egawiser and @rbiswas4 will be interested in this.

**Comment by rhiannonlynne** [comment]
@yoachim a star density map would be a great idea! 
Just noting somewhere (maybe this should be a separate issue)  - we should update @lundmb's metrics  / check that we match.

**Comment by ivezic** [comment]
Mario already produced such maps when we were defining the boundary of
the Galactic plane confusion zone. I think he did it in python - it'd be good to
touch base with him.

**Comment by drphilmarshall** [comment]
Hey @yoachim ! Did this make it into the MAF documentation at all? Is there a reference we should include in the white paper?

**Comment by yoachim** [comment]
Good question!
Looks like I made a stellar density notebook in sims_maf_contrib:
https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/science/static/StellarDensityMap.ipynb

And the ExgalM5 metric is in MAF, so should be part of the full list of metrics documentation.

**Comment by rhiannonlynne** [comment]
We'll work on getting some more basic documentation (what is a map, how do you add a map to a slicer) into the MAF online documentation. Currently the resources @yoachim pointed to above are all there is available (the exgalm5 metric source is here 
https://sims-maf.lsst.io/_modules/lsst/sims/maf/metrics/exgalM5.html#ExgalM5
but unfortunately that's about as much of an explanation as you can extract from the API documentation.
The currently available maps are listed here 
https://sims-maf.lsst.io/lsst.sims.maf.maps.html 
in the API docs.

**Comment by drphilmarshall** [comment]
OK, thanks! Should this be a MAF or sims_maf_contrib issue instead? I'll leave that with you to ponder! :-)
