### ISSUE TITLE
Using MAF to explore impact of mixed vendor focal plane

### ISSUE THREAD

**Issue by yoachim** [LSSTScienceCollaborations/ObservingStrategy#111]
Working with @connolly, I expanded MAF's focal plane geometry so that metrics can know the full raft+chip coordinates of each observation.  

Here's an example metric that returns 1 if a point is only observed by vendor 1, 2 if only vendor 2, and 3 if observed by both vendors.
https://github.com/yoachim/ObservingStrategy/blob/master/notebooks/vendorChips.ipynb

A single exposure, showing rafts with different vendors:
![vendor2](https://cloud.githubusercontent.com/assets/3673733/9424875/6c395dee-48b1-11e5-9d44-df5ae21315b0.png)

Lots of exposures. Due to rotation and overlap, some regions get observed by both vendor chips:
![vendor](https://cloud.githubusercontent.com/assets/3673733/9424882/aad66588-48b1-11e5-8172-62daec51e72e.png)

Some of this code is on a MAF branch--hope to get it merged back to master soon.

**Comment by drphilmarshall** [comment]
This was such a nice hack, @yoachim! Is this code now part of `sims_maf_contrib`? Or somewhere else? I'm going to close this out but don't let that stop you answering :-)

**Comment by yoachim** [comment]
It's been merged to master on sims_maf and there's an example notebook on how to use it in sims_maf_contrib:
https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/science/static/MixedVendorFocalPlane.ipynb

There's also this bit of code where I looked at how one could set different sensitivities to different vendors:
https://github.com/yoachim/ScratchStuff/blob/master/mixedFocal/mixedFocal.py

**Comment by drphilmarshall** [comment]
Excellent! :-) I think that just means that the sims_maf_contrib wiki is
out of date. We can use this to introduce notebooks like this one, and make
it easier for people to find out what's possible in MAF.
