### ISSUE TITLE
Metrics for Gravitational Waves followups

### ISSUE THREAD

**Issue by soares-santos** [LSSTScienceCollaborations/ObservingStrategy#113]
- Continue evaluating existing metrics that could be useful for GW followup strategy studies
- Construct new set of metrics for evaluating GW followup strategy scenarios

Candidate 1st metric:
- inputs:  trigger time (T_0), time window (delta_T), band list (e.g. i,z)
- output: number of visits within the specified time window and filter set (N_v)

@drphilmarshall @ebellm: Can you point us to documentation on the existing metrics? We can find the list in github, but not a description of what they do. Thanks.

**Comment by drphilmarshall** [comment]
Great! @connolly

**Comment by soares-santos** [comment]
This might be useful: https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/mafContrib/transientAsciiMetric.py

**Comment by lundmb** [comment]
For the inbuilt metrics, there's some instructions here (provided you have
the LSST software downloaded) on how to get a list of all of them, with the
relevant documentation

https://confluence.lsstcorp.org/display/SIM/MAF+Metrics

**Comment by drphilmarshall** [comment]
What's the status of the GW follow-up section? Is it written into the V&T chapter yet? @fedhere @ebellm can you take a look and catch up with @soares-santos please? Thanks!

**Comment by soares-santos** [comment]
Hi Phil,

Sorry for the silence. I will look into this today.

Marcelle

On Wednesday, November 11, 2015, Phil Marshall <notifications@github.com>
wrote:

> What's the status of the GW follow-up section? Is it written into the V&T
> chapter yet? @fedhere <https://github.com/fedhere> @ebellm
> <https://github.com/ebellm> can you take a look and catch up with
> @soares-santos <https://github.com/soares-santos> please? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/113#issuecomment-155975596>
> .
>


-- 
Marcelle Soares-Santos
http://home.fnal.gov/~marcelle/
http://www.darkenergysurvey.org/ <http://darkenergysurvey.org/>

**Comment by ebellm** [comment]
We decided against a metric for the whitepaper; PR #335 summarizes the science case.
