### ISSUE TITLE
Chapter or appendix on coordination with other facilities

### ISSUE THREAD

**Issue by jasondrhodes** [LSSTScienceCollaborations/ObservingStrategy#114]
I was asked to lead a section (chapter or appendix) on coordination with other facilities.  Right now this is limited to WFIRST and Euclid, but others could be included.

-WFIRST wide survey (High Latitude Survey) of 2300 square degrees.  Suggest new opsim run by @egawiser to examine covering this area to full depth in first 2500 square degrees.

-WFIRST deep fields including supernova and microlensing fields, maybe coordinated with @rhiannonlynne & Neil Brandt

-Euclid additional overlap area between -5<DEC<30, to AB~24.5 in 4 bands, with a time calculation by Tony Tyson

**Comment by egawiser** [comment]
The new OpSim addition has been suggested; see https://github.com/LSSTScienceCollaborations/ObservingStrategy/tree/master/opsim

**Comment by drphilmarshall** [comment]
Hi @jasondrhodes - Thinking a bit about the LSST/WFIRST overlap, and how it should fit into the LSST Observing Strategy white paper. I *think* what we want to do is first identify a few science sections that can be written that involve using both LSST and WFIRST data, and quantify them with some metrics. These sections should then appear in the correct chapter. Once we have them, we can then think about pulling their results together in a short discussion in the "Tensions and Tradeoffs" chapter at the end. 

So, to that end, here's your short list of science areas again - can you please help me edit it into set of science *projects* please? I'll tag some people so they can comment. Even getting *one* of these written up as a white paper section would be great. Which is the highest priority science case, in your mind?

- WFIRST wide survey (High Latitude Survey) of 2300 square degrees (to be captured in a new opsim run proposed by @egawiser to examine covering this area to full depth in first N years). Science cases: 
  - Joint LSST+WFIRST WL analysis. Metric: $\sigma_{sys}$? DETF FoM? @jasondrhodes @jmeyers314
  - Joint LSST+WFIRST LSS analysis? Metric? @egawiser?

- WFIRST deep fields including supernova and microlensing fields. Science cases:
  - Joint LSST+WFIRST SN cosmology analysis. Metric? (Follow SN chapter). @MichelleLochner ?
  - Joint LSST+WFIRST microlensing analysis. Who can investigate this, @lundmb ?

**Comment by jasondrhodes** [comment]
Phil-  Some comments are embedded below.

**Comment by astrostubbs** [comment]
We should add coordination of photometric calibration...

Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

If you think this email is terse, see http://emailcharter.org

**Comment by jasondrhodes** [comment]
Chris-  Do you feel like that is a necessary part of photo-z (i.e. would already be covered when doing optimal photo-z determination) or will there be other requirements in that area that go beyond photo-z?

Thanks,

Jason

**Comment by astrostubbs** [comment]
It's actually more an issue for supernovae than it is for photo-z's, sorry if my comment was out of place. 
C

Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

If you think this email is terse, see http://emailcharter.org

**Comment by jasondrhodes** [comment]
Chris-  I do think that it is important to include here.  I just wanted to know where to ‘place’ it!

Jason

**Comment by drphilmarshall** [comment]
The WFIRST chapter is coming along nicely - closing this out!
