### ISSUE TITLE
adding transient metric that uses ascii input file for lightcurve shape

### ISSUE THREAD

**Issue by svalenti** [LSSTScienceCollaborations/ObservingStrategy#123]
Federica bianco and me have produced a metric to input asci file and recover the light curve observed by LSST.

https://github.com/fedhere/sims_maf_contrib/blob/master/mafContrib/transientAsciiMetric.py

**Comment by svalenti** [comment]
<img width="457" alt="screen shot 2015-08-22 at 10 06 33 am" src="https://cloud.githubusercontent.com/assets/7798941/9425002/a7ebd6a6-48b5-11e5-8836-9a4fc0953174.png">
![image](https://cloud.githubusercontent.com/assets/7798941/9425005/b0f2fed2-48b5-11e5-97dc-fdd30a34c61f.png)

**Comment by svalenti** [comment]
![image](https://cloud.githubusercontent.com/assets/7798941/9425017/090d77b4-48b6-11e5-955c-2c2f850d5c4b.png)

**Comment by drphilmarshall** [comment]
Very nice! You should introduce it with your simple example on the [`sims_maf_contrib` wiki](https://github.com/LSST-nonproject/sims_maf_contrib/wiki) :-)  @rbiswas4 @MichelleLochner @jhrlsst did you see this? Must be useful for supernovae, I would think.
