### ISSUE TITLE
AGN Future Steps

### ISSUE THREAD

**Issue by cmp346** [LSSTScienceCollaborations/ObservingStrategy#124]
Ideas for Metrics:
detection - how many can LSST detect based on the luminosity function (depends on the depth in each band for single epoch and coadd) (how will this change with each DR)? @ohadshemmer 

classification - How many of these will we actually classify as quasars? non-simultaneous colors. variability of QSOs (how does depend on cadence/baseline/seasonal gaps?) 

microlensing - convolve microlensing timescales for QSOs we already know about. how many of the high magnification events do we get? How bright? @tanguita 

QPOs - Will the cadence and duration give you the proper range on the power spectrum to detect QPOs with a given mass, spin, and L/Ledd? (Bob Wagoner)

How is this interdependent with the photo-z metrics?

Using astrometry at high airmass and differential chromatic refraction to estimate redshifts of QSOs?

Needs from OpSim:
light curves - In order to have informative metrics, we need to have accurate model light curves that can reproduce how the fiducial light curves appear in different bands, at different inherent luminosities, and at different redshifts.

DDF - we need longer duration OpSims in these fields. (Bob Wagoner) (https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/README.md)

commissioning opportunity - one field, one night, one filter (u or g). 15/30 sec exposures. (Bob Wagoner) (https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/commissioning/README.md)

**Comment by drphilmarshall** [comment]
I'm going to assume that @ohadshemmer incorporated all these notes in his write-up. If not, can you re-open this and comment please, Christina? Thanks!
