### ISSUE TITLE
minisurvey: Impactor survey

### ISSUE THREAD

**Issue by rhiannonlynne** [LSSTScienceCollaborations/ObservingStrategy#130]
We want to do a survey for 'almost immediate' impactors.

The impactors we'd target here are very small -- on average a 40cm bolide impacts once a day, while a 1m object would impact once a week. It is extremely interesting to discover these objects before impact, and have a chance to get information on their pre-impact orbit and additional followup observations (ideally spectroscopy, to understand their composition before impact). Predicting the impact location also permits retrieval of the meteorite, for further study after it's passed through the atmosphere.

We propose a short minisurvey to discover these objects. 
The immediate impactor population is concentrated on the sky in the 1000 sq degrees around opposition. Because we have to unambiguously discover these objects in a single night (so that followup can occur in the time before impact), we need to observe in quads. 

More details to come (it's in @davidtrilling 's notebook)

**Comment by yoachim** [comment]
How much warning would one have on these? Enough to short a few stocks?

**Comment by drphilmarshall** [comment]
Impactors! A splendid idea for a new `OpSim` experiment. Can you add it to the [board](https://github.com/LSSTScienceCollaborations/ObservingStrategy/tree/master/opsim) please? Thanks!

**Comment by drphilmarshall** [comment]
I see impactors made it into the Special Surveys chapter - so we can close this out, I think. Hooray!
