### ISSUE TITLE
minisurvey: Minimoons survey

### ISSUE THREAD

**Issue by rhiannonlynne** [LSSTScienceCollaborations/ObservingStrategy#131]
We want to do a small minimoon survey to discover minimoons. 

Minimoons move fast, which is why they may be hard to discover in the normal LSST cadence. 

More details in @davidtrilling's notebook.

**Comment by drphilmarshall** [comment]
Minimoons! Another splendid idea for an `OpSim` experiment :-) Can you add this to the [board](https://github.com/LSSTScienceCollaborations/ObservingStrategy/tree/master/opsim) as well, please? I'm assigning @rhiannonlynne for now but this and #130 really seem like they are on @davidtrilling's to-do list. Thanks!

**Comment by drphilmarshall** [comment]
I see minimoons made it into the Special Surveys chapter - so we can close this out, I think. Hooray!
