### ISSUE TITLE
Can we have a brief description of how OpSim works in the white paper?

### ISSUE THREAD

**Issue by rbiswas4** [LSSTScienceCollaborations/ObservingStrategy#141]
Chapters 1 and 2 mention OpSims a number of times and describe a number of OpSim outputs in terms of some key parameters, and an analysis of their performance. Can we have a brief description of what OpSim itself is doing with such parameters in this chapter or elsewhere? For example What does the OpSim output represent: is it a realization of observational sequences consistent with the constraints mentioned  where one has tried to maximize the number of total visits ?

Apologies if it is already there and I have missed it, but I think having such a section will help in improving the readability of the white paper.

**Comment by drphilmarshall** [comment]
Thanks @rbiswas4 - I think it's a very good idea to have a brief introduction to `OpSim` in the white paper. Section 1.1 ("Synoptic Sky Surveying") looks to me like the place for it. Assigning to @connolly ! :-)
