### ISSUE TITLE
November workshop: dates? funding?

### ISSUE THREAD

**Issue by rhiannonlynne** [LSSTScienceCollaborations/ObservingStrategy#146]
Hi PTB - 
I have to start getting my travel sorted out for this workshop. Are the dates (nov 19-20) solid? Are there any plans for travel support? 
Lynne

**Comment by bethwillman** [comment]
Dates are solid!  @ivezic says that there may be funds for a few non-project folks.  See you there.

**Comment by rbiswas4** [comment]
How do I ask for such travel funds?

**Comment by bethwillman** [comment]
Very active white paper contributors, who don't have other funding to attend the meeting, can directly email Zeljko Ivezic (@ivezic) with a request.
