### ISSUE TITLE
Editors' meeting, 2015-09-21: action items!

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#148]
LSST Observing Strategy White Paper  Editors’ Meeting, 2015-09-21

Monday September 21, 2015. 0900 PDT = 1200 EDT = 1700 BST

Present: Phil Marshall, David Trilling @davidtrilling , Ohad Shemmer @ohadshemmer , Andy Connolly @connolly , Kathy Vivas @akvivas , Eric Bellm @ebellm , Federica Bianco @fedhere , Jeonghee Rho @jhrlsst , Lynne Jones @rhiannonlynne , Michelle Lochner @MichelleLochner , Timo Anguita @tanguita , Beth Willman @bethwillman , Rahul Biswas @rbiswas4 , Zeljko Ivezic @ivezic , Eric Gawiser @egawiser , David Nidever @dnidever 

Apologies: Knut Olsen @knutago , Steve Ridgway @StephenRidgway 

Note takers: Phil Marshall (and occasionally others)

## Our upcoming Face-to-Face Meeting in Tucson

Thursday/Friday 19-20 November. 

Logistics (Beth):
* “Lodge on the Desert” , near Tucson
* Commitment from Victor to support it financially. Some support for people who need it, up to ~10 or so.
* Seems like 15-20 people are likely. Who to invite? Constraints on size. Zeljko suggests: invite by issues, and to people in Bremerton. Need: a mailing list. 
* [x] Action: Beth: to ask Emily to make an “observing-strategy@lsst.org” mailing list.
* Formal list of attendees needed by mid October. Sign-up form, including need for support. Remote attendance too, on this form, including ypes of remote attendance. 
* [x] Action: Beth: make sign-up form and email to the list (inviting us to Tucson :-). 

## How do we want to use that meeting time? What do we want to get done before we arrive in Tucson?

* White Paper writing workshop: Science Book experience: writing groups that meet up, then diverge, then meet up again. Implies need to collect plots and text before workshop, so editors are well set up before they arrive. 
* [x] Action: Phil: Set this homework after meeting invitation email goes out
* MAF metrics: Most useful thing is to get requests for metrics in place, so that MAF folks can implement after the meeting. 
* [x] Action: Phil: Set this homework too!
* Clarification: what are metrics for, and what types of metrics are we looking at? Discovery metrics, then characterisation, etc. 
* [x] Action: Phil: think about how to work more on this in Tuscon

## The White Paper. What shape is it in? Are there ways in which it needs refactoring?

Round table, comments from all!

* Introduction: compare [LSST overview paper](http://arxiv.org/abs/0805.2366) science goals with those in science section. Are the previously defined science goals still relevant/complete?  
* [ ] Action: Zeljko to issue chapter editors with comparing overview paper. 
* Chapter 1 editors: Beth, Zeljko, Phil
* [ ]  Chapter 2 "OpSim Examples": will need to be revamped, following re-run on new sims (with bugs fixed). Forward references to later chapters. Inclusion of other community-defined metrics! :-) Via an auto-magic metric calculator, in both scheduler validation and science context. 
* [ ] Action: Zeljko - re-run Chapter 2 
* Chapter editors: Zeljko, Peter?
* Solar System: mini surveys as new section at end of chapter? David and Lynne to act as chapter editors. 
* [ ] Action: David to add final section on proposed mini-surveys.
* [ ] The Galaxy: experts contacted for feedback! Looking for missing cases, in overview paper. Skeleton in place, main sections defined. Merging with Chapter 5? Plan is to evolve both separately for a bit longer for now. Chapter editors: Kathy & Will.
* Variables and Transients: lots of placeholder, only two science-based metrics defined, plus many diagnostics. Big chapter. How to split?  Periodic vs non periodic? Former may not be very important at all, regarding cadence choices. Which science cases are the most sensitive? And the most important? Supernova science, fast transients, GRBs and GW sources. Chapter editors: TBD, while we figure out split.
* [x] Action: Fed (& Eric B) to start conversation with transients and vars community about chapter.
* Cosmology: Eric and Michelle to be chapter editors. Sections are science driven, with systematics covered. LSS, WL (incl rotation systematics), SN, SL. Photo-zs? TBD. Many probes depend on this. SN classification: needs a section, possibly in transients chapter but referred to from cosmology chapter. Expecting lots of cross-refs between SN cosmology and transients.
* AGN? Ohad: AGN not just variables and transients. Clustering, galaxy evolution. 
* [x] Action: Ohad & Timo to implement new chapter. Editors: Ohad & Timo.
* DDF, MCs. Chapter editors: Niel and Lynne, Knut and David N
* Tensions and trade-offs: Steve R and Beth W to oversee as chapter editors.

More notes:

* Dynamic PDF? Needs setting up. 
* [x] Action: Phil: remove PDF from the repo, set up a separate continuous build. 
* [x] Action: Jeonghee: issue Phil with this task.

* [x] Action: Phil: set up GitHub issue labels, one per chapter.

* It'd be useful to be able to make individual sections, not just the whole document. 
* [x] Action: Fed: issue individual section compilation ability.

## Getting more input 

* From around the science collaborations, and further afield. 
* How to handle that influx of issues? Chapter editors are in charge of issue labelling, assignment and oversight.

* [x] Action: Phil: issue chapter editors with labelling/assigning their issues. 
* [ ] Action: Phil: email project and science to appeal for input.

**Comment by egawiser** [comment]
We should definitely go back and compare the current science content with the Science Book as well as the Ivezic et al. overview paper.  As I understand the goals, we should concentrate here on the science goals in each chapter's purview that are most sensitive to the observing strategy.  But it would also be helpful to briefly list additional science goals published earlier (or added since then) that have similar/weaker/negligible observing strategy dependencies.

**Comment by bethwillman** [comment]
re: the action item of asking for an Observing Strategy email list - Emily can't select out who of the registrants participated in the Observing Strategy workshop; she can only list who was registered on a given day.  I got the list of people registered on Thursday of Bremerton and sent all 180 of them the info about the Observing Strategy workshop.  If we want a specialized list, someone is going to have to curate that by hand by looking through all registrants and selecting those that we think participated. I don't think this is a necessary action item (but if someone else wants to do it, go nuts :) ).
