### ISSUE TITLE
Continuous build of LSST Observing Strategy White Paper PDF?

### ISSUE THREAD

**Issue by jhrlsst** [LSSTScienceCollaborations/ObservingStrategy#149]
Can the current version of the LSST Observing Strategy white paper be posted on a web site somewhere (in pdf format) and updated regularly (at least every 2-3 days)?

**Comment by drphilmarshall** [comment]
I will work on this - I also need to deep-remove the PDF from the repo, as it's getting a bit large and unwieldy.

**Comment by jhrlsst** [comment]
I see the link "Read the current draft of the white paper"(pdf file) from github page. Can you include the date of creation of the file when you compile the tex file?

**Comment by rbiswas4** [comment]
Hi Jeonghee,

Why don't you clone it on your computer and run the makefile? I had trouble
with that link at various times. This will give you the latest.

Rahul

**Comment by jhrlsst** [comment]
I figured out how to get the pdf file. Just click raw then it will download.

I don't feel compiling the entire white paper. I could get CVS version if I need, but now it is good enough
if I have the pdf file.

Jeonghee

**Comment by drphilmarshall** [comment]
Update on this: I'm seeing if we can continuously build the white paper PDF and host it at SLAC. Meanwhile I have removed the PDF and all its history from the repo, following [this example](http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-a-git-repository). That at least reduced the repo's size to 65Mb from 452Mb(!).

**Comment by StephenRidgway** [comment]
Need some clarification, since the pdf is gone, and the link at https://github.com/LSSTScienceCollaborations/ObservingStrategy/tree/master/whitepaper to Read the current version of the paper here <https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/master/whitepaper/LSST_Observing_Strategy_White_Paper.pdf> no longer works, is the expectation that I pull all updates to my computer and run make locally? I would prefer to be able to see the “current” version without having to resolve conflicts.

**Comment by drphilmarshall** [comment]
For now, that is the default plan, yes. You shouldn't have to deal with too
many conflicts, if you are keeping up to date, and committing and pushing
frequently.

**Comment by jhrlsst** [comment]
A current version of pdf (daily created) would be still very useful. Can you make a pdf file (for example, every day midnight) and make it available somewhere? So we can see where we are more easily?
This will be very helpful.

**Comment by drphilmarshall** [comment]
OK, I am most of the way there. Travis CI is now building the PDF every time a new push is detected, and the badge on the [README](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/README.md) shows you if the latex is compiling correctly. The actual PDF file has to come from an automatic build at SLAC, and the only way I know how to do that is via a cron job - see the new file `build.csh` for details. This is not yet functioning correctly though - I'm not sure why but I suspect its an AFS token issue (it almost always is). Maybe @sethdigel or @tony_johnson can advise here.

Meanwhile, I promise you that doing a one line `git pull ; make` in the `whitepaper` directory really does give you the latest version of the PDF. That is all that my build script is doing!

**Comment by sethdigel** [comment]
Well, if the issue is related to AFS tokens then you should use trscrontab (see http://www.slac.stanford.edu/grp/cd/soft/slaconly/unix/cron.htm).   

Where do you have in mind to have the PDF file automatically posted?

**Comment by jhrlsst** [comment]
astroph preprint web site has a good function to build pdf file from tex files. I know they are compiling whenever a user hits the button.

**Comment by drphilmarshall** [comment]
@sethdigel I'm already using trscrontab. The job schedules fine, but
doesn't run. Does trscrontab keep a log somewhere? It seems hard to debug.
The command I am using is in te header of build.csh, if you're interested.

**Comment by sethdigel** [comment]
trscontab does not keep a log that I'm aware of.  For some large Fermi papers we used svn and some scripts by Glenn Morris to make automatic builds.  At the time, the only host where regular users could run cron jobs was lnxcron.  I'm not finding that online documentation any more, but I'd swap in lnxcron for ki-ls07 in your script and see whether that works.  I'm also recalling that SLAC Computing used to want cron jobs to run no more often than hourly (0 * * * *).  I don't think there was any enforcement, but you might find that running every minute is overkill.

**Comment by rbiswas4** [comment]
I have never really tried, but I would guess that easy configuring of
nightly builds would be a feature of continuous integration setups like
travisCI. I am guessing a makefile exists, so maybe this is a way out?
(Sorry, this is just a wild guess, I have not really tried to check this).

**Comment by drphilmarshall** [comment]
@sethdigel OK I give up. I tried lnxcron, both in the trscrontab file and as the host that I set up the cron job on. Nothing works. Here's the line I am trying to execute:
```
lnxcron 0 * * * * (/u/ki/pjm/public_html/LSST/ObservingStrategy/whitepaper/build.csh)
```
I'll remove the promise of "hourly" from the README.

@rbiswas4 The problem with travis CI is that the output files, including the PDF, are not kept - it doesn't give us a URL to link to. It's great for alerting me to a broken paper, though.

**Comment by jhrlsst** [comment]
Please don't worry about this anymore. It seems to be complicated. People (including myself) can download the files and compile.
Thanks for trying.

**Comment by rbiswas4** [comment]
@drphilmarshall Of course... I completely forgot that bit when I was suggesting travis.

**Comment by drphilmarshall** [comment]
Good: at least its not my cron skills that are lacking! :-) I guess your
origin points at the http git address of the repository - or else, you have
figured out how to make ssh keys work properly at SLAC so that you don't
have to type a password when you git pull.

I guess there is something in my environment set-up that is preventing
trscrontab from executing the script in my area. I can try and debug this
next week. Thanks!

**Comment by sethdigel** [comment]
Ah.  In case it is useful in the meantime for the workshop, I've now got the hourly builds being written to http://www.slac.stanford.edu/~digel/ObservingStrategy/whitepaper/LSST_Observing_Strategy_White_Paper.pdf
The log file is http://www.slac.stanford.edu/~digel/ObservingStrategy/whitepaper/build.log

**Comment by drphilmarshall** [comment]
Hi @sethdigel - would you mind making sure that your web-visible hourly build at SLAC is working? I worry that that repo may not be pulling cleanly from the base repo, since I re-wrote its history... The solution is to make a fresh clone. Thanks!

**Comment by sethdigel** [comment]
Ok, done.  It is working again.  Is rewriting the history of the repository likely to happen often?

**Comment by drphilmarshall** [comment]
Hopefully not - but we are only one push away from it, until everyone has
replaced all their clones and forks with the PDF-free version. Fingers
crossed that people are paying attention, and making sure that their repo
is under 100Mb in size. Thanks Seth!

PS. Note to self: don't ever check in the PDF file of a latex project. Ever!

**Comment by jhrlsst** [comment]
I see two errors when I do "make"
1) define "\erg" or change to regular tex format
2) maybe need to define \ref{sec:\supernovae}.

LaTeX Warning: Reference `fedhere' on page 84 undefined on input line 29.

! Undefined control sequence.
<argument> sec:\supernovae 
                           
l.31 ...a (also discussed in \ref{sec:\supernovae}
                                                  ), and explosion of high m...

?
! Undefined control sequence.
<write> ...eX Warning: Reference `sec:\supernovae 
                                                  ' on page \thepage \space ...
l.31 ...a (also discussed in \ref{sec:\supernovae}
LaTeX Warning: Reference `sec:' on page 84 undefined on input line 31.

! Undefined control sequence.
l.31 ...luminous SNe, SLSNe) ($\times 10^{49} \erg
                                                  $), corresponding to absol...

**Comment by sethdigel** [comment]
Thanks for pointing out the errors, Jeonghee.  The build script is not very smart and does not alert me if the LaTeX source has a problem.  I set about to fix the build errors just now - they were in sn.tex and supernovacosmology.tex - but I see that @migueldvb has already done it.  He has posted a pull request here https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/225  
When the pull request gets accepted, the automatic builds will start working again.  The cron job runs at 1 minute after every hour.

**Comment by jhrlsst** [comment]
Hi Seth,
I have updated the tex file for supernova cosmology more than a week ago, but newly updated pdf file
was not updated. I don't think pdf file is built frequently. Can you take a look at it?
Thanks.

**Comment by sethdigel** [comment]
Ah.  Thanks for pointing out the problem.  Again I was not watching.  The builds had been broken since Feb. 5.  The problem was induced by the use of the 'subfigure' environment in cadexp2.tex.  This required adding the 'subcaption' package to the list of packages in LSST_Observing_Strategy_White_Paper.sty, which Zeljko did on Feb. 5.  It seems that, at least in the LaTeX installation at SLAC, the 'caption' package has to be loaded before the subcaption package.  I added it to the LSST_Observing_Strategy_White_Paper.sty file in the build directory and manually ran the build script, so PDF file is current as of now.  The automatic builds will stay broken until I get a pull request submitted for the change, and it gets pulled.

**Comment by sethdigel** [comment]
Just to follow up:  Phil pulled the update to LSST_Observing_Strategy_White_Paper.sty and I've confirmed that the automatic builds are working again.

**Comment by jhrlsst** [comment]
Seth and Phil,
Thank you very much. You are the best.
