### ISSUE TITLE
Message to chapter editors

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#150]
Hi,

Thanks for agreeing to serve as "editors' of the white paper chapters. (@connolly, @yoachim would you mind taking this on for the chapters listed below, please? Thanks!) This task involves "tending" the issue list, making sure that all submitted issues pertaining to your chapter are correctly labelled, milestoned and assigned to people (including yourselves, if its an editorial task). The current issue list needs some care and attention, and so a first run through with your new editors' hats on is in order! :-) 

Here's the current list of chapter editors: please check your box when you have tidied up your chapter's issues! Thanks very much :-)

* [ ] Introduction: @bethwillman @connolly
* [ ] OpSim Examples: @ivezic @yoachim
* [ ] Solar System: @davidtrilling @rhiannonlynne  
* [ ] The Galaxy: @akvivas @willclarkson 
* [ ] Variables and Transients: TBD, from @AshishMahabal @lundmb @ebellm @fedhere @lmwalkowicz 
* [ ] Cosmology: @MichelleLochner @egawiser 
* [ ] AGN: @ohadshemmer @tanguita  
* [ ] DDF: @nielbrandt @rhiannonlynne 
* [ ] Magellanic Clouds: @knutago @dnidever 
* [ ] Tensions and trade-offs: @StephenRidgway @bethwillman

**Comment by drphilmarshall** [comment]
Dear all,

I just sent email to the registered workshop attendees about the upcoming workshop in Tucson (next week!). I've pasted in the text for you below. You'll notice that as chapter editors you will be playing a *starring role* in the workshop, summarizing your sections' progress, calling out roadblocks/requests for help, and assessing the completeness of your chapters as we go through this sprint. 

Now would be an excellent time to start preparing for this role by getting your issues in line: each existing one needs labeling, milestoning, assigning and pinging to make sure it is getting worked on - and any tasks that have not been issued need issuing forthwith! I'd suggest you each do this as a way of getting back into the white paper groove, and then use your issues to make sure you get to where you want to be at the beginning of the workshop. I'll drop in and do some of this too, to help out. If you have questions, please just reply to this message with them. Thanks very much for all your efforts! :-)


Email from Phil to the workshop attendees:

> Dear all,
>
> Remember that observing strategy white paper writing workshop that we said we'd have in Tucson in November? Well, it's next week! Which means this week is the time to get our homework done. More on that on the issues as we go through the week.
>
> Below I have sketched out a plan for how we'll spend our time: basically we'll be in hacking mode for more or less the whole two days, with stand-ups at the start of each day and wrap-ups at the ends, and we'll encourage pop-up discussions (suggested at the beginnings of sessions, so that people can plan their time if they want to sit in). We have two rooms (thanks Beth!), including after dinner on Thursday (this is LSST camp, people! :-) 
>
> We had a bunch of good suggestions of how to make the remote participation work well, thanks for those.  We'll try and find some extra laptops and microphones to increase the presence of the remote people, and we'll use BlueJeans to get you to the group sessions. 
>
> Eric G, Eric B, Bob, Vishal, Seth, Kathy: as remote attendees, I'd suggest clearing your schedules as if you were attending the workshop, and sorting out with your chapter/section collaborators how you will join remotely. Skype, Hangouts and BlueJeans all work well - the main thing you all need is the *collective will* to make the connection happen.
>
> Please do reply all with comments, suggestions and questions - this is *your* workshop!
>
> Looking forward to seeing you all,
>
> Phil
>
>
>
> Thursday:
> 
> We'll plan on starting at 9am (after meeting up for breakfast/coffee etc at 8am), with a short walk through of the white paper as it stands, and a briefing of what we are trying to achieve. I will remind you that our goal is to get the white paper into a state where it could be posted to the arxiv, and that our focus at this point has to be on *metric quantification of key science cases* (with documentation of proposed alternative strategies of secondary importance at this stage). 
>
> Then, at 9:30am or so we'll do a round of stand up, where each *chapter editor* states the following things: 
>
> * What their key science cases=sections are 
* What must be in place in these sections before we post the paper
* What their group is going to achieve by the end of Thursday
* What its current roadblocks are (so we can unblock them)
>
> Finally, before we get started, there'll be an opportunity to propose a pop-up discussion that afternoon. We'll then get to work, probably at about 10:30am or so.
>
> After a lunch break c. 1pm, we'll do another call for pop-ups, and schedule them with locations so we have them in mind, and a quick call for roadblocks and help requests. Then, we'll be back to work. Pop-ups will be announced as we go, and will use one of the rooms (which one will depend on the expected size). 
>
> Then, at 1800, we'll do a half-hour-ish wrap-up where the editors again:
>
> * Say what their group achieved that day
* Raise questions and issues that came up, for group discussion
>
> We'll then have dinner, and then return to group writing at around 8pm.
>
> Friday:
>
>This will follow the same format, but without the initial walk-through, just a stand-up with the editors again saying:
>
> * What has changed in their chapter plan (some sections may have been dropped, or merged)
* What their group is going to achieve by the end of Friday
* What its current roadblocks are (so we can unblock them)
>
> and then we'll call for pop-ups again. These might have to happen in the morning as well as the afternoon, to fit them in.
> 
> Lunch at 1pm, then back to writing after a quick round of pop-up scheduling.
> 
> At the end of Friday (time to be decided, by us), we'll have one final wrap-up, where the chapter editors report:
>
> * What they have achieved, and can sign off on
> * What, if anything, still needs to be done (and how much time they need to complete it)
>
> After this, we'll finish with a group discussion of arxiv posting tactics and timetable.

**Comment by connolly** [comment]
I will also be around for most of the workshop on Bluejeans

cheers
Andy

**Comment by drphilmarshall** [comment]
Great, thanks Andy!

**Comment by MichelleLochner** [comment]
@drphilmarshall I will try to attend remotely, at the very least for the first hour and a half or so today and tomorrow. It's obviously difficult with the time difference but people can email or github me and I'll respond as soon as I can. Sorry I'm halfway round the world... :/

**Comment by drphilmarshall** [comment]
Thanks Michelle! Even being on hand electronically will be useful, I'm
sure.

**Comment by MichelleLochner** [comment]
@drphilmarshall What's the bluejeans details?

**Comment by bethwillman** [comment]
<http://bluejeans.com/>        Hi there!
You have scheduled a video meeting.
        Meeting Title: Observing Strategy Workshop         Meeting
Time: Thursday
November 19, 2015 • 8 a.m. MST / 2 days         *Join Meeting*
<https://bluejeans.com/339278241/85719?src=htmlEmail&g=onxxe5djpjagy43toqxg64th>
                (Join from computer or phone)

        *  ________________________________  *

        Connecting directly from a room system?

1) Dial: 199.48.152.152 or bjn.vc
2) Enter Meeting ID: 339278241
3) Enter Moderator Passcode: 85719 (DO NOT SHARE)

Just want to dial in on your phone?

1) *Direct-dial with my iPhone* <+1.408.740.7256,,#339278241%23,85719%23>
 or
*+1.408.740.7256* <+1.408.740.7256> (US)
*+1.888.240.2560* <+1.888.240.2560> (US Toll Free)
*+1.408.317.9253* <+1.408.317.9253> (Alternate number)
(*all numbers* <http://bluejeans.com/numbers>)
2) Enter Meeting ID: 339278241
3) Press #
4) Enter Leader Passcode: 85719 (DO NOT SHARE)
        *  ________________________________  *

        Want to test your video connection?
*http://bluejeans.com/111* <http://bluejeans.com/111?ll=en>


On Thu, Nov 19, 2015 at 8:56 AM, MichelleLochner <notifications@github.com>
wrote:

> @drphilmarshall <https://github.com/drphilmarshall> What's the bluejeans
> details?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/150#issuecomment-158099208>
> .
>



-- 
Beth Willman
LSST Deputy Director
Associate Astronomer, Steward Observatory
933 North Cherry Avenue
Tucson, Arizona 85721
520-318-8473
