### ISSUE TITLE
pull request https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/151

### ISSUE THREAD

**Issue by fedhere** [LSSTScienceCollaborations/ObservingStrategy#157]
hi phill,

do you have any feedback on this pull request and why you did not merge it? i did implement your suggestion of writing a script to generate the individual chapters makefiles

**Comment by drphilmarshall** [comment]
Pure overworked oversight, my apologies. PR now merged, with a giant thank you. Thank you Fed! :-)
