### ISSUE TITLE
Frequency of visit and filter change optimized for SN cosmology

### ISSUE THREAD

**Issue by jhrlsst** [LSSTScienceCollaborations/ObservingStrategy#159]
We suggest an observing strategy by changing a filter every day (or half day) during the LSST main survey for SN cosmology. This will help us to increase the number of SNe at low red-shift (e.g. z<1) and to distinguish SN Ia from other types of SNe. We aim to obtain 7-10 epochs s spread over 45 days or so for each filter. 

-Suggested Observing Strategy.
For simplicity, we assume the LSST main survey will cover the entire LSST fields for 3 days (I divide the entire LSST fields into 3 separate fields, which would be called Field 1 and 2 and 3. The sum of Field 1 and 2 and 3 is the LSST entire fields) . Thus for a day 1/3 of the LSST entire field would be observed. By changing the filter, every day, LSST can observe 6 filters for 1/3 of the LSST entire fields. We repeat 9 times for the same field, which will result in 54 visits (with 6 different filters) for the same field (1/3 of the LSST entire fields). We repeat the same for Field 2 which takes another 54 days. Then observe Field 3 for another 54 days. 
To visualize this idea
Day 1 : F(ilter)1 (for Field1)
Day 2: F2 
Day 3: F3 
Day 4: F4
Day 5: F5
Day 6: F6
Repeat this sequence for 9 times for the Field 1. 
Then observe the same sequences for Field 2 (it takes 54 days) and then do the same for Field 3. 

-Explore further details
*Sky coverage : Since the sky coverage visible to LSST changes every day,  we need to further examine the details of this strategy.
*Correlation with weather: we also need to examine impact of weather pattern to this strategy.

We plan to explore many aspects of details with simulations. We would like to invite members of other groups (in other science fields) as well as of SN group for comments/suggestions. 

I thank for the SN Cosmology group who participated the discussion (includes Michelle Lochner, Christopher Stubbs, Pierre Antilogus, Saurabh Jha, Ryan Foley, Zeljko Ivezic, Jeffery Newman, Michael Wood-Vasey and Eric Gawiser; if I miss anyone or have misspelling, I apologize.).

**Comment by jhrlsst** [comment]
jhrlsst: Jeonghee Rho

**Comment by drphilmarshall** [comment]
Hi @jhrlsst - Interesting! Can you please transfer this to the ["Suggestions for New OpSim Runs" board](https://github.com/LSSTScienceCollaborations/ObservingStrategy/tree/master/opsim)? Thanks!

**Comment by egawiser** [comment]
Not sure of the status of this - @jhrlsst, please close out the issue if this has been done i.e. transferred to the Suggestions for New OpSim Runs board.  In the meantime, I'm postponing the Milestone to May 5 internal review.

**Comment by jhrlsst** [comment]
This issue and discussion results in 
"Rolling Cadence Optimized for SN Cosmology"
at
https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/Proposal_SN.md.
