### ISSUE TITLE
Add MAF installation and testing material to website

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#16]
Copy this from [UK Cadence Workshop web page!](http://cadence.lsst.org/cadenceWorkshop/), after May 20 (to catch Lynne and Peter's new notebooks)

**Comment by drphilmarshall** [comment]
Andy, could you add the MAF content to the website when you're ready, please? I'm going to switch to working on the white paper latex. Thanks!

**Comment by connolly** [comment]
@drphilmarshall How do I stop the website from making all of the text centered (I would like it to be aligned to the left as a series of bullet points)?

**Comment by drphilmarshall** [comment]
I would like that too, but my css powers are weak. That's where all the
classes are set up and things like alignment are defined. Good luck!

**Comment by connolly** [comment]
OK done and pushed
