### ISSUE TITLE
Normal Plane OpSim run

### ISSUE THREAD

**Issue by caprastro** [LSSTScienceCollaborations/ObservingStrategy#162]
I propose an OpSim run in which the Galactic Plane within the normal declination limits of the wide-fast-deep survey is observed with the same cadence as the rest of the survey. For now, the northern Plane extension can be left as assumed for the current special proposal (30 visits per filter).

**Comment by drphilmarshall** [comment]
See [the proposal](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/Proposal_GP.md) for more details! Closing this for now, until someone comments or objects.

**Comment by rhiannonlynne** [comment]
Starting opsim run after attempt to match requirements in changes to config files.

**Comment by rhiannonlynne** [comment]
The Normal Galactic Plane opsim run completed and is available from the links at 
http://astro-lsst-01.astro.washington.edu:8080/ 
You can see that the galactic plane run is called 'astro_lsst_01_1004' (sorry for the terrible names). 
The sqlite link is
http://astro-lsst-01.astro.washington.edu:8080/db_gzip/astro_lsst_01_1004_sqlite.db.gz 
The standard MAF analyses for this run are also available at: 
http://astro-lsst-01.astro.washington.edu:8080/metricSelect?runId=3
and 
http://astro-lsst-01.astro.washington.edu:8080/metricSelect?runId=4

**Comment by drphilmarshall** [comment]
Thanks very much for doing this run, Lynne!
