### ISSUE TITLE
Cosmological sky definition

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#165]
Cosmology afficionados @MichelleLochner @jhrlsst @rbiswas4 @egawiser @wmwv @jmeyers314 do we have maps of "the cosmological extragalactic sky" that we expect to give accurate light curves, shape estimations and photo-zs for DESC science? The capability offered by @yoachim in #161 ought to be very useful to us, especially when considering early science, overlap with WFIRST and so on.

**Comment by rbiswas4** [comment]
@drphilmarshall, read the issue #161, but am confused about what you are suggesting here. 

Isn't the idea that we should finally produce MAF metrics that will gauge how good an OpSim strategy, which would be plotted up in MAF. So, it sounds like you are suggesting a pre-metric partial result, that can be plotted up, (which would be great!) but I am not sure what you have in mind.

**Comment by drphilmarshall** [comment]
I guess our cosmological parameter accuracy will scale roughly as the
square root of the sky area surveyed, and so we need to know how much
useable sky is provided to us by th esurvey, in the time period of
interest. If we have a metric which quantifies science performance after 1
year (which we should, right?), that metric will need to be able to
calculate how much of the sky is useable. Is it 17934 sq deg? 6534 sq deg?
The "useability" of a sky area has to be defined by us, and will be best
reported in terms of a *sky map*. I can imagine rolling cadences designed
by other people that are sub-optimal in terms of cosmological sky
coverage... so we need to be able to quantify that sub-optimality via a MAF
metric that calls a DESC sky map.

**Comment by rhiannonlynne** [comment]
To calculate the size of the area that meets your requirements, just add a
summary statistic that counts area/npix above a threshold (theresn example
in the amount of area that meets a threshold for the rapid revisit metric).
The sky map would show you where that area falls on the sky.

**Comment by drphilmarshall** [comment]
Great, thanks Lynne! It's likely that all the cosmology metrics will new to
make use of this technology. Do you have easy ways to access the star
counts and dust extinction from MAF ? I expect these are the main things
we'd need in the first instance - although I k ow the supernova group are
always concerned with photometric calibrion accuracy. The others will be
able to comment in more detail.

**Comment by rhiannonlynne** [comment]
Dust extinction yes, star counts.. Maybe not yet? (@yoachim?)

**Comment by rbiswas4** [comment]
@drphilmarshall 
Ok. So what you are asking us to be careful about is that the metrics should be calculable on any area of the sky (essentially what @rhiannonlynne said) and any time window. Sure.

**Comment by drphilmarshall** [comment]
Not just that: I'm saying that our figures of merit (constructed as
functions of lower level diagnostic metrics) will depend on the sky area we
define. At the moment, the SL figures of merit (eg mean time delay
accuracy, fraction of sample useable) assume that the entire survey area is
available to us. In practice that will not be true. The first thing we can
do is include a useable area as Lynne suggests, that is computed based on
the values of our metrics. The second thing we can do is define useable sky
area based on dust (via MAF) or other things (star counts, photometric
calibration accuracy, overlap area with WFIRST etc etc) that *we must
define as input sky maps*.

**Comment by rhiannonlynne** [comment]
I think I'd actually recommend doing that the other way around, Phil -- you
can calculate metrics on the whole sky and then decide how to combine
metric results which rise above a given threshhold (for each metric)
afterwards -- remember, the metric maps are really just big numpy arrays
and we can combine them in any way we want after the fact. That capability
doesn't exist *within* MAF yet, but we can look at adding some automatic
methods for this kind of thing. In the meantime, it's not too bad to do in
an ipython notebook. Here is an example of messing around with the metric
results after-the-fact, although it's not quite what you'd like to do (I'd
actually create a new mask, then set the mask bits true/false for each
pixel based on whether all of your metric values for that pixel reach the
values you want).
You could include the dust maps and star maps before the metric or after
the metric calculation, too.

**Comment by drphilmarshall** [comment]
Good, thanks Lynne - although I think I missed the link you sent...

Rahul et al: Whichever way we compute our figures of merit, we'll still
need to know where the dust, stars, good and bad photometric calibration,
and WFIRST field are! :-)

**Comment by yoachim** [comment]
Here's the quick notebook I put together showing how to use the dust maps. It computes the co-added depth, and then the depth after taking the dust extinction into effect, what we've been calling the extra-galactic m5 value.
https://github.com/yoachim/ObservingStrategy/blob/master/notebooks/MapExample.ipynb

And here's the most bare-bones example of how to write a MAF map, this just adds the galactic coordinates to the slicePoint information (so your metric can use that info when making computations):
https://github.com/lsst/sims_maf/blob/master/python/lsst/sims/maf/maps/galCoordsMap.py

**Comment by egawiser** [comment]
As the assignee (thanks, Phil!) I've read through the discussion above and think I'm doing a great job on this issue!  ;)   I agree with Lynne - different cosmological probes will have different thresholds in dust and star counts with which to define useable area.  So we need to use a Milky Way model to create a star counts map analogous to the dust map that Peter linked to; I suspect that using the dust map alone will get pretty close.

**Comment by egawiser** [comment]
Thinking more about this, some probes like LSS will have (statistical) performance that scales closer to sqrt(N_galaxies) rather than sqrt(N_area), where variable depth must be accounted for and really shallow regions (e.g., high dust extinction) have such low galaxy counts that it doesn't really matter if we include them in the "usable area" or not as long as depth is accounted for.  Thanks to Lynne, we have a metric for this already built into MAF - it's called galaxy_count.
