### ISSUE TITLE
Try AGN in its own Chapter

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#166]
As suggested in #152 and elsewhere.

**Comment by drphilmarshall** [comment]
@ohadshemmer @tanguita I'm halfway through this, check out the AGN branch to follow along:
```
cd whitepaper
git fetch
git checkout AGN
make
```
I am splitting the AGN science cases into sections, and storing them in an AGN folder. I am also suggesting new text in blue as I go, trying to anticipate the metric(s) that you are going to calculate in order to quantify performance in each science case. Feel free to edit away anything you see in blue and replace it with notes of the metric analysis you are doing.

**Comment by tanguita** [comment]
Great, thanks

**Comment by drphilmarshall** [comment]
@ohadshemmer @tanguita @nielbrandt @cmp346 git pull: AGN now has its own chapter! I had to guess who was leading/working on each section, please do edit. Where I have suggested new text, it's colored in blue and also needs editing. Hope you like the new set-up! :-)
