### ISSUE TITLE
New transients and variables chapters need editors

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#169]
Hi - now that we have two chapters on variables and transients, we need a couple of people to take responsibility for making sure each one gets done. For now (in Tucson for the face to face meeting), I have assigned the following people:

* Stellar and Binary Variables @AshishMahabal @lmwalkowicz
* Explosive Transients @ebellm @fedhere

My original list of 5 T&V chapter editors had @lundmb in it as well, but Mike's not able to be with us this week, so I figured he should take a back seat for now. Also, @StephenRidgway put a lot of the current T&V material into the files, but is also on the hook for the rolling cadence section of chapter 2 and also the "tensions and tradeoffs" chapter - so I spared him one of these two chapter. I hope that's OK - later on you might want to sub in and out. 

If you want to swap assignments, please do reply to this message, and edit the chapter tex files so everyone knows who the points of contact are.  Let me know what you think! Thanks.

**Comment by lundmb** [comment]
I actually was able to make it, but as a last minute sort of thing, so I just arrived at the hotel about 5 minutes ago

**Comment by drphilmarshall** [comment]
I just put the schedule up at [this link](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/workshop/Tucson2015.md), hope that helps!

Please note: the chapter editors have some presenting to do over the next couple of days: it'll be up to you to stand up and tell the rest of the group what you are going to achieve, what your roadblocks are etc. Hope this is OK - the primary function or such stand-up meetings is to focus our minds! No slide making is necessary - but you'll want your chapters looking spiffy by the end of each day :-)

**Comment by drphilmarshall** [comment]
Alright! Great job at the Tucson workshop, T&V chapter editors! I think you have earned the title with your hard work. And also thank you Mike, for your excellent contributions despite being passed over for the top job ;-) Good luck with your respective recruitment drives, let me know if I can help at all.
