### ISSUE TITLE
Key Science Cases for Variables and Transients Chapters

### ISSUE THREAD

**Issue by lmwalkowicz** [LSSTScienceCollaborations/ObservingStrategy#171]
The following science cases were identified by @lmwalkowicz, @AshishMahabal, @fedhere, @lundmb and @ebellm for inclusion in the (now two) chapters: 

Variables Chapter

- Discovery of Periodic Pulsating Variables
     - Galactic Structure form RR Lyrae - period recovery
     - Distance Ladder from Cepheids - period recovery
- Planet Populations: hot jupiters, young stars, extragalctic planets; star clusters, bulge and red dwarfs - period recovery, crowding metrics
- Age Mapping the Galaxy from Rotational Variability - period recovery, modulation of period
- Young Stellar Objects / FU Ori - colors, structure function, temporal sampling of colors to look for color difference

Transients Chapter

- Prompt Discrimination of Transients - desired result of a given metric may be different for different transients; develop generalized framework for working w transient model using light curve tool - work up specific example of transients to separate to stimulate work on other classes of transients; what about multi class discrimination, versus one class vs. everything else
     - CVs versus SNe versus TDEs (maybe relate AGN chapter)
- EM counterparts to GW transients
- Statistical Understanding of Transients Populations (e.g. SNe, whatever else)
- Age Mapping the Galaxy with M Dwarf Flares -
- Tracing Stellar Evolution with Eruptive Massive Stars

**Comment by willclarkson** [comment]
Looks good - a lot of the "Variables" information there is going to be
vital to Milky Way science as well. For example, we were thinking of a
hierarchical metric for Galactic Structure in the MW chapter along the
lines of the error in structural model parameters, which in turn would
depend on the period recovery fraction it looks like you are developing for
the Variables chapter.

One of the items on Kathy and my to-do list for this meeting is to find out
a bit more from the Variables experts what the current capability is for
issues like this... does any of your group (Variables people) have
availability to talk to Kathy and myself after about 3:45pm today please?

Thanks!!

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR330 or PHYS 150 lab or discussion).

**Comment by akvivas** [comment]
Hi Lucianne,

We may want to coordinate. We are including galactic structure as seen by RR Lyraes in The Galaxy chapter. Also, the star formation section will be mostly based on T Tauri and family variable stars. 

Keep us in the loop please. It should be in only one place, so we may refer to your chapter. 

Delta scuti and SX Phe should be great to trace structure as well. 

Kathy

Enviado desde mi iPhone

**Comment by keatonb** [comment]
Hi Lucianne,

I am working on a developing some tools for studying short period and/or multi-periodic variable stars (pulsating white dwarfs and others) from scatter in the measured magnitudes. These are not systems for which a period solution is directly possible from the LSST data, but should be a separate subsection of "Discovery of Periodic Pulsating Variables". I am working on a metric to determine detection thresholds for variability amplitudes that I hope to have done in the next week or two.  I hope that this can be included in the white paper.

Best,
Keaton

**Comment by StephenRidgway** [comment]
Hi Keaton,

Why is a direct period solution not possible?  With deep drilling and/or possible rolling cadences, it would be possible to cover part or all of the main survey with sample spacing just a little greater than 30 seconds, which I think is less than most WD pulsation periods.

Steve

**Comment by ebellm** [comment]
For variables: 

Discovery of stellar and compact binaries: period recovery, crowding metrics, Plane coverage; connection to Galaxy topics

**Comment by ebellm** [comment]
Transients: I think we need to focus less on the mechanics of distinguishing transient classes and more on potential science drivers.  For SN science that might be early discovery to find shock breakout and/or trigger flash spectroscopy, discovery of rare event types.

I'm working on the GRB science section (#67), and @soares-santos is working on EM/GW TOOS (#113)

**Comment by lmwalkowicz** [comment]
I should point out that this is not intended to be an exhaustive list of science cases-- basically, we sat around and tried to think "what are the 3-4 key science cases that we can put forward with associated metrics that test their performance?". It is my (our) hope that the community will read this and contribute additional science drivers with quantitative tests.

**Comment by lmwalkowicz** [comment]
I have updated the key transients cases to include EM-GW @soares-santos

**Comment by AshishMahabal** [comment]
And along with a "few" science cases we need to identify a few metrics that we can include as these will be the key to our ability to actually do the science. Again that list need not be exhaustive, but ideas for metrics that do not already exist will be very useful.

**Comment by fedhere** [comment]
@ebellm There are definitely two aspects: discovery/classification and scientific caracterization. The early discovery of inidividual SN w e.g. shock breakout signatures to trigger follow up I think is naturally addressed by the question "how well can we distinguish different transients and how soon". Then there is a long term statistical characterization that is also a science driver (e.g. how many families of SN Ia can we separate on a 5 year LSST sample). Realistically the case for early detection of shock breakout, companions, etc in the early lightcurve is extremely difficult with the current cadences providing one datapoint in one band.

**Comment by ebellm** [comment]
Fair point, @lmwalkowicz.  I'd only add that we should make sure the science cases (and their metrics) stress the cadences in all the ways we think relevant.  So I agree we don't need a separate science case for periodic compact binaries (largely in the Plane) if we're covering detecting pulsating RR Lyrae in the Plane.  But if the RR Lyrae search is only in the halo, then it's relevant.

**Comment by lmwalkowicz** [comment]
+1 to what @AshishMahabal said: for each science case, authors must think of their Figure of Merit and how it can be *measured* using MAF output. What will you measure and how will that tell you if you have succeeded?

**Comment by StephenRidgway** [comment]
I did not hear the first part of discussion, so maybe the following is redundant.

There may be some concern with distinguishing in a detection image new SN from CV’s and flaring dwarfs which rise above the single visit detectability threshold.  I’ve looked at some numbers, and for most flare stars, even if the stars are below the single epoch detection limit, they will be detected in a stacked image, or even in forced photometry of a single image, so confusion between SN and flares should not be a big problem.  I suspect the same will apply to CVs, since the faint ones are expected to have weaker flare activity, but probably some deep searches are needed to confirm that. This line of reasoning may justify not focussing on how to distinguish.

**Comment by ebellm** [comment]
@fedhere It's a philosophical difference: I think we should advocate for the most important transient science LSST can do, *especially* if it's not well handled by current cadences.  That's the point of this exercise, to identify potential improvements in the cadences and quantify them.

**Comment by jhrlsst** [comment]
SN cosmology group already has the metric to classify types of SNe (Michelle and Rahul). We will need to classify types of SN using the LSST data for within 50 days. I will add  a number of light curves from a few sample of SNe based on OpSIm output (Rahul is close to finish up) in the text both from deep drilling field and main survey, respectively.

**Comment by lmwalkowicz** [comment]
I might phrase it slightly differently @ebellm: the point of this exercise is not actually to suggest alternative cadences, it is to show the performance (or non-performance) of the current available OpSim runs on key science cases, and to develop a framework for testing future cadence iterations on those science cases. I def agree that we should advocate for the most important science cases LSST can do, but this paper is not the venue for roll-your-own cadence.

**Comment by ebellm** [comment]
@lmwalkowicz that's a better statement of what I meant, thanks.

**Comment by keatonb** [comment]
@StephenRidgway 

Depending on the details of the deep drilling and rolling cadence strategies, some period recovery may be possible. WDs typically pulsate with ~10 observable modes simultaneously with periods ~10 minutes. Resolving these periods typically requires extensive, continuous coverage.  I would be interested in looking into how well these periods can be recovered in the deep drilling fields. Perhaps some of the existing metrics for period recovery can be modified to test multi-period recovery and short period recovery.

The photometric precision will, at the least, reveal a sizable population of pulsating WDs through the distributions of measured magnitudes. We can do some interesting science with those distributions alone, such as studying the amplitude evolution through the instability strip (color space) for tens of thousands of WDs.

The metric that I propose to contribute assesses the lowest amplitude of variability that can be reliably detected at a given magnitude in a given filter and answers the most fundamental question here: Is this object variable (and how variable is it)? This is applicable to all variables with periods > ~ 1 minute. This will yield a fainter limit than the detection threshold for period recovery. It is relevant to evaluating the performance of OpSim runs because its performance will be affected by the number of visits per filter and exposure times for each filter (60 second exposures in u' have been proposed, for example).

**Comment by lmwalkowicz** [comment]
Virtual Hi-Five for being on the same page, @ebellm!

**Comment by jhrlsst** [comment]
Basic conclusion is that the number of data points and quality of data from deep survey are sufficient to
identify the source as SN and its classification.
However, the OpSim data from the main survey show only a couple of data points per band over 60 days of observing period. They are not insufficient to be classified and for some cases, it may not possible to identify the source as a SN.

**Comment by lmwalkowicz** [comment]
@StephenRidgway yes, Eric Hilton did his thesis on M dwarf flares in LSST, and it is true that most (not all, but most) dMs are detected in quiescence in the stacked images, which is great. Foreground fog no more!

**Comment by fedhere** [comment]
@ebellm @lmwalkowicz in fact separation of subtypes (e.g. SN w shock breackout/interaction w companion) is again at the core: lets put limit on what can be separated from what with the current metrics, and how long it takes us to say that something is a SNIa vs a TD vs a SNIIp. I am pretty sure we will not be able to pass the threshold of separating different families of phenoomena in the first few days, much les subtypes of SN. We can point out how poorly the current observing strategy performs on separating different flavors of transients, and then we can state how crippling that is to the science itself.

as for how to do it:  @tmatheson  is preparing a 1model-fits-all for transients with 8 parameters: 2 gaussian bumps and a linear decay. We can use that as input for the metric and get an output lightcurve. we can then fit that lightcurve to see how well the observed photometry constraints the 8 parameters (enough to tell a TD from a CV? a IIb from a Ia? ). This part is gonna be slow.

**Comment by StephenRidgway** [comment]
My suggestion is that an SN that excedes the detection threshold in a single visit can be identified as an SN with useful probability (possibly high probability) based on ruling out the most likely alternatives (from stacked images, forced photometry and knowledge of the variable sky statistics) and by position correlation with a nearby galaxy.  Detection in a single image (or a few closely spaced images) is probably required to enable flash spectroscopy.

**Comment by StephenRidgway** [comment]
A metric to detect and establish the reality of variation at the lowest level, even if too low to characterize, seems like a tool of very general utility - it could be used to clean target lists of nominally classified sources, as well as to identify targets needing follow-up.

Concerning your last point, does your metric require observation over a limited time interval, or can it be applied to a 10-yr dataset?  We are interested in the relation between global and differential photometry, especially as the best global calibrations may only be available years after data acquisition.

**Comment by fedhere** [comment]
@StephenRidgway  the way i am thinking about it: since you get an observed lightcurve back, which you then can fit, the metric is suited to work with transients of any time scale and observations along many time scales. which allows us to say: we can tell that this is interesting for follow up with 1, 2, 5, 50 observations (and if it is >1 then we can say "we can tell it would have been interesting for follow up, but we lost that train)

**Comment by fedhere** [comment]
@StephenRidgway @ebellm detection in a single image is inded required to initiate flash follow up, but it is not sufficient: if we cannot select objects that are strong candidates for flash spectroscopy we may run out of resources before we observe an interesting candidate

**Comment by fedhere** [comment]
It seems that we need to fold into the transient metric a measure of the depth of the observational stack on the transient field calculated up to the transient epoch to know how well we can separate true transients from a single observation.

**Comment by StephenRidgway** [comment]
That’s possible.  Alternatively we can assume that there is already a minimum stack available - e.g.1 or 2 years - and that forced photometry can be applied to it - this already gains several magnitudes, which is enough to detect most flaring/bursting stars. Responding rapidly to faint alerts earlier than 1-2 years into the survey will be difficult and low efficiency anyway, and maybe not worth the effort.
