### ISSUE TITLE
What were the Deep Drilling Field / Special Survey proposals in the Tier 1 OpSim Runs?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#173]
Chapter 2 needs updating to document the DDF/SS proposals that were included in the set of OpSim runs we are using (the ones in the table in Ch. 2). Kem says that this is all included in the "confluence page" so this issue should be easy to resolve! Assigning to @ivezic but will re-assign to Kem if I can find his GitHub address.

**Comment by rhiannonlynne** [comment]
@kem0cook
