### ISSUE TITLE
Deep Drilling Field / Special Survey Re-organization

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#175]
* [x] Comment out DDF chapter @drphilmarshall
* [x] Put discussion of the existing DDFs into each science section - how useful are they for your science? Needs diagnostic metrics by science teams. This seems to have happened naturally!
* [X] Commissioning discussion in each section? No. Few sentences in introduction @michaelstrauss 

Optional extras:
* [ ] Extend Special Surveys chapter to cover projects possible with Deep Drilling Fields @knutago
* [ ] Add text on boundaries of special surveys program? Total time, others? Conservatism. Reminders from SRD. @knutago @ivezic 
* [ ] Notes (warnings?) about the interaction between special surveys and main survey - any given OpSim run will contain this. @knutago

**Comment by drphilmarshall** [comment]
@nielbrandt thanks for the feedback! Would you like to have a go at summarizing the outstanding DDF suggestions (ie, those that have not been implemented in the tier 1 / chapter 2 OpSim runs) in a `\section` of this "Special Surveys" Chapter? @michaelstrauss has offered to help too. Thanks!

**Comment by drphilmarshall** [comment]
Ooh, this issue got well and truly forgotten. The DDFs are chronically under-represented in the current white paper draft as a result. @michaelstrauss @nielbrandt @knutago can any of you work on this over the next week? You'll want to remind yourself of [the original issue](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/175#issue-117929739) I expect!

**Comment by nielbrandt** [comment]
Unfortunately, I am fully saturated this week with travels to
Canada and Spain. My apologies.

On 4/28/16 3:00 PM, Phil Marshall wrote:
> Ooh, this issue got well and truly forgotten. The DDFs are chronically
> under-represented in the current white paper draft as a result.
> @michaelstrauss <https://github.com/michaelstrauss> @nielbrandt
> <https://github.com/nielbrandt> @knutago <https://github.com/knutago>
> can any of you work on this over the next week? You'll want to remind
> yourself of the original issue
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/175#issue-117929739>
> I expect!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/175#issuecomment-215528934>
>

-- 
-------------------------------------------------------------------------------
Niel Brandt; Department of Astronomy and Astrophysics; The Pennsylvania
State University; 525 Davey Lab; University Park, PA 16802 USA
Phone: (814) 865-3509; FAX: (814) 863-3399; Office room number: 514A;
AIM: Niel Brandt; WWW: http://www.astro.psu.edu/users/niel/index.html
-------------------------------------------------------------------------------

**Comment by drphilmarshall** [comment]
Thanks for letting us know, Niel!

**Comment by drphilmarshall** [comment]
@knutago - in the last part of my audit ( #304 ) I cleaned up the special surveys section so it is at least presentable. In its current state it makes no mention of the Deep Drilling Fields.  If you have a few mins, maybe give the PDF a quick browse and give us your opinion on whether the white paper *needs* to discuss the deep drilling fields in any other context than the science sections and chapter 2 - try searching for "drilling," I think you get a consistent set of references.

**Comment by rhiannonlynne** [comment]
Relevant, but maybe not something that has any need to go into version 1 of
the paper:
https://community.lsst.org/t/deep-drilling-whitepapers/732

**Comment by drphilmarshall** [comment]
Thanks Lynne! Added a footnote with this link.

**Comment by knutago** [comment]
Sorry for lack of response, have been swamped!  I will look at this tomorrow

**Comment by drphilmarshall** [comment]
Revisiting this: the DDFs are explained in Chapter 2, and are available in the OpSim outputs for people to quantify. I think we should leave them out of the special surveys chapter, and use that space to focus on *new* ideas for special surveys - there does not seem to be high demand for investigation of the white paper ideas. Closing this out: we can always re-issue ourselves with providing more DDF content if we feel that the white papers are under-represented.
