### ISSUE TITLE
Workshop registration page

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#18]
We need one. @connolly made one for the UK cadence workshop using Google docs, and embedded it in the meeting webpage, [check it out](http://cadence.lsst.org/cadenceWorkshop/#registration). Should we be pointing people at the main project and community meeting website for registration, @ivezic, or should we make our own registration page like Andy's?

**Comment by ivezic** [comment]
We should definitely use the same registration mechanism as for all-hands meeting, at
https://project.lsst.org/meetings/lsst2015/registration
It would be good to emphasize on our side too that the deadline is July 24th.
