### ISSUE TITLE
Re-ordering of Milky Way chapter 2015-11-19

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#182]
Outcome of discussion at Tucson (Thurs 2015-11-19): re-ordering of Milky Way chapter around science cases that are relatively well-developed by this point, and (in principle) straightforward to turn into metrics. Many metrics will likely call on those developed by Variability chapter team (both periodic and non-periodic). @akvivas @cbritt4 @ctslater @willclarkson @bethwillman @caprastro @dnidever @knutago @ivezic  + volunteers welcome!  Proposed revised chapter structure:

Need progress at the Tucson meeting:

**4.1. Introduction**

**4.2. Mapping the Milky Way Halo** - Tracers: RR Lyrae, red giants [surface gravity separated from dwarfs], metallicity maps w/ F+G main sequence stars. 

**4.3. Mapping the Milky Way Disk** - Science drivers include: finding rare objects, microlensing, and dust mapping... 

**4.4. Mapping the Milky Way with Positions, Proper Motions, and Parallax** (proposed merging of Chapter 5 with Chapter 4)

"Wish list" sections depending on availability of effort and strictness of whitepaper posting deadline:

**4.5. Mapping the Milky Way's bulge**

**4.6. Mapping the Local Volume with Resolved Stars**

-----

**Comment by akvivas** [comment]
Ok... new skeleton for the chapter is in place. There are individual files for each subsection in the MilkyWay subdirectory. You can start editing!

**Comment by willclarkson** [comment]
Kathy - excellent, thanks!!!

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR330 or PHYS 150 lab or discussion).

**Comment by willclarkson** [comment]
Hi @cbritt4 @caprastro - just FYI, we have a backup copy of the older MW_Plane.tex that Jay and Chris have worked on, and which was committed again by Chris just before the refactoring. One of my jobs is to update the refactored section 4.3 with parts of those science cases. So we have not lost all your work! Cheers -- Will

**Comment by drphilmarshall** [comment]
Good good! I notice that one of your sections (Mapping the Milky Way with Positions, Proper Motions, and Parallax) is not like the others (Disk, Bulge, Halo, Local Volume). Presumably the content of the old chapter 5 will get divided among the other 4 science sections, and a fraction of it will get quantified with metrics? I will go ahead and remove Chapter 5.

**Comment by willclarkson** [comment]
This initial reordering was done, closing this issue.
