### ISSUE TITLE
Magellanic Clouds chapter needs science sections, figures of merit

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#184]
@knutago @dnidever I just closed the old issue about sections in the special surveys chapter ( #41 ) , because we now have this new MC chapter to work in. It still needs sections, though!

For each of your science projects (which I think are not actually written down accurately in the chapter at this point, please make a copy of the `section_template.tex` file and fill in the subsections. Most important is to identify the key astrophysics parameter you want to infer/measure/find out about in each case, and then use this to define a figure of merit. Then, you can if you need to suggest a simpler proxy for this, that depends on other diagnostic metrics etc. How do your science projects depend on crowding? Imaging depth? Cadence etc?

**Comment by drphilmarshall** [comment]
Hey @knutago good to see you in Tucson! I just closed #177 as you now have an MCs chapter (re-implemented properly after the history re-write). The next thing to do is to make a section file for each of your science sections, and focus on the figure of merit associated with each of these science projects. Now you have a nice crowding metric, you need to use it in a figure of merit proxy! :-)

**Comment by drphilmarshall** [comment]
@knutago @dnidever 

Hi there! We missed you at the meeting this morning ( #293 ). When doing my audit ( #304 ), the only science results section I could see in the Magellanic Clouds chapter was the proper motions one, which has ideas for metrics but no quantitative results yet. So, at the moment the MCs chapter consists of a nice introduction, and then a "Future Work" section with the proper motions science case as a subsection. 

What shall we do about this, for Version 1 (whose "final draft" is due today)?

I think we have two options:

1. Add the MCs work back into "Special Surveys" and call out proper motions as one science case that is being worked on.
2. Comment out the MCs chapter entirely, and add it back in later when you have some results to show.

What do you think?

**Comment by drphilmarshall** [comment]
@knutago and @dnidever tell me offline that option 2) is the way to go for now, with the MCs chapter making a re-appearance at a later date. I will take care of shifting the content (including the proper motions science case) to the special surveys chapter, as soon as I can. Thanks!

**Comment by lundmb** [comment]
I'll quickly note that there is an exoplanet case that I wrote up and
should be in the directory for the Magellanic Clouds, although it does
reference the other exoplanets section for a more in depth discussion of
metrics, though it's possible to reproduce the metric results in that
section if that's preferred.

**Comment by knutago** [comment]
Thanks, Phil.

**Comment by drphilmarshall** [comment]
OK, thanks Mike - I'll try and remember to take a look when I get to this.
