### ISSUE TITLE
IMPORTANT: All forks and clones need deleting and remaking ASAP

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#191]
Hi @LSSTScienceCollaborations/observing-strategy-white-paper-editors @LSSTScienceCollaborations/maf-workshop-organisers,

I've seen a couple of very nasty conflicts today, resulting from the necessary deep removal of the PDF file. I had to redo this excision, and some fiddling around to repair some damage caused by (I think) a `git push --force`. To avoid this sort of thing happening again, can you please please do the following things before you do anything else? In particular, do *not* pull from the base repo (you will immediately regret it). 

If you are working in a fork:
1. Delete your fork (in its "Settings" menu)
2. Make a new fork
3. Clone this to your local machine, renaming (or better, replacing completely) your old clone. Work in that.

If you are pushing to and pulling from the base repo:
1. Rename (or better, delete) your local repo
2. Make a fresh clone and work in that.

Good news: the repo now only weighs 59Mb (reduced from 0.51Gb!). Bad news: if you have unpushed commits (or uncommitted edits) you will have to merge these into your new clone by hand. Sorry! 

Last thing: please keep your local clone up to date with the base repo, by regularly doing `git pull base master` (if "base" is the name you have given to the base repository). This will prevent the temptation to do `git push -f` when your clone gets out of date with the base repository, and `git push` doesn't just work... 

Thanks! And apologies for the inconvenience.

**Comment by willclarkson** [comment]
Thanks Phil - one question:

"If you are working in a fork:
1. Delete your fork (in its "Settings" menu)
2. Make a new fork
3. Clone this to your local machine, renaming (or better, replacing
completely) your old clone. Work in that."

By "Delete your fork," am I correct that this is the "Delete this
Repository" button in the "Danger Zone" at the bottom of the fork
"Settings" page? The warnings there are somewhat severe...

Best

Will



--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR330 or PHYS 150 lab or discussion).

**Comment by drphilmarshall** [comment]
I know, it sounds bad, but it has to be done. If you have files in your
fork (and hence also on your local machine) that have uncommitted or
unpushed changes, you'll need to re-edit those in manually once you have
made a fresh fork and clone - that's why you need to rename your local repo
to something like "ObservingStrategy-broken" or something before making the
new clone. As long as you have your edited files locally it should be easy
to copy them into the new clone.

I'm very sorry about this - its my mistake, I should never have checked in
the paper PDF file.

**Comment by drphilmarshall** [comment]
Hi all,

So far so good this morning - I have only heard one report of a terrible conflict when pulling from the base repository. I think the problem was actually caused by a regular push (not forced), but from a polluted repository that had the old PDF history still in it. The lesson for us now is: *please don't push directly to the base repository until you have first tried to pull from it!* If you get a lot of conflicts, you need a fresh fork/clone. 

Thanks!
