### ISSUE TITLE
Large scale structure section

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#196]
@egawiser @rhiannonlynne @other authors... I think quite a lot of work on the large scale structure section and metric has already been done (Awan et al. in prep it says), can you try and put some of this in the white paper today? Particularly the metric description and the figures referenced in that section. Can we get Humna Awan on github to do this?

**Comment by drphilmarshall** [comment]
@egawiser Just a reminder of your task: extract highlights from Awan et al and insert into the white paper, potentially using the discussion section to lay out the next steps in your ongoing investigation. Thanks!

**Comment by MichelleLochner** [comment]
@humnaawan and @egawiser any progress on this? Is this maybe something to focus on getting done at the workshop if you're both going to be there?

**Comment by drphilmarshall** [comment]
I think this was closed by #550 #590 and #601 - thanks all!
