### ISSUE TITLE
Weak lensing section

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#197]
@StephenRidgway et al. Please update the white paper with any work you guys have done on the weak lensing metrics. What are the most important issues still remaining here and who can we get to help with them?

**Comment by drphilmarshall** [comment]
@jmeyers314 Has been the main contributor from WL. The main issue is to
define an overall figure of merit (ie a proxy for dark energy parameter
accuracy) which captures all the important aspects of observing strategy.
Key things to think about will be: photo-z accuracy (metric to be created!)
and Neff at least. Neff is important for checking that the WL precision
stays high, as the main survey gets eroded as new strategies are proposed.
It will also allow us to assess different strategies for their ability to
provide early (eg year 1 or 3) WL results. Photo-z accuracy needs a
separate thread.

**Comment by StephenRidgway** [comment]
I contributed paragraphs on randomization of optics angles, which is in, but nothing since.

**Comment by drphilmarshall** [comment]
This section looked in pretty good shape to me - thanks @jmeyers314 ! I'm going to close this, and we'll see what the internal reviewer says :-)
