### ISSUE TITLE
White paper design

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#2]
* [ ] Chapter headings, with responsible authors.
* [ ] Chapter layout template, with sections to be filled in before and after workshop.

**Comment by drphilmarshall** [comment]
Hey @bethwillman what do you think of the science areas implied by the chapter headings in the [white paper design notes](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/notes/whitepaper-design.md)? Are we missing anything there? Great if you can edit them into shape...

**Comment by bethwillman** [comment]
For what its worth - Knut Olsen and Kathy Vivas have collaboratively started an LMC/SMC roadmap already so they are good choices.  For Galactic Plane science - I especially support Kasliwal and Clarkson, as already listed.  Will has already done some lifting along these lines within our collaboration.

**Comment by drphilmarshall** [comment]
OK, I updated the [white paper design](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/notes/whitepaper-design.md). @ivezic, @bethwillman  can you please check that this looks close enough to what you had in mind, please? We need the repository to be in good shape when the first announcement goes out.  There's also a [chapter template](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/notes/chapter-template.md) that also needs to be close enough. I'd suggest jumping in and editing in situ, in the interests of time!

**Comment by drphilmarshall** [comment]
Closing this for now, as we add in section leads (#14) - we can always rejig the WP after we talk to everyone in June.
