### ISSUE TITLE
Galaxy chapter 4.3: Figure of merit for Dust

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#202]
@pmmcgehee - Can you take a look at the strawman metric for Dust currently in Section 4.3.2 please?

Additionally, we need a figure of merit at least to first-order for the ISM dust... it sounds like something as simple as magnitude and color precision across the filters, propagated through into errors in derived parameters as you suggest, would be a reasonably straightforward figure of merit. 

Issues with the 3D distribution assumed, as well as crowding, etc., could be implemented in a future round of edits / updates.

**Comment by willclarkson** [comment]
Strawman figures of merit for Dust have been added to the Dust section description. I'm closing this issue for now, with the expectation that more detailed development will take place once the FoM is actually implemented.

**Comment by drphilmarshall** [comment]
Good plan.
