### ISSUE TITLE
Explosive Transients / Milky Way overlap

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#205]
Hi @bellm and @fedhere - We (@akvivas, @willclarkson and the Milky Way folks) would like to know a bit more about the framework you currently have for recovery of nonperiodic variables, since a number of our metrics will likely depend on them. (We expect that many of our metrics would call your metrics, see e.g. the current version of Section 4.3.2 for examples.)

When you get time, could you point us to any examples of implementations of metrics you currently have for recovery and characterization of non-periodic variables please?

**Comment by ebellm** [comment]
Hi @willclarkson: this is an old issue and I see that you have done a lot of nice MAF work in the MW chapter--is there any specific linkage or discussion you want to see in the Whitepaper?

**Comment by willclarkson** [comment]
Hi @ebellm (cc @akvivas) - That issue was us trying to work out what wheels we didn't need to reinvent for the Galaxy chapter; our vision was to build compound metrics / Figures of Merit that called the metrics you guys were developing for the transients and variability chapters. In the interim we went with @yoachim 's TransientMetric for our simple GalacticSupernova Figure of Merit. But, a number of the "recovery of transient population X" metrics we're discussing in the Milky Way Disk section (MW_Disk.tex, Section 4.3) I think should build on the metrics your group has been developing. 

At this stage I don't have anything specific to request, particularly given the deadlines this week. 

However, for next week and beyond, I think we should pick up this thread more. @cbritt4 @caprastro and Laura Chomiuk are also thinking hard about some of these issues, so I recommend they be included in the discussion.

**Comment by ebellm** [comment]
Sounds good.  We likewise have stuck mostly with simple metrics for the whitepaper, but yes, let's explore useful overlap going forward...

**Comment by willclarkson** [comment]
Hi @ebellm - OK great. I'll close this issue for now, but we can pick this up a little later on.

cc @akvivas
