### ISSUE TITLE
Time Delay Lens Cosmography as a template white paper section

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#21]
* [x] Update the chapter template
* [x] Discuss with SOC
* [x] Make amendments
* [x] Start a skeleton white paper, closing issue #3 
* [x] Sketch subsections of TDC section, with very brief notes on what could go where.
* [ ] Discuss with SOC and other section leads
* [ ] Make amendments, ready for fleshing out section

**Comment by drphilmarshall** [comment]
While I am putting together the latex for the white paper, please let me know what you think of the updated notes on the chapter design at 

https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/notes/chapter-template.md

Our chapters are planned to have multiple sections, one per science case. In the chapter notes I suggest we have the section leads think of them as "science projects" that they actually plan to do, so that they can then write their sections in familiar "observing proposal" mode. 

I also suggest they think about pulling their various metrics into a "figure of merit" that summarizes in a single scalar how good an (opsim) observing strategy is for that science project. Hopefully this might help people think  about what a metric is, too. 

Comments welcome!

**Comment by StephenRidgway** [comment]
The chapter-template explains that a chapter should be subdivided by science projects - that is clear for science oriented chapter topics like: solar system and variable stars.

However, there are also non science oriented but rather technique oriented topics like: survey uniformity, dithering, rolling cadence, astrometry.

And there are science topics that are overlapping: such as galactic plane and stellar variability,

I believe that a list of chapter titles is needed, and in some cases maybe an explanation of how and whether the different ways of parsing the content are merged or duplicative.

I missed part of the telecon, in case this was worked out early today.

Steve

**Comment by drphilmarshall** [comment]
Thanks Steve! You can see the chapter titles in our other white paper
planning document, here:

https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/notes/whitepaper-design.md

I think that even in the case of the chapters that are titled around mini
surveys or generic observing strategies those chapters can be used to
collect together a set of related science cases (projects) that share some
common features. Would you agree? Certainly it would be easier to see this
if the non-science titled chapters were sectioned in detail in the
whitepaper-design document! Perhaps you could have a go at this for the
chapters you will be working on?

The big advantage of sectioning in this way is that it will enable us to
divide and conquer the work much more easily: every section lead's task
becomes the same (write a section following the template provided). The
resulting document will be easier to read then, as well - and the whole
will be represented by a uniform set of MAF metrics, as required.

**Comment by drphilmarshall** [comment]
@StephenRidgway wrote:

> I had a shot at this (tuning the [whitepaper outline](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/notes/whitepaper-design.md)).  I think it’s important to converge on this before the leads telecon, since it is in some respects the most tangible evidence for what is expected.
> 
> With two orthogonal axes (science and technique) there is no one-dimensional organization logic that keeps all closely connected topics co-located. I didn’t see any way to improve on the chapter sequence of the previous draft.
>
> First, I updated the intro to reflect the current distinction between strategy and cadence.  
> 
> Second, I redistributed variables and transients in a different way - which makes sense to me but is not unique.  One particular point, I put very slow variables (AGN, etc) in the uniformity section, since achieving long time series with minimum gaps is very close to a uniform time sequence, rather than in the “variable” section, which is more about adequate sampling over a limited time range.
>
> Finally, I hacked the descriptions of most of the sessions to, I hope, be more explicit and more complete.

Interesting! When I dreamt up the "Keeping it even" chapter, I had in mind a set of science cases that only required uniformity in the stacked image, not uniformity or longevity in the time sampling. The SN and lens time delay groups mainly care about the balance between night-to-night cadence and season/campaign length, not about dithering choices or stacked image depth - so I had them together in a chapter defined by time domain science.

The chapter that makes least sense to me, organisationally, is the deep drilling one, actually - because we plan to have several different *types* of DDF, used by different science teams. If anyone can think of a better way to collect together the DDF science projects, now, as Steve says, would be a good time to hear it.

**Comment by StephenRidgway** [comment]
Hi,


I thought that I understood from discussion Tuesday that there is a list of persons who have registered for the cadence workshop, but at the registration site I only find an inclusive list for all persons attending during the week.  Can anybody point me to the cadence workshop attendee list, or confirm that there is not one?

Steve
