### ISSUE TITLE
Galaxy chapter 4.6: FOMs and metrics to be coded

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#211]
Hi @yoachim - following our discussion, I believe you intend to code up some of the figures of merit / metrics that were communicated in the old Chapter 5. Also for interest: @akvivas @caprastro @bethwillman 

A lightly edited version of that material (including description of the figures of merit) is now part of the new Chapter 4. It's currently the final section in chapter 4 (which will probably still be the case even if we run out of time to implement 4.4 and 4.5 in the text).

Thanks!! -- Will

**Comment by willclarkson** [comment]
Hi @yoachim - just checking in on this action to code up the figures of merit that had been indicated in the old chapter 5 bullet points (now found in chapter 4); is there anything you need to help with this?

Thanks!! -- Will

**Comment by willclarkson** [comment]
Hi @yoachim - do you have any availability later this week to chat with me (@willclarkson) about the epoch distribution of parallax factor in your nice astrometry metrics notebook please?

cc @akvivas

Thanks!! -- Will

**Comment by yoachim** [comment]
Sure, I should have some free time in the afternoons (west coast time) this week.  I need to update those old notebooks because I did tweak some things in the final version.

**Comment by willclarkson** [comment]
Closing this issue. Thanks @yoachim !
