### ISSUE TITLE
Rolling cadence notes in the "Special Surveys" chapter

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#215]
Hi @StephenRidgway - I think I heard this morning that a better place for the Rolling Cadence discussion might be the Special Surveys chapter, at the end of the white paper (since I don't think there will be any suitable OpSim databases for a while). I think it's likely we will rename the Special Surveys chapter to "Proposed Surveys" or something, and I think using a fraction of visits to enhance the cadence in certain sky areas in a rolling cadence scheme is just such a proposal.

To help people think about rolling cadence, I have added a link to your and Kem's notes (extracted from docushare and made visible as a Google doc) to the [OpSim runs suggestion board](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/README.md). If you have a better web-visible version of this document, please do update the link. When we have moved your Rolling Cadence notes to the special surveys chapter, you could ask for comments by replying to this issue. Thanks!

**Comment by StephenRidgway** [comment]
I agree, sounds good.

**Comment by drphilmarshall** [comment]
Hey @StephenRidgway - I just noticed that the Rolling Cadence section is still in Chapter 2, not Chapter 10! Do you have time to move it and make sure everything makes sense, today?

**Comment by StephenRidgway** [comment]
Hi Phil,

I did not know that it was to be moved.  Sorry I am leaving for the airport now, on a couple days of serious vacation, then at the LSST "Maximizing Science in the Era of LSST” workshop for 3 days.

I think that section is self-contained and could be moved as a chunk, if somebody is willing.  If I see that it has not been moved the next time that I’mfree, I’ll do it - otherwise review it in the new location.

Steve

**Comment by drphilmarshall** [comment]
I'll take it on then - I love refactoring modular code :-) Have a good vacation, Steve!

**Comment by drphilmarshall** [comment]
Becuase the rolling cadence section makes use of 4 existing OpSIm outputs, I decided it needs to stay in chapter 2. I did some editing of it, still!
