### ISSUE TITLE
Post-Tucson Issue Clean-up

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#219]
Dear Chapter editors: 

Thanks for all your efforts in Tucson! You and your teams made a ton of progress, it was brilliant to see the paper transforming into a coherent, presentable set of science projects :-) Let's keep up the momentum: if we are going to hire some LSST publications board reviewers in early December so we can go through their reports on the Sunday/Monday before the AAS meeting, we have to move fast to get the white paper into reviewable shape. Remember, the bar is low: we are aiming for something we are happy to have advertised on arxiv with our names on it, not a final version suitable for a journal.

So, momentum: can you please spend some time going through your chapter's issues, aggressively closing (or re-naming) the old ones and making new ones that contain the work you need to do? This will be important for working with your growing teams (as they take on individual tasks), but also for the whole group (who will thrive on a small, focused, not out-of-date issue list). Keep calling on individuals if you need help or feedback! You'll find it helpful to make sure the labels are accurate too, so you can filter your chapter's issues separately. Great if you can check your chapter of f the list when you are done. Thank you! :-)

* [ ] Introduction: @bethwillman @connolly
* [ ] OpSim Examples: @ivezic @yoachim
* [ ] Solar System: @davidtrilling @rhiannonlynne
* [ ] The Galaxy: @akvivas @willclarkson
* [ ] Variables: @AshishMahabal @lmwalkowicz
* [ ] Magellanic Clouds: @knutago @dnidever
* [ ] Transients: @ebellm @fedhere 
* [ ] AGN: @ohadshemmer @tanguita
* [ ] Cosmology: @MichelleLochner @egawiser
* [ ] Special Surveys: @StephenRidgway @knutago

**Comment by egawiser** [comment]
Thanks, Phil, for pushing all of this forwards!  For those who weren't there in person for the wrap-up, could you please describe the "meet before AAS" plan in more detail (email is fine)?

**Comment by drphilmarshall** [comment]
Hi @egawiser - I thought your question deserved a fuller response, now posted in #222 . Great to hear your thoughts on it over on that thread. 

All: have fun closing out your issues! :-)
