### ISSUE TITLE
arXiv posting timeline

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#222]
Hi @LSSTScienceCollaborations/observing-strategy-white-paper-editors @LSSTScienceCollaborations/maf-workshop-organisers ,

At the end of the Tucson face-to-face meeting, those of us in the room tentatively agreed on the following plan for posting the white paper to the arXiv. This needs digesting a bit, because we are talking about doing something rather different to standard practice in astronomy.

* Friday December 11: Send white paper for LSST project review (@michaelstrauss to find out the correct procedure for this paper)
* Friday December 11: Let project sims team (ie @rhiannonlynne and @yoachim) know if your science section's metrics are ready to be absorbed into the science verification metric analysis
* Mid December: OpSim re-runs finish, and science verification is run (hopefully including some new white paper metrics) by the sims team (led by @ivezic). Replace numbers and figures in science metric analysis sections with new ones from re-run analysis.
* Sunday/Monday of AAS meeting (January 3/4): Gather in Florida and discuss the LSST paper review and the new OpSim analysis results, decide if paper is postable to arXiv.

The reason why this schedule is not quite as scary as it might seem at first is that the idea is that *the arXiv v1 posted white paper will not be a finished paper*. The thought is that arXiv is the right place to advertise this ongoing project to all potential stakeholders in LSST science. We want people whose science will depend on LSST's observations to be part of the discussion about how the telescope is scheduled: presumably they will be motivated to make quantitative assessments of any proposed observing strategy in the same way that we are, and so will be interested in working with the science collaborations in contributing metrics. If this is our primary goal, it makes sense to post the white paper as soon as possible, so that the community can react, and participate in improving it. 

Indeed, the white paper is in some sense *already published* (since we are developing it in the open), so really the only question for us is when should we take advantage of our single biggest advertising opportunity? The feeling in the room in Tucson was that it might be possible to post the paper right before the AAS meeting, so that it could be discussed well at the LSST town hall meeting on the Thursday. Obviously only a few science projects will have metric analysis done by then, but the hope was that all of them would lay out a plan for their metric analysis, and be in various well-documented stages of its execution. This is why I keep going on about describing your figures of merit, and how they might be more simply approximated, and also why the term "pseudocode" keeps floating around: these are important elements of the planned metric analysis that can (should?) be written down even before the metric coding has started.

So, what do you think, everyone? Your comments are most welcome! It would be great to hear good arguments for and against the above plan. Thanks!

**Comment by rbiswas4** [comment]
Could I ask for a clarification about the pre-AAS meeting. If the above plan is followed, can you clarify if the arrangements for the pre-AAS meeting would be outside AAS (ie. will *not* require registration at AAS which I think will be preferable.) The next deadline in AAS registration seems to be Dec 15, and it might be helpful to know the answer well before then.

**Comment by bethwillman** [comment]
Hey Phil

As a longtime member of the Publication Board, I think it's inappropriate to send a paper to the pub board before its in the final form before posting on arXiv (or another public forum).

Was there explicit discussion of this on Friday?

Beth

**Comment by rhiannonlynne** [comment]
I agree with Beth about the pub board. I think I misunderstood the plan, I
had thought that what would be advertised at the AAS was the current (in
progress) github repo, rather than an arxiv/pub board reviewed paper.

**Comment by StephenRidgway** [comment]
I understood the reason for contacting the pub board to be that the objective of reporting the paper for the AAS conflicted with updating the metric numbers with a rerun of all  relevant simulations, and an assumed review time of 3 weeks, and the only way to work it was to coordinate with the pub board - (I inferred this could mean to review the paper with the old numbers and update the numbers later, or it might mean a plan to accelerate the review process).

**Comment by drphilmarshall** [comment]
Good that we are having this discussion! I asked @burchat for clarification about the LSST publication policy for papers that are being developed in the open (like this one is), but, @bethwillman, it sounds as though you have the answer already, that LSST review will be required before we post to the arxiv. There was discussion of this at the end of Friday: there was some (but as it turns out, not full) support for posting the paper to the arxiv during the AAS meeting, and then discussing it at the Thursday LSST town hall.  We can carry on pointing people to the paper on GitHub no problem, including at the AAS meeting (if we want).  

I think the main question for us is: what is the white paper's "final form," that it must be in before it gets sent first for LSST review, and then to the arxiv? The sense I got from the room on Friday was that a post-able version of the white paper would have at least *some* complete science sections (with MAF results for a set of OpSim runs), and  comprehensive plans (with figures of merit defined, and metrics designed but not necessarily implemented) for all others. Having such a paper ready to go by early January seemed doable to the group, with the caveat that we needed to explore the LSST review requirements. I expect others will be less confident, though. If we envisage this white paper being a living document, with multiple versions posted to the arxiv at various intervals, we can focus on the question of what version 1 should look like, and by when. If it is to be a more traditional white paper, that would push us to defining what a finished version must look like before we post it. 

Given the multiple-year task facing us, I would recommend that we follow the living document route - and if there were no other time pressures, I'd suggest that we complete just enough science sections so as to make it easy for a new contributor to see their own way to a MAF analysis complete with meaningful figure of merit. That way they could (in principle) join in and start quantifying LSST science performance in short order. For me, the main danger with posting early is that we will attract new contributors without a good set of example metric analyses in place for them to adapt and extend. Having said that, it's usually very important to identify all stakeholders as soon as possible...

**Comment by ivezic** [comment]
I think it is likely that this paper would fall under the purview of the LSST Project Publication Policy.
There are a few detailed policy questions that might have ambiguous answers and I will discuss
them with the Project Science Team tomorrow. I will provide further details here when available.

**Comment by MichelleLochner** [comment]
Thanks for opening the discussion on this on github @drphilmarshall, it's helpful for those of us who weren't at the meeting! I personally do think all sections need to be in a relatively complete form in terms of science cases, how we expect observing strategy to affect them qualitatively and at least, as you said, some discussion of how a relevant metric would be implemented, with an actual coded metric being the ideal case. I think some time in January is a fairly feasible goal for version 1, modulo the review process (which I'm sure will be useful in itself).

**Comment by AshishMahabal** [comment]
Any updates on this? I have had a couple of queries from new potential contributors. 
If it is to be first week of Dec by when we need to wrap up the text ready for review, additional contributions will be difficult.
@drphilmarshall @ivezic

**Comment by ivezic** [comment]
We had to cancel PST meeting due to poor attendance - we'll talk about this issue next Monday.
It is likely that we will need to properly review this paper, and it's unlikely that we'll be able to post
on arXiv before AAS meeting. I will send an update next Monday afternoon. Happy T-day!

**Comment by MichelleLochner** [comment]
Any thoughts on this? It would be good to come up with a reasonable timeline.

**Comment by ivezic** [comment]
I can confirm now that we need to go through the Project's Pub Board review before
posting to arXiv (despite the fact that the text is essentially public on github). 
I would propose that we aim to have the manuscript ready for review by the 
time of AAS meeting in January, or soon afterwards (e.g. we might receive good
comments if we talk about it at the LSST AAS Townhall meeting on Thu evening)

**Comment by drphilmarshall** [comment]
Thanks very much for sorting this out, Zeljko!  Aiming to have the
manuscript ready for viewing at the AAS meeting, and submitting for review
shortly afterwards, sounds sensible. What was the feeling in the project
science team about submitting an in-progress paper, with complete MAF
analysis only present in a handful of science cases (but even the
unquantified science cases presented tidily), both for pub board review and
to the arxiv?

**Comment by ivezic** [comment]
I think that whatever the team will decide is a presentable well-rounded
work can go to the review and eventually to arXiv. The concept of 
a living doc is fine here too.

**Comment by drphilmarshall** [comment]
OK, good. Let's do what we can before the end of the quarter, and see what
shape we are in at AAS, then.

**Comment by AshishMahabal** [comment]
Indeed, this is good. We can now call on TVS folks who said they can contribute after first week of Dec.
