### ISSUE TITLE
Adding text to the whitepaper

### ISSUE THREAD

**Issue by ShashiKanbur** [LSSTScienceCollaborations/ObservingStrategy#224]
Hello, I created a fork and have have added some text to the variables.tex file - mainly some additional science projects that could be done with LSST data. My fork has my name, Shashi Kanbur in its label. Can people see it? I think I have initiated a pull request. I wanted to ask what is the next step? Will I be notified if the pull request is fulfilled? Any advice would be helpful Im a novice at this.
Let me know.
Thanks,
Shashi Kanbur

**Comment by StephenRidgway** [comment]
Hi, thanks for contributing!  We will probably have to wait for Phil to decode the git status, as I see your additions have not yet propagated to the master.

**Comment by drphilmarshall** [comment]
Hi Shashi! Thanks for your edits. I haven't seen a pull request from you yet, it will appear in [this list](https://github.com/LSSTScienceCollaborations/ObservingStrategy/pulls) when it's gone through properly.  Once @AshishMahabal and @lmwalkowicz see your PR, they will check it and respond, probably just merging it - and you will be a contributor :-)

**Comment by ShashiKanbur** [comment]
Hello, I did issue a pull request which I can see here https://github.com/pulls, but can you see it?
Im not sure what else to do.

**Comment by migueldvb** [comment]
@ShashiKanbur the pull request was based on your own repository. You 
need to open a new pull request and select as base fork the parent
repository `LSSTScienceCollaborations/ObservingStrategy` with default 
base branch `master`, and head fork `ShashiKanbur/ObservingStrategy`
with branch `ShashiKanbur-patch-1`

**Comment by ShashiKanbur** [comment]
Hello, thanks, I tried doing what you suggest - can you see the pull request now?

**Comment by migueldvb** [comment]
great, it is here #226 now!

**Comment by migueldvb** [comment]
@ShashiKanbur great, it is here #226 now!

**Comment by ShashiKanbur** [comment]
Hello, I added an update to variables.tex but my head fork with base branch *ShashiKanbur-patch-1* doesnt compile because of a latex error in sn.tex. How can I correct this?

**Comment by migueldvb** [comment]
This error was fixed in the master branch so you can rebase your ShashiKanbur-patch-1 branch onto master and push them up  to your github repository using these commands.                                
                                                                               
```                                                                            
git pull origin master:master                                                  
git checkout ShashiKanbur-patch-1                                              
git rebase master                                                              
git push 
```

**Comment by drphilmarshall** [comment]
Looks like this was resolved by https://github.com/ShashiKanbur/ObservingStrategy/commit/0b892403c4c64bd800215fd4f04a093a3aca0c52 - thanks Shashi!
