### ISSUE TITLE
Pre-Workshop MAF Tutorial?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#23]
In the beginning we discussed having a pre-workshop remote MAF tutorial session, like last year's dry-run, to get people ready to come to Bremerton and code. Will we be doing that again this year? If so, do we need to do anything before the kick-off telecon? I guess the section leads will need to be familiar with MAF - or at least, have people that are, that they might want to send to a dry run.

**Comment by bethwillman** [comment]
Thais is getting scheduled now, and was announced in the second workshop announcement. Did you get that today?

Beth

**Comment by drphilmarshall** [comment]
Ah yes, sorry - I see it now:

A 3-hour, remote training session in the use of the LSST Project's Metrics
Analysis Framework (MAF) will be held mid-July.  Please register your
availability if you would like to participate:
http://doodle.com/sb5thc7ynyd98h4r

I'll move the milestone date (for issues that need resolving by this
tutorial) to July 10th for now.

**Comment by drphilmarshall** [comment]
[Done.](https://github.com/LSSTScienceCollaborations/ObservingStrategy/milestones)
