### ISSUE TITLE
AAS2016: editorial meeting plan 

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#235]
NB. 25 seconds of action required below!
-----

Hi @LSSTScienceCollaborations/observing-strategy-white-paper-editors @LSSTScienceCollaborations/maf-workshop-organisers 

For many of us this is the last week of the quarter before the winter break, something I am sure you are all looking forward to! Thank you for all your efforts on the observing strategy white paper this year: it's been impressive to see it forming out of all your LSST hopes, dreams, fears and worries :-)  

We said in #222  that we would aim to go through the white paper at the AAS meeting, and decide whether or not to submit it for LSST review at that time. I suggest we meet on the Monday (January 4th) for this activity. The [deadline for "splinter meetings"](http://aas.org/meetings/winter-meeting-session-proposal-information-and-deadlines#Splinter_Meetings) is tomorrow, and booking one would cost a few hundred bucks (even with minimal support requested). 

Action: Please edit the list below **today** if you will be able to make it to an editorial meeting on that Monday, and we can decide whether or not to put in a splinter meeting request tomorrow. I can imagine meeting in a hotel room or cafe instead, if very few of us will be in Florida then. 

* Phil Marshall (in person)
* Zeljko Ivezic (in person)
* Eric Gawiser (in person)
* Lynne Jones (remote)
* Peter Yoachim (in person)
* Your Name (in person / remote)

Comments welcome!

Phil

**Comment by ivezic** [comment]
Zeljko - in person.

**Comment by MichelleLochner** [comment]
Won't be able to make it at all, sorry @drphilmarshall.

**Comment by AshishMahabal** [comment]
Ashish - remote
Am getting there in person only on the 5th

**Comment by jgizis** [comment]
Gizis -- remote (probably; definitely not in person)

On Mon, Dec 14, 2015 at 4:13 PM, Ashish Mahabal <notifications@github.com>
wrote:

> Ashish - remote
> Am getting there in person only on the 5th
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/235#issuecomment-164561344>
> .
>



-- 
John E. Gizis
Professor
Department of Physics and Astronomy
University of Delaware

302-831-2668

**Comment by knutago** [comment]
Nope, traveling that Monday.

**Comment by egawiser** [comment]
In person!  (arrive MCO 7AM, must leave for Undergraduate Reception setup at 5PM)

**Comment by akvivas** [comment]
Nop, I can't make that day neither in person nor remotely. Sorry!

Kathy

---
Kathy Vivas
akvivas@gmail.com

**Comment by connolly** [comment]
I can do it remotely but not in person

cheers
Andy

**Comment by willclarkson** [comment]
Me too - remotely but not in person.

Cheers

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR330 or PHYS 150 lab or discussion).

**Comment by StephenRidgway** [comment]
Yes, 90% chance remote, 10% chance in person.

**Comment by bethwillman** [comment]
I'm traveling Monday & land ~ 2pm.

On Mon, Dec 14, 2015 at 2:32 PM, Phil Marshall <notifications@github.com>
wrote:

> NB. 25 seconds of action required below!
>
> Hi @LSSTScienceCollaborations/observing-strategy-white-paper-editors
> <https://github.com/orgs/LSSTScienceCollaborations/teams/observing-strategy-white-paper-editors>
> @LSSTScienceCollaborations/maf-workshop-organisers
> <https://github.com/orgs/LSSTScienceCollaborations/teams/maf-workshop-organisers>
>
> For many of us this is the last week of the quarter before the winter
> break, something I am sure you are all looking forward to! Thank you for
> all your efforts on the observing strategy white paper this year: it's been
> impressive to see it forming out of all your LSST hopes, dreams, fears and
> worries :-)
>
> We said in #222
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/222>
> that we would aim to go through the white paper at the AAS meeting, and
> decide whether or not to submit it for LSST review at that time. I suggest
> we meet on the Monday (January 4th) for this activity. The deadline for
> "splinter meetings"
> <http://aas.org/meetings/winter-meeting-session-proposal-information-and-deadlines#Splinter_Meetings>
> is tomorrow, and booking one would cost a few hundred bucks (even with
> minimal support requested).
>
> Action: Please edit the list below *today* if you will be able to make it
> to an editorial meeting on that Monday, and we can decide whether or not to
> put in a splinter meeting request tomorrow. I can imagine meeting in a
> hotel room or cafe instead, if very few of us will be in Florida then.
>
>    - Phil Marshall (in person)
>    - Your Name (in person / remote)
>
> Comments welcome!
>
> Phil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/235>
> .
>



-- 
Beth Willman
LSST Deputy Director
Associate Astronomer, Steward Observatory
933 North Cherry Avenue
Tucson, Arizona 85721
520-318-8473

**Comment by drphilmarshall** [comment]
Alright everyone, thanks for your replies! Looks like it'll just be a
handful of us in Florida in person, so I don't think we'll need a special
meeting room. The reception is Monday evening and starts at 7pm, so I think
the window of opportunity for those of us who are in town is afternoon
teatime, 4pm. @ivezic, @bethwillman, @egawiser: I will identify a suitable
venue where we can meet, (possibly) drink tea and review the white paper.

Remote attendees: rather than try and hold a large meeting with many remote
attendees, I have a suggestion: how about I get set up somewhere with
wireless at around 12 noon EST, and spend a few hours meeting with you and
discussing your chapters, surgery-style? I can then report to Zeljko and
Beth at 4pm and we can see how things look. Let me know!

Zeljko: if we do this I might need to use your hotel room, I can only check
in to mine at 3pm!

**Comment by rbiswas4** [comment]
I can do a remote meeting at anytime that day, but will not be going to the AAS.

**Comment by jhrlsst** [comment]
I will arrive after 5pm on Monday. I can meet other day during the AAS meeting. Or before or after the AAS meeting (you may busy to talk to many other members), I can visit Stanford to meet since I am local.

**Comment by lmwalkowicz** [comment]
I'm on the ExoPAG exec council and our meeting is all day Monday, so I'm out for this unfortunately.

**Comment by tanguita** [comment]
Timo Anguita (remote) Apparently replying to the email didn't work!

**Comment by jhrlsst** [comment]
Does the LSST project need anything from us for the LSST townhall meeting?
Perhaps 1 or 2 page power point slides for each chapter?

**Comment by bethwillman** [comment]
Thank you for asking this!

I will briefly mention the community-based study of the Observing Strategy
in a single slide that I'll make (so no further contributions are needed
from y'all).  I'll be leading a ~15 minute presentation on broad LSST
Project updates and ways for the community to be involved, Lucianne will
lead ~10 minutes presentation on science collaborations and how to get
involved, Pat Eliason and Pat Osmer will lead ~10 minutes presentation on
enabling science by the LSST Corporation.

cheers
Beth

On Wed, Dec 16, 2015 at 2:28 PM, Jeonghee Rho <notifications@github.com>
wrote:

> Does the LSST project need anything from us for the LSST townhall meeting?
> Perhaps 1 or 2 page power point slides for each chapter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/235#issuecomment-165230121>
> .
>



-- 
Beth Willman
LSST Deputy Director
Associate Astronomer, Steward Observatory
933 North Cherry Avenue
Tucson, Arizona 85721
520-318-8473

**Comment by ebellm** [comment]
Sorry, wasn't on the distribution list--I will be at AAS on Monday in person but in a workshop until 4.

**Comment by ohadshemmer** [comment]
Will be traveling to MCO on Mon. 1/4, arriving around 4.

**Comment by drphilmarshall** [comment]
Hi all,

Hope you are having good winter holidays! I've been taking the 360 degree
virtual tour of the AAS resort, and @bethwillman @ivezic @egawiser
@nielbrandt it looks like [The Cocoa Bean](
http://www.marriott.com/hotelwebsites/us/m/mcogp/mcogp_pdf/Resort_Map_Final_Online_2015.pdf)
might be a good place for the few of us to meet in person at 4pm on Monday.

Others, I'll try and be online from 12 noon EST if any of you want to chat
about your chapters before I see teh others later in the afternoon. I'll
post a hangout URL when I am installed.

Safe travels, and Happy New Year!

Phil

**Comment by lundmb** [comment]
@drphilmarshall I'll be able to attend on Monday at 4 pm as well (sorry, missed the initial call for responses because I was traveling then)

**Comment by drphilmarshall** [comment]
Hi all,

I am now at the Gaylord Palms resort for the AAS meeting. This place is crazy - I seem to be sitting on the ramparts of a recreation of a ruined medieval castle.

@ivezic @bethwillman @egawiser @yoachim It turns out that the Cocoa Bean has only 3 tables, and is more of a coffee serving hatch than a tea shop. However, the [Sandbar](http://www.marriott.com/hotelwebsites/us/m/mcogp/mcogp_pdf/Resort_Map_Final_Online_2015.pdf) will be open at 4pm and we should be able to get a table no problem (it's outside :-) ). Follow signs to "Resort Pools" and take the Emerald A elevator down one level, and it's in the middle of the pool. (There's a bridge.)

Others: I will be in Zeljko's room from 12 noon in this [LSST hangout](http://ls.st/zhd) if you'd like to drop in and chat about your chapter. I'm going to try and look through each one, and issue the tweaks that need to be made before completing a presentable draft. (My guess is that mainly this will involve commenting out unwritten subsections about metrics, and replacing with promissary notes.)

See you later, one way or another!

Phil

**Comment by bethwillman** [comment]
Got it. Will see you at the Sandbar in a bit.

Beth

**Comment by lmwalkowicz** [comment]
Just FYI: should you need another ridiculous meeting location sometime this
week, the MOOR restaurant/bar is partially composed of a boat floating in
an indoor fishpond.

**Comment by willclarkson** [comment]
Thanks Phil - if you are around at 12:30 I will look for you in the hangout
then.

Best

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR330 or PHYS 150 lab or discussion).

**Comment by rbiswas4** [comment]
@drphilmarshall :

I think the internet connection on a plane I have right now is to slow for
using chat. So, I think I will be very brief in an email:
On the SN chapter: I think we are making good progress on
- calculating a few metrics based on heuristics only, and the main idea
here is  using a sliding window in time, and weights to tag 'distinct'
observations. I have working code for a few examples in a notebook.
- also made some progress following up on an idea Zeljko wanted to explore
about fitting SN light curves with the survey mean number of observations
/depths.
- What this seems to be heading towards (but not quite solid yet) is that
the OpSim results are such that mean conditions are rarely produced (due to
observations not being distinct enough etc.). This has been kind of
expected, but I think we can pin down a few more details.

If you are taking a vote on whether to submit to the arXiv or not: I do not
feel that the chapter is ready enough for an arXiv submission. I expect
parts of it to change, and a few things to be added very soon (this week).
Of course, if you decide that submission is still berter, these changes
will be propagated to the github page :) ,

Thanks,
Rahul
