### ISSUE TITLE
In progress: variability depth metric.

### ISSUE THREAD

**Issue by keatonb** [LSSTScienceCollaborations/ObservingStrategy#247]
I just want to let y'all know (esp. @drphilmarshall, @lmwalkowicz, @AshishMahabal) that I'm putting the finishing touches on a new metric that should be ready to distribute in the next few days.  This metric calculates a "variability depth": the magnitude limit where variable sources with, say, > 1% photometric variability will be overwhelmingly recovered (say, with something like a 5% false alarm probability).  This will characterize how well LSST reveals the low-amplitude variable sky.  Sorry not to have that together by the meeting tomorrow, but it turned out to be a bit more difficult of a problem than I expected.  Please anticipate that contribution as you discuss the Variables chapter.  I'm afraid that I will not be able to join your meeting remotely.

**Comment by drphilmarshall** [comment]
Excellent, thanks Keaton! Don't worry about missing the meeting: it'd
really just a few of us catching up with tea. Watch out for an issue with
the result of the conversation tomorrow evening though. Thanks for all your
work on the variability metric! Sounds good :-)

**Comment by rbiswas4** [comment]
@philmarshal
Is there going to be a meeting with remote participants? I am going to be on travel but if plane timings work out I will try to call in. It would be good to know the phone number/ address ahead of time though

Thanks,
Rahul

**Comment by drphilmarshall** [comment]
The 4pm EST meeting will not have remote access. If you want to chat with
me about the paper, I'll be online between 12 noon as 3pm EST. Safe
travels, Rahul!

**Comment by lmwalkowicz** [comment]
This is great to hear Keaton, thanks very much! Happy meeting/tea drinking
all, I am in the ExoPAG meeting today so will unfortunately miss you.

**Comment by keatonb** [comment]
To update: this metric exists now in sims_maf_contrib.  I will work on adding some description to the white paper by the final draft deadline.

**Comment by keatonb** [comment]
I sent a pull request with the new contents that describe this analysis.  This issue can be closed when that request goes through.

**Comment by drphilmarshall** [comment]
Hooray @keatonb ! Closing thanks to #346 :-)
