### ISSUE TITLE
Galaxy chapter AAS presentability

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#249]
Hi @willclarkson 

Good talking to you just now - here are my notes based on our conversation. I'll talk to @ivezic and @bethwillman about deadlines for content injection and report back.

* [x] Decision on section 4.5 and 4.6: comment out for now?

* [ ] References in preamble

* [x] Halo mapping: tidy up preamble, "XXX", "Colin please step in..." etc
* [x] Halo mapping measurements: XX, Y etc - numbers needed. Target measurement: distance? Are the figures of merit distance precisions?
* [ ] Star/galaxy separation is a diagnostic metric - need to make this clear. How are figures of merit likely to depend on this? If unknown, explain that this is research.
* [x] Which OpSim runs are of interest? What questions do you want o answer? What do you anticipate finding? What would the consequence be if you did find that?

* [x] Disk science cases: 5 in one section, each with a figure of merit, that depends on some lower level diagnostic metrics - reword to use this terminology. Explain your plan of a table of figures of merit, and the need to do comparisons within the disk study community.
* [ ] Disk: some target measurements are not measurements, eg "Probing planets outside the snow line". What do you want to measure? Their abundance? 
* [x] Disk: numbered metrics are figures of merit. Dependencies are diagnostic metrics. Both are calculable using MAF framework (FoMs will be complex metrics.)

* [x] Astrometry section also has multiple science cases - explain decision to keep them together?
* [x] Figues of merit are not defined, but diagnostics are very well defined and in fact already implemented. What is the link between them?

**Comment by willclarkson** [comment]
Thanks Phil - can you clarify point 2 about references in the preamble please? Are you asking for ADS links as in Section 1.1, or for something else?

**Comment by drphilmarshall** [comment]
I think they need to be `\citep{}` commands to papers in the
`references.bib` file. Hopefully the hyperlinks will all still work
(although thats a separate issue).

**Comment by willclarkson** [comment]
Hi Phil - I had time to address some of the presentability issues you raised. I have clicked the checkboxes on your issue, please advise if I need to do anything else to enter the check (so to speak). Cheers -- Will

**Comment by drphilmarshall** [comment]
Looks good, thanks Will - thanks for taking a stab at the Figure of Merit / diagnostic distinction. When I have tidied up the introduction, I'll take a pass through the Galaxy chapter to ensure consistency.

**Comment by akvivas** [comment]
Comments added. Closing.

**Comment by drphilmarshall** [comment]
Good - thank you, Kathy!
