### ISSUE TITLE
Discussion of TDC2

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#250]
@tanguita @drphilmarshall

Lets extend the SL time delays section to include our plans for TDC2, and then extend the AGN microlensing section to refer to this.

**Comment by drphilmarshall** [comment]
In particular, we said that:

* [ ] The metrics section needs a figure of merit (accuracy in scaling relation slope?), and then discussion of what we expect that FoM to depend on, eg night to night cadence, season length, campaign length, as in the time delays. The enigma1189 cadence and season length figure can go here, for illustration. I think its *here* that we should admit that we don't yet know the dependence of the FoM to the diagnostic metrics, but that we will find out by doing TDC2. A brief layout of the TDC2 microlensing analysis program would go really well here. 

* [ ] In the OpSim analysis subsection, we could say which OpSim outputs are likely to be most interesting for microlensing - or if there are particular approaches to rolling cadence that could be interesting. Splitting visit pairs? Separating the u and g band visits more?

* [ ] There's not much to discuss yet, but it could be good to write down what we think the biggest risks are. I guess we need good sampling over the widest wavelength range possible, and so poor sampling in u and g could be a problem - especially as that is where the variability is strongest. We can't write much here, but its a place to reiterate our concerns, before doing the investigation.

**Comment by drphilmarshall** [comment]
Then, in the lens time delays section of the cosmology chapter, I need to write the discussion that explains TDC2.

**Comment by tanguita** [comment]
I updated the text to cover at least the first two points... don't know whether you want to close this one.

**Comment by drphilmarshall** [comment]
Thanks Timo! I still have the time delays section to edit, so I'll close this when I've done that.
