### ISSUE TITLE
Solar System chapter presentability

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#254]
Hi @rhiannonlynne, hi @davidtrilling 

Just looking through the solar system chapter, and making a few notes (see below). Lynne says she is planning on working more on this later today, please feel free to edit/extend the list of things to fix below! 

* [x] I think that completeness is a Figure of Merit for the discovery/linking section, would you agree? Is there a scalar you could define for each object type, that would then allow you to make statements of the form "the improvement going from run A to run B was X%"?
* [ ] If you have not yet had a chance to compute completenesses for different  opsim outputs (in the opsim analysis subsection), you could highlight a few runs that you want to investigate (because of their properties) in lieu of any results.
* [ ] Sounds like you have identified some risks, that could be reiterated in the discussion section: removing visit pairs in "extragalactic sky" (ie away from the ecliptic) may have a drastic effect on the NEO count, and so on. You could also suggest other tweaks to the observing strategy here, if you think you already know enough to do so?

* [ ] Sections 3.3 (Orbital Accuracy) and 3.4 (Activity) have zero content - comment them out for now?

* [ ] Section 3.5 (Light curves, rotation periods) has no Figure of Merit defined, but seems to be about inferring shape models over realistic distrbutions. If you have plans to do these simulations you could sketch them out. It's nice that you already have a diagnostic metric (number of observations) that you think this FoM will depend on, but there must be more besides (cadence? season length? campaign length?).

* [ ] Could the light curves and color measurements be combined into a single section? Sounds like your inferences of intrinsic color and rotation period are always correlated, so *could* be represented by a single FoM, but I can see how you might prefer to keep them separate. Still, some sections in other chapters have more than one FoM per section, when it makes sense to keep them together (eg in a single table). Much of the Galaxy Chapter is structured like this - probing th edisk in 5 different ways seems conceptually similar to probing asteroid structure in 2 different ways (bright ness variability, and color). What do you think?

* [ ] Will your proposed special surveys go in a section alongside the DDF text? Or separately? Either way they will look good at the end of your chapter!

**Comment by migueldvb** [comment]
Regarding the fourth point, there is some content for the activity section (3.4) in #242.

**Comment by drphilmarshall** [comment]
Splendid! I'll leave the review and merge to @rhiannonlynne :-)

**Comment by rhiannonlynne** [comment]
Phil - we haven't calculated  completeness for the new runs yet at all. 
I could do that, but it will take a few days (note that this is probably true for all of the other metrics too). Is this consistent with the timeline?

**Comment by drphilmarshall** [comment]
Yes - as you will see in my next email to the group! Hope all's well in
Seattle, and the New Year has started well.

**Comment by drphilmarshall** [comment]
Hey @rhiannonlynne and @davidtrilling  - I am going to close this one out, following PR #366 :-)
