### ISSUE TITLE
New AGN text from Vishal needs editing in

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#265]
Hi @ohadshemmer - I got tired of seeing @AstroVPK 's unmerged PR (#204) hanging around, so I merged it. His new text appears bright blue in the PDF, and needs editing in by you, I think. Great if you can take a look at `AGN/AGN_Disk_Intrinsic.tex` and fix the text so it reads how you want it. Thanks for your efforts, Vishal! :-)

**Comment by ohadshemmer** [comment]
Just deleted that text by @AstroVPK - this is old text that I've edited in back in Tucson on 11/20/15.

**Comment by AstroVPK** [comment]
Is this issue closed then? How can I help close it otherwise?

**Comment by tanguita** [comment]
Hi  @AstroVPK, is it closed? does the text look ok? if so, we could just close this issue.

**Comment by AstroVPK** [comment]
Looks fien. Let's close the issue!
