### ISSUE TITLE
OpSim run name macros

### ISSUE THREAD

**Issue by rbiswas4** [LSSTScienceCollaborations/ObservingStrategy#266]
@ivezic, 
Kraken_1032 on Pg 18 is probably really Kraken_1033  (The confluence page: https://confluence.lsstcorp.org/display/SIM/OpSim+Datasets+for+Cadence+Workshop+LSST2015
and the run pages have Kraken_1033, and no Kraken_1032).

@drphilmarshall 
Also, while we are at it ... can we advertise variable names `\opsimdbref{db:enigma}` that are stylized, so that the fonts and links are consistent throughout the white-paper.

**Comment by drphilmarshall** [comment]
@LSSTScienceCollaborations/observing-strategy-white-paper-contributors @LSSTScienceCollaborations/observing-strategy-white-paper-editors 

As you write about metric results based on various `OpSim` output databases, please do refer to the definitions made by @ivezic in `cadexp2.tex`. I notice that the new baseline cadence is now `minion_1016`. Chapter 2 is now finished, I believe - which makes it an excellent reference for you! Here, for your convenience, is the complete list (and how to generate it):

```
grep 'opsimdb\[' cadexp2.tex
```
```latex
\opsimdb[db:baseCadence]{minion\_1016}{The New Baseline Cadence.}
\opsimdb[db:opstwo]{minion\_1012}{Only Universal Cadence, with pairs of visits.}
\opsimdb[db:opstwoPS]{minion\_1020}{A Pan-STARRS-like observing strategy.}
\opsimdb[db:UConlyNoVisitPairs]{minion\_1013}{Only Universal Cadence, no visit pairs.}
\opsimdb[db:NoVisitPairs]{kraken\_1043}{Baseline Cadence, but with no visit pairs.}
\opsimdb[db:ShortExptime]{kraken\_1052}{Baseline Cadence, but with 33\% shorter exposure time.}
\opsimdb[db:LongExptime]{kraken\_1053}{Baseline Cadence, but 100\% longer exposure time.}
\opsimdb[db:DoubleUbandExptime]{kraken\_1045}{Baseline Cadence, but with doubled $u$-band exposure time.}
\opsimdb[db:DoubleUbandExptimewithNESpur]{kraken\_1059}{Baseline Cadence, but with doubled $u$-band exp.\ time and Baseline NE Spur.}
\opsimdb[db:UConlyRelaxedAirmass]{minion\_1022}{Only Universal Cadence, with relaxed airmass limit.}
\opsimdb[db:UConlyStringentAirmass]{minion\_1017}{Only Universal Cadence, with stringent airmass limit.}
\opsimdb[db:NEOsNoVisitPairs]{kraken\_1043}{NEO test: no request for pairs of visits.}
\opsimdb[db:NEOswithVisitPairs]{enigma\_1016}{NEO test: pairs of visits (i.e.\ the Baseline Cadence).}.
\opsimdb[db:NEOswithVisitTriplets]{enigma\_1281}{NEO test: triplets of visits.}
\opsimdb[db:NEOwithVisitQuads]{enigma\_1282}{NEO test: quads of visits.}
```
