### ISSUE TITLE
WFIRST + LSST supernovae: science project definition, figure of merit

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#272]
Hi @rubind !

I made you a `WFIRST_supernovae.tex` file for you to define your fiducial WFIRST+LSST supernova cosmology project, and its figure of merit! You're welcome :-) Great if you can have a go at writing down your plan, and issuing yourself with any other tasks that need doing in order to get some metrics designed by the end of Feb. Hope all's well!

Phil

**Comment by drphilmarshall** [comment]
Hi @rubind @jasondrhodes 

As you might have seen, I commented out this section for now when going through my "Version 1 Final Draft" audit ( #367 ), because the pushed version doesn't  have any content yet. It's definitely not too late to contribute something! But it would be great if you could check in what you have ASAP, so that we have time to have someone else from the community review it in early May. The idea is to get you good feedback, so that you are ready for submission to the LSST pub board at the end of the month. 

Also of relevance: the chapter editors have been trying to figure out where to draw the line between results sections, that stand on their own complete with quantitative results, and ideas subsections, that make up "Future Work" section at the end of each chapter. The consensus threshold is that the quantification should make use of numbers from `OpSim` in some way. Those numbers can be very rough (total number of visits, rough magnitude limits, and so on) - we just want to at least start making the link to actual `OpSim` and MAF diagnostic metric outputs.  This is something you should keep in mind when working on your supernova section! 

Hope all's well,

Phil

**Comment by jasondrhodes** [comment]
Phil-  Have you gotten what you need yet?  I just got back from a few days off and want to make sure you have what you need.

Jason

**Comment by drphilmarshall** [comment]
Hi @jasondrhodes - @rubind submitted a nice pull request at #397 , which we are now discussing. There's some dots to join with the cosmology chapter, but otherwise it looks a straightforward addition.

**Comment by drphilmarshall** [comment]
In #397, I wrote the following:

>  @rubind Reading [your section], I notice some slight misunderstanding about the section heading "Target Measurements" . Your "target" is I believe the dark energy parameters, and from this flows the figure of merit defined by the DETF (or similar), and the diagnostic metrics that you need in order to be able to compute that FoM (ie summaries of the light curve sampling, and so on).

> It seems as though for now your quantitative results are coming from an independent analysis, which is fine. However, for the future have you interacted any further with @MichelleLochner @jhrlsst and @rbiswas4 on enhancing the metric analysis they have been working on, to include the value added by WFIRST? The key point is that the DDF time sampling (and the time window of the observations) is not yet set in stone, and so needs motivating by the SN metric analysis - including the WFIRST extension. You could imagine that other science cases might need all the DDF observations to be done in year 1, for example, or at very rapid cadence over a very short season, or spread out over the whole year at low cadence, etc etc. Another possibility could be that only 1 DDF is optimized for SNe... All these strategies could be simulated, and all will need evaluating using SN metric code.

> For version 1 of the white paper, I think it's enough to describe how the WFIRST SN science case relates to and/or builds upon the LSST-only SN science case, in the cosmology chapter - and then give your early indication of the improvement of the FoM in the best-case scenario. What do you think? You're mostly there bar the cross refs to the cosmology chapter, and reorganizing your current text. Thanks!

I'm just reproducing this feedback here so that you can address it before we close this issue. I needed to merge the PR so that @jasondrhodes could get up to speed easily.

**Comment by drphilmarshall** [comment]
Thanks again, @rubind  - closing this out while I go find you a reviewer. I may do some editing myself, like I'm doing for @jasondrhodes :-)
