### ISSUE TITLE
Work to be done on supernova section

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#287]
The supernova section is in good shape. While there's still masses of things people _can_ do to improve this section of the white paper, below is a list of things that we could use help on right now:

1) We need code testers to check Rahul's code so let us know if you want to play with OpSim output and generate supernova light curves.

2) We have a detection metric, classification metric and characterisation metric but not a final cosmology metric. There are many possibilities over and above the DETF FoM, someone needs to at least write a paragraph on this and the merits of various metrics, and maybe a first iteration of code (Rahul? David?).  

3) Starting to look at alternative models to SALT2 so that our metric is not so dependent on it (David Rubin?). 

4) Any other additions people want to propose (if you can finish it in under a month...)

**Comment by drphilmarshall** [comment]
Hi @MichelleLochner ! 

Here are your [open "Supernova Cosmology" issues](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues?q=is%3Aopen+milestone%3A%22Version+1+Final+Draft%22+label%3A%22Supernova+Cosmology%22) - can you see a route to a internally-reviewable section by the end of today? Some condensing of text, choosing of figures *might* be in order as you go, potentially. I have internal reviewers in mind for you when you are done! :-)

**Comment by MichelleLochner** [comment]
Hi @drphilmarshall! @rbiswas4 and I were just figuring this out. I would say no, there's no way it can be done today (we're at a supernova workshop until the end of Friday). I agree about condensing. :-) I would say more realistically we can get this done by the early to mid next week. Sorry for dropping the ball! I will ping you once we're done with this.

**Comment by drphilmarshall** [comment]
OK, sounds good! My advice is: be aggressive in getting the section into shape. The sections in the white paper will be in a range of states of completeness, almost by definition. You just need to get your section to the point where you would like one of us to read it and give feedback, so that in turn you can produce something that could in principle be posted to the arxiv very soon after May 27th. Thanks!

**Comment by MichelleLochner** [comment]
Supernova section is now ready for internal review!

**Comment by drphilmarshall** [comment]
Hurrah! Well done, all :-)
