### ISSUE TITLE
Run classification pipeline on LSST simulations

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#289]
I need to run the classification pipeline on the LSST simulated light curves from enigma_1189 and compute the AUC metric. Also need to see how this changes as a function of redshift.

**Comment by egawiser** [comment]
I wonder if at this point this should be updated to the now-standard minion runs?  Postponing the milestone to May 5 internal review, pending @MichelleLochner 's decision on whether to close this issue.

**Comment by MichelleLochner** [comment]
I think this will be too much for this iteration of the white paper. I'll close this for now and we'll work on this in parallel.

**Comment by drphilmarshall** [comment]
Another option to turn this issue into an "Epic", and use it to organize
the large amount of work involved with analyzing the sims. Agree that you
should at least move it to a later milestone: feel free to create your own!
