### ISSUE TITLE
Should we publish the whitepaper in a journal?

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#29]
I've asked @drphilmarshall if the white paper is to be published and he said it's most likely to be just an ArXiv document, but hasn't been discussed yet so he suggested I open an issue on it. Speaking as a junior person, I would prefer to see the paper published in a peer-reviewed journal rather than just on the ArXiv. How do other people feel?

**Comment by StephenRidgway** [comment]
Hi Michelle,

I certainly understand the value of turning work into a published paper.  On the other hand, I see great difficulties in getting a many-author, inevitably heterogeneous collection of science cases turned into a uniform, and sufficiently compact, paper for regular publication.  Several of us have adjusted to this by carving out a niche and developing it sufficiently to publish a topic as a single or few authors.  Most of these publications have gone to non-refereed venues.  In years past I’ve heard it said that some journals are biased against “science case” type articles, but it might be worth pinging a few editors to check.  Whatever the reply, the use of metrics is a really good stepping stone for turning a hand-waving science case into a plan, and working with simulated data is even better.  I’d be interested to hear of others' experiences with publishing LSST science studies or leveraging it to develop publications.

Steve

**Comment by michaelstrauss** [comment]
This is something to discuss at the next phonecon (which I will miss).  As you know, we "published" the LSST Science Book by posting to ArXiv (and also distributing a limited number of hardcopies).  It now has 378 citations; not too shabby.  On the other hand, it has 245 authors, and it is not clear whether any individual author of a given section gets the recognition he or she deserves.  Again, this is worth talking through on the phone.  

						-Michael

**Comment by MichelleLochner** [comment]
Just to add to this, we discussed this at the Bremerton workshop and several people agreed we should try to publish if we can, as many funding agencies completely discount anything not in a peer-reviewed journal. One of my colleagues said that CMB white papers are generally published in AIP Conference Proceedings, so perhaps we could consider this as a potential publishing journal.

**Comment by egawiser** [comment]
There is also a relevant journal run by SPIE (this was mentioned in Bremerton) that seems like the most logical target journal.

**Comment by drphilmarshall** [comment]
Quick question: I don't think we need to decide on a journal/proceedings to submit to before posting the white paper to the arxiv after the Tucson meeting, do we?

**Comment by egawiser** [comment]
Well, it would be nice to not have to change the article format (significantly) from the ArXiv version in order to submit it, hence helpful to choose the journal before posting.  I think we can finalize that aspect next week, hopefully.

**Comment by drphilmarshall** [comment]
I will discuss the journal destination of the white paper with @bethwillman and @ivezic on Friday, when we meet up to take stock. Watch this space!

**Comment by egawiser** [comment]
Sounds good.  We should consider SPIE's [Journal of Astronomical Telescopes and Systems] (http://spie.org/publications/journals/journal-of-astronomical-telescopes-instruments-and-systems-)

**Comment by darkojev** [comment]
We already had faced problem with SPIE publications - most of people do 
not have an access to the published articles (being in astronomy 
departments, and Universities are stingy in their subscriptions...) and 
that means that citation get scarcer (it is hard to expect that people 
cite an article they could not access).

Cheers

Darko

**Comment by egawiser** [comment]
As I understand it, this White Paper will be a living document on ArXiv, and the current discussion is about which refereed journal to publish a snapshot of it in.  I expect people to access the ArXiv version, which can have a Journal Ref noting where it ended up published to generate proper citations.

**Comment by StephenRidgway** [comment]
Hi,

The SPIE journal recommended is conditionally open access - if you pay the fee, the article is open to anybody. However, as Darko says, most people assume that SPIE is equivalent inaccessible, and maybe they will not even try.

If you don’t pay the fee, it is not open access, and SPIE policy forbids putting it on any public site.  

Steve

**Comment by drphilmarshall** [comment]
Does anyone have the link to the whitelist of journals that are somehow
acceptable to people tracking citations etc?

The size of our white paper is as much of an issue as its dynamic state, I
think: we're calling it a white paper but it's similar in volume to a big
review, or (dare I say it) a "science book."

**Comment by drphilmarshall** [comment]
Hi all: I just talked to @bethwillman and @ivezic about where to publish the white paper. I think we are all in agreement that yes, this work *should* be published beyond arxiv posting, both for accounting purposes but also because peer review is important. We have a few options including SPIE (thanks Eric!) and PASP, and so can move on to investigating whether the living document model is one that they can support. At this point I think we might want to pause and regroup, given our looming final draft deadline: I'm going to close this out, and invite the editors in for coffee to discuss that :-)
