### ISSUE TITLE
Write a paragraph on cosmology metric with SNe

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#290]
While we have some great intermediate metrics, we still haven't looked at a final figure of merit for supernova cosmology. We need someone to just write a piece on what we might plan to do in the future, since there may be more interesting options than the standard DETF FoM.

**Comment by egawiser** [comment]
Sounds urgent, but @drphilmarshall told us on today's telecon that we should either complete things or postpone the milestone, so given that you're at a conference, I'm doing the latter.

**Comment by drphilmarshall** [comment]
Good. This might be something your reviewer comes back to you and asks for,
so you could think of adding it "during review".

**Comment by MichelleLochner** [comment]
Ok, I'm closing this for now. We'll see what the review says.

**Comment by drphilmarshall** [comment]
Brava! :-)
