### ISSUE TITLE
Change in MAF dither stacker names

### ISSUE THREAD

**Issue by rhiannonlynne** [LSSTScienceCollaborations/ObservingStrategy#292]
My apologies if you receive this notice more than once - we still need to work out the kinks in our communications regarding MAF (or opsim) upcoming changes that would affect users.

This notice is regarding the names of the dithering stackers. In MAF, these are generally currently called 

RandomDitherFieldVisitStacker', 'RandomDitherFieldNightStacker', 'RandomDitherNightStacker', 'SpiralDitherFieldVisitStacker', 'SpiralDitherFieldNightStacker', 'SpiralDitherNightStacker', 'HexDitherFieldVisitStacker', 'HexDitherFieldNightStacker', 'HexDitherNightStacker'

It's been pointed out that this format: 
[geometry]Dither[Field][Timescale]Stacker, 
where [geometry] refers to the geometric pattern used in the dithering pattern, 'Dither' identifies the stacker as a dithering stacker, and "Stacker" identifies the class within MAF as a stacker, and then the [Timescale] indicates how often the dithering offset is changed, while if [Field] is present, it indicates that a new dither offset is calculated and applied for each field, on the timescale indicated and its absence indicates that all visits within the indicated timescale have the same dither offset.

should instead be
[geometry]Dither[Field]['Per'Timescale]Stacker 
for clarity - the addition of the Per would hopefully make it more clear that the timescale is indicating how often the dithering offset is changed.

Thus, we are proposing to change all of the MAF dithering stackers to add "Per" into the stacker name.  
I wanted to be sure to spell this out here before making this change, in case it added significant complications to preparing the white paper. 

Lynne

**Comment by drphilmarshall** [comment]
Thanks @rhiannonlynne ! Would you mind please posting a link here to the relevant repo once you have made this very sensible change, so that we can see the new files in place and remember to check and edit all our MAF code? Thanks!

**Comment by rhiannonlynne** [comment]
Important Note! I'm fixing a problem with sims_maf_contrib (hopefully will be resolved tonight). 
Please refrain from pulling from sims_maf_contrib at the moment, to avoid having some pretty weird git problems.

**Comment by rhiannonlynne** [comment]
The sims_maf_contrib problem is fixed. 
The dither stackers changes are available on a branch of sims_maf, and should be merged back to master shortly. It will not be available in conda or eups distrib until we make a new release, but if you are running from the github repo version of sims_maf, it will be useable immediately.

**Comment by rhiannonlynne** [comment]
The names are changed on master of sims_maf, although they are not yet in the conda or eups distrib releases. (there will be an announcement about that on sims-announcements when that happens).
