### ISSUE TITLE
"Available Metrics" appendix?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#295]
Hi @yoachim 

At AAS, in #264 , we wrote that "Peter [will] collect list of all available metrics in an appendix, to show contributors what is available. Ideally this will be hyperlinked to the functions themselves; other hyperlinks to documentation should also be included in the appendix."  @ivezic reminded me the other day that [the MAF code already has a reference paper, in SPIE](https://confluence.lsstcorp.org/display/SIM/MAF+documentation?preview=/4751463/11010055/spie_proc.pdf), so I'm wondering how much we need to document in the white paper, and how much can simply be referred to. I guess the `sims_maf_contrib` metrics are not written up yet - maybe it's just these and any new ones you have put together since the SPIE paper that need putting in, somehow? Interested to hear your thoughts on what belongs with the white paper - perhaps it's something to briefly discuss when we meet this week ( #293  )?

**Comment by lundmb** [comment]
To chime in on this, I'd point out that the paper seems to be more about
the general framework of MAF. I think there's something valuable in having
a list of what all the available metrics are, and that paper doesn't do
that. All the inbuilt metrics can be accessed once someone downloads MAF,
but that requires the download, and doesn't include the third-party metrics
that have been contributed, and I believe is only limited to around
one-sentence explanations.

It seems to me like it would be very beneficial to include a list of all
the metrics so that people can quickly see if there's already a metric that
they can apply for their purposes or not.

**Comment by rhiannonlynne** [comment]
We actually have something else in the works that should address this
problem, at least for the core metrics (how to document the contrib metrics
is a little tougher).
We have sphinx documentation in the works.. I'll see if we can get it
online somewhere in the next few days. Maybe @jsick can help.

**Comment by drphilmarshall** [comment]
Cool :-) I would hope that all the `sims_maf_contrib` metrics that we use
could be hyper-linked from the white paper (and auto-tabulated in one
place, too). A simple companion table pointing at the online MAF sphinx
docs might then be good enough for @lundmb et al. We should try something
simple and see.

**Comment by rhiannonlynne** [comment]
We've got a preliminary version up and running here: 
https://sims-maf.lsst.io/ 

This will be where this documentation lives going forward, at least for an indefinite while (this is part of the new "LSST the docs" setup). 
We'll of course add more MAF documentation as it's available, and hopefully make it a bit more presentable by Friday, but this does give you the available metrics list, including links to the metrics API documentation (for core maf stuff) and the github page (for sims_maf_contrib metrics).

**Comment by rhiannonlynne** [comment]
Are all the metrics people using pushed to sims_maf_contrib?

**Comment by keatonb** [comment]
I'm still wrapping one up that I will push in the next ~day.

**Comment by drphilmarshall** [comment]
Love it, Lynne! Check out our list of contributed metrics:
https://sims-maf.lsst.io/metricList.html#contributed-mafcontrib-metrics
 Very cool seeing everyone's work up there in readthedocs :-) Thank you!

**Comment by drphilmarshall** [comment]
I will add a reference to the readthedocs at a suitable location in the white paper.
