### ISSUE TITLE
Protect the master branch

### ISSUE THREAD

**Issue by yoachim** [LSSTScienceCollaborations/ObservingStrategy#296]
Given past and recent experiences here and elsewhere, I suggest @drphilmarshall configure the master branch to prevent force-push updates. Just seems prudent.

**Comment by drphilmarshall** [comment]
Thanks @yoachim I should have done this a long time ago. Here are the settings I chose, do they look good to you? We still want to enable the Editors to push directly to base/master (for speed), just prevent them from force pushing commits the rewrite history, right?

![image](https://cloud.githubusercontent.com/assets/710903/14496622/8e35cd10-0148-11e6-8baf-8524967c655d.png)

**Comment by yoachim** [comment]
Looks good to me!
