### ISSUE TITLE
Define SDSS

### ISSUE THREAD

**Issue by AstroVPK** [LSSTScienceCollaborations/ObservingStrategy#301]
SDSS needs to be defined and referenced in section 4.2. Do we have a list of acronyms that we can use (and add to when we define & reference new acronyms).

**Comment by drphilmarshall** [comment]
Good idea. I'd say let's just add macros to the [style file]() to keep it simple. Great if you can trace all instances of SDSS, and make sure the first one spells it out in full - and that the others use the macro. Thanks!

**Comment by akvivas** [comment]
SDSS spelled out in section 4.2 .Closing.

**Comment by drphilmarshall** [comment]
Hey, thanks Kathy! :-) :-)
