### ISSUE TITLE
sn.tex -- Missing file figs/transients/LSST_Kasen_lcv0.pdf  ?

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#340]
Hi sn.tex editors (I think @fedhere ?) - Can you check to make sure that file figs/transients/LSST_Kasen_lcv0.pdf gets added to the repository please? I am getting a "file not found" error in the build when latex tries to find that file:

LaTeX Warning: File `figs/transients/LSST_Kasen_lcv0.pdf' not found on input line 174.

Thanks!

Will

**Comment by fedhere** [comment]
done
