### ISSUE TITLE
Dithering section needs sketching out

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#35]
Hi @egawiser,

Can you sketch out the dithering section, please? It'll need its own file, and then to be `\included` from `cosmology.tex` - but then it shoudl be plain sailing given the instructions in the file. You can check out `lenstimedelays.tex` for an example too. Feel free to pass this issue on to Peter K when you are ready. 

Also, heads up: there will be a plenary session at the Bremerton workshop next week where we all tell the other section leads very briefly what's going in our sections - we'll be looking for a strong performance from you two, with no dithering. 

Thanks!

Phil

**Comment by egawiser** [comment]
Done.
