### ISSUE TITLE
Galactic plane as a "Tension"

### ISSUE THREAD

**Issue by akvivas** [LSSTScienceCollaborations/ObservingStrategy#351]
Hi @StephenRidgway, I just read chapter 12 and it looks excellent. However, would you consider to include the science in the galactic plane as an additional "tension"? Some science cases in the plane require a cadence similar to the WDF at low galactic latitudes. cc. @willclarkson

**Comment by fedhere** [comment]
i think @chomiuk who is a TVS member would be interested in this issue

**Comment by StephenRidgway** [comment]
Hi @akvivas , Thanks for this very important comment.  Though I mentioned mini-surveys, I did not point out that the demand for mini-survey time is in competition with many things.  I will put something about that with an example of two.

Stephen

**Comment by StephenRidgway** [comment]
Added section called "Mini-surveys and Main Survey - Tension for Sure" and merged.

**Comment by drphilmarshall** [comment]
Thanks very much, Steve! I might add a thought or two on this topic myself
later today - I'll do it by PR so you can see the modifications. It should
be easy to build on such a clear summary.
