### ISSUE TITLE
AGN section needs sketching

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#36]
Hi Ohad, Timo:

Can you please make a quick sketch of your AGN section please, and check it in? You'll need it before next Friday morning, for a plenary session on the white paper. Great if you can stand up and tell the rest of the writing team (and the rest of the audience) what you are all about. 

Thanks!

Phil

**Comment by drphilmarshall** [comment]
@ohadshemmer can you please fix the refs in `agn.tex`? Then you can close this issue, I think :-)

**Comment by tanguita** [comment]
I updated the references and edited an equation. Hope it works (first github commit ever)

**Comment by drphilmarshall** [comment]
Looks good, @tanguita! I tweaked the formatting a little bit, and made the AGN section refs point at the non-periodic variables section (where I *think* AGN should get a mention). If you're happy, please  git pull, make and check the PDF, and close this issue (hooray! :-) )

**Comment by tanguita** [comment]
Looks good!

**Comment by StephenRidgway** [comment]
I agree AGN should be in the non-periodic variables table.  Should AGN stay in the transients table, or does non-periodic variable cover AGN adequately?

**Comment by AshishMahabal** [comment]
AGNs should stay in transients. But they are also non-periodic, and not all show transient behavior.

There is a small subset which likely show periodic behavior (or at least quasi-) but that is not enough to warrant them being out in the 'periodic' bin.

-ashish

**Comment by StephenRidgway** [comment]
OK, AGN appear as both varables and transients, with brief comment about why.  

Because of the organization of the paper, I’m thinking that the science and AGN specific metrics analysis will appear in the AGN section, and that AGN-relevant metrics in the “variables and transients” section will probably be more generic, addressing the needs of objects with certain types of behavior.  Just a suggestion, still plenty of time to negotiate coverage.

**Comment by drphilmarshall** [comment]
That could work. I suggest we try and define some AGN science projects, one
per section, one section per file, that address these various signals
(transient, QPO, long term variability etc), and `\input` them *somewhere*.
Then, we can see about moving some around, as we like. It makes total sense
for different AGN aspects to appear in multiple chapters, as Timo and Ohad
have anticipated. Thanks!
