### ISSUE TITLE
Sections need `\credit{}`s

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#368]
@rhiannonlynne can you please accredit each of the Solar System science cases with the (GitHub user)names of the people who did the work, please? I'll put in placeholders for you, commented out. Thanks!

**Comment by migueldvb** [comment]
@rhiannonlynne my username is `migueldvb` and I contributed to the comet activity section.

**Comment by rhiannonlynne** [comment]
Done - PR in
https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/381
