### ISSUE TITLE
Double check PHA discovery section following merge with chapter 2 content

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#369]
Hi @rhiannonlynne

When auditing the solar system chapter I first moved the PHA analysis section of Chapter 2 (that @ivezic  wrote?) into the Solar System chapter, on the grounds that it fitted better there (it's "science"). Then, you submitted a PR ( #366 ) that seemed to contain a new PHA analysis that supercedes the old one. So, I commented out Zeljko(?)'s and left it in the `SolarSystem_Discovery.tex` file, at the bottom. Can you please double check this file, and chapter 2, and make  sure that it is all consistent and accurate and actually what you want the white paper to show? Thanks! :-)

**Comment by davidtrilling** [comment]
i will do this.

david

On Thu, Apr 28, 2016 at 8:34 AM, Phil Marshall <notifications@github.com>
wrote:

> Hi @rhiannonlynne <https://github.com/rhiannonlynne>
>
> When auditing the solar system chapter I first moved the PHA analysis
> section of Chapter 2 (that @ivezic <https://github.com/ivezic> wrote?)
> into the Solar System chapter, on the grounds that it fitted better there
> (it's "science"). Then, you submitted a PR ( #366
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/366>
> ) that seemed to contain a new PHA analysis that supercedes the old one.
> So, I commented out Zeljko(?)'s and left it in the
> SolarSystem_Discovery.tex file, at the bottom. Can you please double
> check this file, and chapter 2, and make sure that it is all consistent and
> accurate and actually what you want the white paper to show? Thanks! :-)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/369>
>



-- 

=======================================================================
David E. Trilling
Associate Professor
Department of Physics and Astronomy
Northern Arizona University
928-523-5505

**Comment by drphilmarshall** [comment]
Thanks, David!

**Comment by rhiannonlynne** [comment]
I need to do a bit of this now - to move the basic description of the enigma_1281/enigma_1282 runs back into chapter 2. 
I'll reassign it to David after I do that much, so he can see if there is material from the PHA section which should go straight into our discovery section.

**Comment by drphilmarshall** [comment]
Thanks Lynne. Sorry for breaking things! Note that @ebellm and @fedhere are
working on the same problem, in #373

**Comment by rhiannonlynne** [comment]
Somewhat addressed in https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/381

@davidtrilling we should decide if we want the more specific PHA analysis that Zeljko had run through (or perhaps just to salvage some of his text) into our chapter. 
He was looking at PHAs, I did NEOs in our section. He did some more specific stuff relating to completeness at H=22, I did a more general overview (but in theory you could pull out the same information from what is there). 

Eventually, I think we will want to include a more specific PHA analysis and metric, similar to what he had. The question is if we could or should do that today/tomorrow. The analysis he has in his section is for the old tier1 runs, not the new set so would have to be redone. 

For now we may just want to salvage some of his text about the mandate and why this particular figure of merit (completeness H<=22) is important.

**Comment by rhiannonlynne** [comment]
@drphilmarshall we're going to move this PHA text to its own subsection. But -- I need to do some text editing to make it match the pattern for the other subsections. I don't think it's that much to do, but I have some other things I have to finish out first today. If I close this on Monday, will that work?
Otherwise, we could just leave this section out (but it's kind of a pity, because the metric analysis will be ready too).

**Comment by rhiannonlynne** [comment]
Done.

**Comment by drphilmarshall** [comment]
Nice work, Lynne - the solar system chapter is looking really good.
