### ISSUE TITLE
Supernova section needs sketching

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#37]
Hey, Team Supernova! Can you please check in a sketch of what you plan on putting in your section please? You'll need it to be in place in the PDF by next Friday morning, when you'll be called upon to stand in front of it and briefly explain it to the rest of the white paper writers (and everyone else at the Bremerton workshop). Thanks! 

Phil

PS. I assigned this to @MichelleLochner just to get started - feel free to re-assign to @rbiswas4 or Jeonghee as you see fit! :-)

**Comment by MichelleLochner** [comment]
Rahul has been making some excellent progress on an internal discussion document and circulating it around the working group. Rahul perhaps now would be a good time to start integrating some of these thoughts and the other things we've been discussing via email into the white paper section? If you like, I can make a first stab at some section headings.

**Comment by drphilmarshall** [comment]
Excellent idea! My advice would be to transfer as much as you can to the
repo latex as soon as possible, so that the other white paper authors can
see where you are. Early feedback is the best kind, to catch overlaps and
confusion early on.

Thanks for all your efforts so far - looking forward to seeing where you
are in your thinking!

**Comment by StephenRidgway** [comment]
That would be timely.

Please note that the outline is “recommended” in the master document down to the subsection level, I’m not sure if everything will fit into that schema, but have been trying so far.

Steve

**Comment by rbiswas4** [comment]
Hi Michelle,

That would be great if you went ahead and added stuff in:

Something that I had started is in a fork of the repo
https://github.com/rbiswas4/ObservingStrategy. Feel free to either use
that, ask me to merge it, or we can merge later if necessary.

Thanks,
Rahul

**Comment by StephenRidgway** [comment]
Hi,

I don’t have experience editing with such a large team, but the effort is spread over a large number of topics.

My recommendation would be for authors to merge into the master as soon as they have a complete draft.  

What do others think?  

Steve

**Comment by rbiswas4** [comment]
Hi @StephenRidgway, 

Obviously your question is more general, (and I agree with your thoughts)
but just to be clear since this was tied to my comment: what I pointed to is much closer to an empty draft than a complete draft, and hence I had not thought of merging it in,

**Comment by drphilmarshall** [comment]
At this size of group, I'd say Steve was right: the most important thing is
that all co-authors can see the paper easily as it evolves. Forks are
useful for enabling separate development without breaking the code in the
base repo, but since we designed the paper to be very modular, there should
be no problem with conflicts if we all just push directly to origin/master.

Having said that, the GitHub pull request mechanism is really nice for
enabling people to see the changes you have made, so if you want to work in
a fork, that's fine too. My only  request is that you start the pull
request as soon as you start writing, so that we all know what you are
doing and can follow along. The danger in everyone working in isolation is
that we won't be able to help you catch problems early...

**Comment by StephenRidgway** [comment]
Phil,

I understand that I execute a pull request before I start writing, so that I am starting with the most current document on my local file set.

I don’t understand how you know what I am doing and follow along.  Aren’t you “in the dark” until I do a push?

Steve

**Comment by drphilmarshall** [comment]
Nope - when you open a pull request, GitHub makes an issue-like comment
thread that you can use for discussion in the meantime. Here's a good
example:

https://github.com/drphilmarshall/Lens-Zoo/pull/77

See how every commit made in the development branch is tracked, and
clicking on them shows you the changes made in that commit? It's really
nice. And people can "watch" that PR, so they get a notification when a
comment is made, just like with the issues. Anyone with a copy of the repo
can git pull from the development branch into a local branch, too, in case
they want to see how the code works, make their own edits, and so on.

**Comment by rbiswas4** [comment]
@drphilmarshall OK I will make a PR.

**Comment by MichelleLochner** [comment]
Ok I've added a introductory section on the photometric classification. I'm not sure exactly where it should go but we can easily move it later. Er... I just pushed it to master, I forgot to make a PR. Should I do that in future?

**Comment by drphilmarshall** [comment]
Don't worry about it - by replying to the issue, we all now know to git
pull and check out your work. Thanks very much!

BTW Did you know you can close issues with a commit message?

    git commit -am "First attempt at supernova cosmology sections (needed
two instead of just one). Closes #37"

The magic words are "closes", "closed", "fixes" and "fixed", right before
an issue number (#37 in this case). These days I'm trying to include an
issue number in every commit (which admittedly means issuing everything :-)
)

**Comment by MichelleLochner** [comment]
Oh that's cool. Not that I'd consider this issue closed yet. ;) But I'll try add it to future commits. Nifty feature.

**Comment by drphilmarshall** [comment]
OK, team supernovae: I'm going to close this old "sketch your section" issue - but watch out for a "define your metrics issue" if I don't find one already open :-)
