### ISSUE TITLE
defining opsim macros for solar system OpSim runs (e.g., enigma_1281)

### ISSUE THREAD

**Issue by fedhere** [LSSTScienceCollaborations/ObservingStrategy#373]
making sure the enigma_1281 run name renders

**Comment by drphilmarshall** [comment]
Don't forget to use the macros, to enable hyperlinking back to Chapter 2!

**Comment by ebellm** [comment]
@drphilmarshall We're using the macros; the problem is that one of the runs we compare is no longer in chapter two.  It's the NEO visit triplets: \opsimdb[db:NEOswithVisitTriplets]{enigma\_1281}{NEO test: triplets of visits.}

**Comment by drphilmarshall** [comment]
Ah! I see. Feel free to add extra definitions in Chapter 2 as you need them.

**Comment by ebellm** [comment]
It looks like the definitions were (re)-moved by @drphilmarshall when he put the NEO completeness discussion in SolarSystem/SolarSystem_Discovery.tex.  It's broken a bunch of references through the solar system chapter as well.  Is the right thing to uncomment the `\opsimdb` definitions in that file, or put them back in cadexp2.tex?

**Comment by rhiannonlynne** [comment]
Ah - I was just finding that (and thinking that they were still in chap2). 
I can't find any of the definitions anymore though. Where are things being defined now?

**Comment by ebellm** [comment]
They're undefined at the moment, but the actual text is commented out at the bottom of SolarSystem/SolarSystem_Discovery.tex

**Comment by rhiannonlynne** [comment]
Actually, now I'm very  confused. Where did the material that was describing enigma_1281 and enigma_1282 end up?  I think that basic description needs to go back into chapter 2, as there is more than just the solar system chapter referring to these runs. We can take out the specific parts which talk about completeness, as those particular topics are covered in the solar system chapter. 

However, I can no longer find that material -- I thought Phil had dumped it somewhere into our chapter? Or do I just need to go back to an earlier version of cadexp2, pull the relevant pieces out, and put it back in the new version?

**Comment by ebellm** [comment]
I think our comments crossed--if you look at the bottom of SolarSystem/SolarSystem_Discovery.tex, there's a large block of commented-out text, and the material for enigma_1281 and enigma_1282 is in there--search for `NEOswithVisitTriplets` for instance.

**Comment by rhiannonlynne** [comment]
Yes- found it! I'm working on this. I'll submit a PR within the hour - ok?

**Comment by drphilmarshall** [comment]
Ahhh - I guess they all have to be in cadexp2, so they can appear in the
table there. Sorry about this!

**Comment by ebellm** [comment]
Thanks Lynne!

**Comment by drphilmarshall** [comment]
<sheepish>

Thanks for cleaning up - I should have commented the solar system latex
better, sorry. You are on the right track though. Thank you!

**Comment by rhiannonlynne** [comment]
Hey Phil - I want to discuss enigma_1281 and enigma_1282 together in the same section as they're so similar, but I'm having a formatting problem.  If I put the 
\opsimdb[db:NEOswithVisitTriplets]{enigma\_1281}{NEO test: triplets of visits.}
in the tex, then I get a line between the two opsim names, before I get the discussion of them both.

Is there a way to turn that off right there?
I'm going to go ahead and send in the PR, but if you can help me fix this it would be easier to read I think.

**Comment by rhiannonlynne** [comment]
PR in 
https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/381

**Comment by ebellm** [comment]
Thanks Lynne!  Looks great now.
