### ISSUE TITLE
Check on solar system chapter content

### ISSUE THREAD

**Issue by rhiannonlynne** [LSSTScienceCollaborations/ObservingStrategy#379]
Final check / read-through before sending off for version 1 internal review.

Just making sure this issue is here so we can indicate when we're ready! 
 
@davidtrilling @rhiannonlynne

**Comment by rhiannonlynne** [comment]
I think we're ok with the general content.

**Comment by drphilmarshall** [comment]
Hooray, Solar System! A completed chapter, ready for review :-) Thanks for
all your efforts, all.
