### ISSUE TITLE
Deep drilling field chapter needs sections

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#40]
@rhiannonlynne and Niel, would you mind checking in what you have on deep drilling fields please? We're having a plenary session next Friday at the Bremerton workshop, where each section lead will be asked to stand up and explain briefly what will go in their section - great if you can put the sections in place and add enough notes for them to make sense before then! Thanks very much :-)

PS. I have assigned this to you, @rhiannonlynne, while I find out Niel's GitHub ID...

**Comment by drphilmarshall** [comment]
@rhiannonlynne @nielbrandt The Deep Drilling Fields chapter is still completely empty, so I'm going to re-milestone this issue to next week's meeting. Feel free to make new issues to help you get it into the shape you want it to be in by next week: I haven't seen much DDF discussion yet, so now could be a good time to start some conversations on here.

**Comment by drphilmarshall** [comment]
Big decision today: abandon the DDF chapter! Individual science sections will analyze the implemented DDFs, and the special surveys chapter will include discussion of further proposed DDF projects. Let us know your thoughts, @nielbrandt !

**Comment by nielbrandt** [comment]
Hi,

This seems reasonable to me. Please do consider all the DDF ideas
in the DDF white papers, and not only those that have currently been
implemented in OpSim. A lot of effort went into the good ideas in
those white papers, and sadly they have been underutilized in my
opinion.

And, as I've mentioned several times before, it will be helpful to
have some clarity when possible about how future decisions regarding the
DDFs will be made. Does the Deep Drilling Interest Group have a
role to play in this, or is it now somehow disbanded? I asked
Michael S. about this a couple days ago when I was in Tucson, and nobody
seems to know! Worth getting this situation under control.

Thanks, Niel



On 11/19/15 10:17 PM, Phil Marshall wrote:
> Big decision today: abandon the DDF chapter! Individual science
> sections will analyze the implemented DDFs, and the special surveys
> chapter will include discussion of further proposed DDF projects. Let
> us know your thoughts, @nielbrandt <https://github.com/nielbrandt> !
>
> — Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/40#issuecomment-158267064>.
>


-------------------------------------------------------------------------------
Niel Brandt; Department of Astronomy and Astrophysics; The Pennsylvania
State University; 525 Davey Lab; University Park, PA 16802 USA
Phone: (814) 865-3509; FAX: (814) 863-3399; Office room number: 514A;
AIM: Niel Brandt; WWW: http://www.astro.psu.edu/users/niel/index.html
-------------------------------------------------------------------------------
