### ISSUE TITLE
Give the pub board some advance notice

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#416]
Contact Pat B, tell her when the v1 WP will be submitted, and advise on it's unusual nature.

**Comment by bethwillman** [comment]
Tim Jenness is now the chair of the Publication Board.  Has anyone talked with him about this yet?

**Comment by drphilmarshall** [comment]
@ivezic is going to contact Tim Jenness about LSST pub board review of v0.99 chapters 1, 2 and 12 - let us know how that goes, Zeljko!

**Comment by ivezic** [comment]
Done, see
https://jira.lsstcorp.org/browse/PUB-42

**Comment by drphilmarshall** [comment]
Great, thanks Zeljko! I started a conversation with Tim about how we should implement changes during review - once we converge, I'll inform the writing team here.
