### ISSUE TITLE
Feedback on Cepheids Section 5.2

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#417]
@AshishMahabal @lmwalkowicz Who wrote the Cepheids section in your chapter, please?@StephenRidgway provided the following comments for them, below. Thanks!

Comments on "5.2 The Cepheid Mass-Luminosity Relation"

"once the evolve " -> once they evolve 

"B20 and references therein" - B20 is not defined

The Fourier decomposition looks odd.  The term phi_k looks like a phase, should it be inside the cos argument?  

The abbreviation PC is used before it is defined.  (It is defined in the next paragraph).

"have clearly demonstrated" - "clearly masks" - should avoid using "clearly" except for strong reason - risks being mistaken for posturing

Paragraph beginning: "What cadence is required for “accurate multiwavelength Fourier decomposition”?" - 

I assume that these stars are strictly periodic and that data can be folded onto a single cycle.  I suggest clarifying whether the decomposition would be done on a folded light curve, or on the full light curve.  If it is the former, then it is not realistic to ask for a cadence that optimizes the sampling, as the cadence would be different for every period. Can the success of the decomposition be cahracterized based on the maximum phase gap in the folded light curve?

"Probably more opsim experiments are required" - I would disagree, and say that what is needed is the Fourier study of any one simulated schedule.

(Petersen 1980) - there is no corresponding entry in the biblio

"and the compare" -> and then compare

Comments on "5.2.1 Description of Relevant Metrics"

Suggest deleting the table, as it does not correspond exactly to the metrics discussed.

Figures - I would suggest including in the caption the medan value of the metric over the main survey fields, and also the median over the galactic plane sub-region.

"the correct period of sinusoid" -> the correct period of a sinusoid

**Comment by keatonb** [comment]
Attention @ShashiKanbur, I believe these comments are for you.

**Comment by ShashiKanbur** [comment]
Hello, I tried to address some of these comments - the section on "Description of relevant Metrics" was not written by me. Let me know if there are any other points. Thanks.
