### ISSUE TITLE
Feedback on ZZ Cetis Section 5.3

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#418]
Hi @keatonb - @StephenRidgway has reviewed your section, and has the following comments! See what you think.

Comments on "5.3.1 The Case for ZZ Cetis"

"Strategies that maximize photometric precision and total number of visits in all filters optimize the survey toward this goal, but the tradeoffs between these dual requirements are complicated and must be explored in MAF to be understood."

I do not understand why there is any trade between photometric precision and total number of visits. 
Is this point an argument for increasing the number of visits in the galactic plane?

"significant variability should be detected in the u band for at least 1000 ZZ Cetis"

It would be nice if the number 1000 could be motivated more quantitatively - for example if it were desired to obtain statistically significant sampling with 10 temperature bins, 10 period bins and 10 amplitude bins.

**Comment by keatonb** [comment]
Thanks for your comments on this section @StephenRidgway 
```
"Strategies that maximize photometric precision and total number of visits in all filters optimize the survey toward this goal, but the tradeoffs between these dual requirements are complicated and must be explored in MAF to be understood."

I do not understand why there is any trade between photometric precision and total number of visits. 
Is this point an argument for increasing the number of visits in the galactic plane?
```

The tradeoff here has to do with exposure times.  We could obtain higher photometric precision with longer exposure times, but we would end up with fewer visits overall.  The MAF analysis favors the strategy with 60-second _u_ band visits, providing greater photometric precision in _u_.  I know there are some other existing OpSim runs that explore other potential exposure times.

```
"significant variability should be detected in the u band for at least 1000 ZZ Cetis"

It would be nice if the number 1000 could be motivated more quantitatively - for example if it were desired to obtain statistically significant sampling with 10 temperature bins, 10 period bins and 10 amplitude bins.
```

This is a great point.  I will try to write a revision that does a little better job of motivating this.  One reason that 1000 is attractive is that it is ~an order of magnitude greater than the number of ZZ Cetis currently known.  We would also like to be able to track the evolution of pulsation amplitudes through temperature bins (and surface gravity bins too, though this may be more tricky to pin down from photometry alone).

**Comment by StephenRidgway** [comment]
Ah, yes, u band.  By all means.  Perhaps I was reading carelessly and extrapolated down the wrong path.  Your point about an order of magntiude increase is also perfectly fair - that is easy to understand as significant.

**Comment by keatonb** [comment]
Okay.  I've just submitted a pull request with my clarified revision.

**Comment by keatonb** [comment]
The pull request has was accepted a while ago.  This issue can be closed.
