### ISSUE TITLE
Feedback on Young Stars Section 5.4

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#419]
@phartigan - I think you are actually best placed to tidy up Section 5.4 after all. @StephenRidgway read through it, and has the following comments (which I'm sure make sense to you!). He is suggesting that you make your proposal  for a new survey in its own subsection, I think - this what other groups have done, and it helps keep the concepts of survey evaluation and survey optimization separate. Sorry I was not able to do better with the merge of content between you and @pmmcgehee !

Comments on "5.4 Discovery and Characterization of Young Stellar Populations"

"From the Milky Way science perspective:"

All of the Milky Way perspective sections have redundancy with the previous sections.  I suggest deleting them and putting any missing info in the previous sections.

"B. Period Recovery for wTTs" - there are question marks in this section

"The Need for Annual Dense Coverage of a Few Selected Regions"

This plan cannot be implemented as part of a regular cadence strategy.  If it is needed, it should be proposed as a mini-survey project.  Since this is the first mini-survey that would require multiple consecutive days, it is important to enter it as a request in  order for that type of demand to be studied.

**Comment by drphilmarshall** [comment]
Just seen your recent messages on the old thread, #321. Thanks for volunteering, @phartigan ! You asked:
> Which sections, specifically, need to be downloaded and merged?

Can you please `git pull` to get the most recent version of the whole paper, and then work on `Variables/youngstars.tex`? The whole section needs reading through and editing so that it makes sense, and is as concise as possible. Then, Steve's other comments above need attending to. Thank you!

**Comment by phartigan** [comment]
ok.

**Comment by phartigan** [comment]
ok, I've merged it all and think I've submitted a pull request.

The mini-survey part is a standalone that could be moved en-masse to
another section if desired.

Pat

**Comment by pmmcgehee** [comment]
Hi Pat,

Yes, I see your pull request - looking at the changes now.

Peregrine

On Wed, May 25, 2016 at 12:38 PM, phartigan <notifications@github.com>
wrote:

>
> ok, I've merged it all and think I've submitted a pull request.
>
> The mini-survey part is a standalone that could be moved en-masse to
> another section if desired.
>
> Pat
>
> > @phartigan - I think you are actually best placed to tidy up Section
> > 5.4 after all. @StephenRidgway read through it, and has the
> > following comments (which I'm sure make sense to you!). He is
> > suggesting that you make your proposal for a new survey in its own
> > subsection, I think - this what other groups have done, and it helps
> > keep the concepts of survey evaluation and survey optimization
> > separate. Sorry I was not able to do better with the merge of
> > content between you and @pmmcgehee !
> >
> >
> > Comments on "5.4 Discovery and Characterization of Young Stellar
> Populations"
> >
> > "From the Milky Way science perspective:"
> >
> > All of the Milky Way perspective sections have redundancy with the
> > previous sections. I suggest deleting them and putting any missing
> > info in the previous sections.
> >
> >
> > "B. Period Recovery for wTTs" - there are question marks in this section
> >
> >
> > "The Need for Annual Dense Coverage of a Few Selected Regions"
> >
> > This plan cannot be implemented as part of a regular cadence
> > strategy. If it is needed, it should be proposed as a mini-survey
> > project. Since this is the first mini-survey that would require
> > multiple consecutive days, it is important to enter it as a request
> > in order for that type of demand to be studied.
> >
> >
> > ---
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/419
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/419#issuecomment-221683455>
>



-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199

**Comment by pmmcgehee** [comment]
Pat et al.,

That's fairly concise cleanup - and in general looks good. Three minor
comments on the changes I see in youngstars.tex.

o The shortest wavelength band in LSST is "u", so the upper case "U"s
should be replaced by "u".
o What is the reference for d=414 pc for Orion, and which cloud/complex
within Orion does this refer to?
o Table {table:pseudoForExor} needs to fleshed out.

Thanks!
Peregrine

On Wed, May 25, 2016 at 1:27 PM, Peregrine McGehee <
peregrine.mcgehee@gmail.com> wrote:

> Hi Pat,
>
> Yes, I see your pull request - looking at the changes now.
>
> Peregrine
>
> On Wed, May 25, 2016 at 12:38 PM, phartigan <notifications@github.com>
> wrote:
>
>>
>> ok, I've merged it all and think I've submitted a pull request.
>>
>> The mini-survey part is a standalone that could be moved en-masse to
>> another section if desired.
>>
>> Pat
>>
>> > @phartigan - I think you are actually best placed to tidy up Section
>> > 5.4 after all. @StephenRidgway read through it, and has the
>> > following comments (which I'm sure make sense to you!). He is
>> > suggesting that you make your proposal for a new survey in its own
>> > subsection, I think - this what other groups have done, and it helps
>> > keep the concepts of survey evaluation and survey optimization
>> > separate. Sorry I was not able to do better with the merge of
>> > content between you and @pmmcgehee !
>> >
>> >
>> > Comments on "5.4 Discovery and Characterization of Young Stellar
>> Populations"
>> >
>> > "From the Milky Way science perspective:"
>> >
>> > All of the Milky Way perspective sections have redundancy with the
>> > previous sections. I suggest deleting them and putting any missing
>> > info in the previous sections.
>> >
>> >
>> > "B. Period Recovery for wTTs" - there are question marks in this section
>> >
>> >
>> > "The Need for Annual Dense Coverage of a Few Selected Regions"
>> >
>> > This plan cannot be implemented as part of a regular cadence
>> > strategy. If it is needed, it should be proposed as a mini-survey
>> > project. Since this is the first mini-survey that would require
>> > multiple consecutive days, it is important to enter it as a request
>> > in order for that type of demand to be studied.
>> >
>> >
>> > ---
>> > You are receiving this because you were mentioned.
>> > Reply to this email directly or view it on GitHub:
>> >
>> https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/419
>>
>>
>>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/419#issuecomment-221683455>
>>
>
>
>
> --
> Dr. Peregrine M. McGehee
> Santa Clarita, CA    (626) 993-4199
>



-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199

**Comment by phartigan** [comment]
That's fine, change U to u if you like. I kept your table
in there. If you don't want it, you can remove it without affecting the flow.
Personally I don't think that level of detail is too crucial since it
ought to be fairly straightforward to identify eruptive variables, but
your call.

The reference for Orion at 414 +/- 7 pc is Menten et al 2007, A&A 474,  
515. It is
a VLBA distance. It replaces the old standard 450 pc.  Add it if you  
want, though
we don't have refs for distances to rho-Oph, Carina, etc, so I'd probably
leave it out.

ph

> Pat et al.,
>
> That's fairly concise cleanup - and in general looks good. Three minor
> comments on the changes I see in youngstars.tex.
>
> o The shortest wavelength band in LSST is "u", so the upper case "U"s
> should be replaced by "u".
> o What is the reference for d=414 pc for Orion, and which cloud/complex
> within Orion does this refer to?
> o Table {table:pseudoForExor} needs to fleshed out.
>
> Thanks!
> Peregrine
>
> On Wed, May 25, 2016 at 1:27 PM, Peregrine McGehee <

**Comment by drphilmarshall** [comment]
Sounds good! @pmmcgehee I re-assigned this to you to finish off and close out. Thanks!

**Comment by pmmcgehee** [comment]
Ok.. I'll do that.

Pat, thanks for the reminder of the Menten+2007 VLBA trig parallax values.
The 414+/-7 pc value is specifically for the ONC. I don't think we need to
cite it in the paper.

Peregrine

On Wed, May 25, 2016 at 3:57 PM, Phil Marshall <notifications@github.com>
wrote:

> Sounds good! @pmmcgehee <https://github.com/pmmcgehee> I re-assigned this
> to you to finish off and close out. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/419#issuecomment-221732447>
>



-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199

**Comment by pmmcgehee** [comment]
Phil - could you please go ahead and merge Pat's changes? Then I will edit
from there.

Thanks
P

On Wed, May 25, 2016 at 4:39 PM, Peregrine McGehee <
peregrine.mcgehee@gmail.com> wrote:

> Ok.. I'll do that.
>
> Pat, thanks for the reminder of the Menten+2007 VLBA trig parallax values.
> The 414+/-7 pc value is specifically for the ONC. I don't think we need to
> cite it in the paper.
>
> Peregrine
>
> On Wed, May 25, 2016 at 3:57 PM, Phil Marshall <notifications@github.com>
> wrote:
>
>> Sounds good! @pmmcgehee <https://github.com/pmmcgehee> I re-assigned
>> this to you to finish off and close out. Thanks!
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/419#issuecomment-221732447>
>>
>
>
>
> --
> Dr. Peregrine M. McGehee
> Santa Clarita, CA    (626) 993-4199
>



-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199
