### ISSUE TITLE
Feedback on Preface and Introduction?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#421]
Hi @michaelstrauss 

It would be _great_ if you would review the Preface section and Introduction chapter for us. What we need is to make sure that we have correctly framed the paper, and explained the living document concept well. It might be good to skim the rest of the paper to check for consistency as well. 

Here's the "final draft" of the paper: 

https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf

If you could give us your feedback via the issues system that would be best. You could just paste your thoughts into this thread, or you could open up separate issues for each thing that needs fixing (especially if the best person to address your comments and queries is different each time). 

Thanks very much for helping out with this! :-)

**Comment by michaelstrauss** [comment]
Do we use the phrases "baseline cadence" and "universal cadence" to be synonymous or not?  It is unclear in the white paper.   Perhaps you want to restrict "universal cadence" to the observing plan for the Deep-Wide-Fast component, and "baseline cadence" for the minion_1016 realization, including the deep fields.

**Comment by drphilmarshall** [comment]
Yes, you're right - they are not synonymous, and should not be used as
such.

**Comment by michaelstrauss** [comment]
OK, but we never quite define them or their distinction.  I'm working now on 
the introduction; I'll try to make this clear (assuming I said it correctly below). 

						-Michael

**Comment by michaelstrauss** [comment]
OK, I've made some edits on the preface and the introduction, mostly cleaning up minor wording
issues, etc.  Here are some specific concerns and notes, reading sequentially through: 

  Preface: Only very minor edits; it looks fine. 

  Introduction: 
    -I wonder whether I should be included as a chapter editor?  I wrote a good chunk of the first
few pages.  (It's perfectly OK if I am not). 

   I added a reference to the DESC white paper on the first page. 

   Section 1.1 title used the phrase 'universal cadence' without defining it; this is the only place where it appears in the chapter.  I changed the title, but the distinction between baseline and universal cadence needs to be made explicit. 

  End of second paragraph states that the DWF survey requires 85% of the observing time, but Chapter 2 states that it is 60%.  This needs to be made explicit.  

  Just below that, the third bullet refers to four deep drilling fields.  Chapter 2 refers to 5.  Which is correct?  We should explicitly list them somewhere. 

  Section 1.2 was written at the beginning of this whole process, and thus is somewhat tentative and mostly in the future tense: it was trying to give guidelines for what would come later.  Those later chapters are now in place, and I think the tentative tone and future tense of the text could be modified a bit, to be consistent with what actually appears in those chapters.  I didn't take a stab at this, but Phil @drphilmarshall is probably the right person to think about this.  For example, there are tentative words asking everyone to design FoM in the same units; does that reflect the current reality at all? 

  Section 1.3 is instructions.  As I understand it, we want to keep these more-or-less in place, as we want to encourage new contributions to what currently exists.  However, this was written before most of the white paper existed (so there is a reference to the lens time delay section, one of the first that was put in place).  Again, Phil should give this a readthrough and ask whether the tone needs to be changed at all to reflect the present reality. 

  Finally, I'll point out that the link to the GitHub repository at the beginning of Section 1.3.1 appears to be broken. 

					Thanks,  Michael

**Comment by rhiannonlynne** [comment]
Thanks for catching those errors @michaelstrauss  - the WFD survey definitely takes 85% of the observations (and I'd guess about 85% of the observing *time* as well), in the baseline survey. 
There are 5 DD fields in the current baseline survey, of which 4 are pre-selected fields (so the location of the 5th is subject to change). 
The contents of this community page may be helpful for DD clarification:
https://community.lsst.org/t/deep-drilling-whitepapers/732/2

(note that I didn't look up the errors in chapter 2 or the introduction, so there may be some context I'm missing?)

**Comment by bethwillman** [comment]
Michael - It looks like the intro hasn't been edited in a month.  Did you merge in your edits?  I'm doing a close review of the Preface and Intro as well and want to work from the most recent version.  Thanks!
