### ISSUE TITLE
Does the Preface explain the white paper concept sufficiently well?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#425]
@bethwillman Would you mind reading the white paper Preface and letting me know what you think? It's important to communicate the white paper concept well, so both our readers and our prospective contributors understand what they are looking at. Should this be done in the Introduction or the Preface, do you think? Thank you!

**Comment by bethwillman** [comment]
Hey Phil - Whats my deadline for this?  I could do it late next week with
deadline of ~June 3.

On Tue, May 24, 2016 at 9:24 AM, Phil Marshall <notifications@github.com>
wrote:

> @bethwillman <https://github.com/bethwillman> Would you mind reading the
> white paper Preface and letting me know what you think? It's important to
> communicate the white paper concept well, so both our readers and our
> prospective contributors understand what they are looking at. Should this
> be done in the Introduction or the Preface, do you think? Thank you!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/425>
>



-- 
Beth Willman
LSST Deputy Director
Associate Astronomer, Steward Observatory
933 North Cherry Avenue
Tucson, Arizona 85721
520-318-8473

**Comment by drphilmarshall** [comment]
That would be perfect, thanks Beth! I've pushed the internal review
milestone back to June 3rd: I can work on addressing your comments in the
week following that.

**Comment by drphilmarshall** [comment]
Closed by #599 !
