### ISSUE TITLE
Feedback on the AGN Chapter

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#427]
Hi @lmwalkowicz - would you mind please reading and commenting on Chapter 8 please? The AGN group have put in a lot of work laying out their science cases, and have suggested AGN experts to review them - what I think we also need is a high level review of the chapter to make sure that it tells a coherent story, and to check that the quantitative / metric analysis is presented well (eg with appropriate context, and consistent with our Figure of Merit approach). Is their future work laid out clearly?

You can [download and view the v0.8 PDF here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or comment/edit the current version in `master` if you prefer. Great if you can either post comments and queries to this issue thread, or make new issues assigned to suitable people if you see things that need fixing. 

Thank you!

**Comment by lmwalkowicz** [comment]
Hi all, 
Chapter is looking good! I think it lays out the work done so far and the future work fairly well. Suggestions below for the future work section:
@ohadshemmer: the AGN clustering paragraphs seem like fragments, it might be helpful to spell out what the future work associated with this question would be, ideally. 
Section 8.4.2 looks good, but the "Discussion" bit could have the first two sentences deleted and the next paragraph merged into the preceding section as the concluding paragraph of the section on metrics. 
8.4.3: BELR is used earlier in the chapter without being defined-- please spell out the acronym when it first appears.

**Comment by ohadshemmer** [comment]
Hi @lmwalkowicz

Thanks for reviewing the chapter.
As for the "clustering" section - I'm not sure why it was resurrected - we commented it out completely back in Tucson in Nov.
As for microlensing (8.4.2 and 8.4.3) - I think this has since been edited by @tanguita - Timo can you please check this out and confirm?

**Comment by tanguita** [comment]
Hi @lmwalkowicz, @ohadshemmer,

I think you might have read a rather old version. There is no discussion section in 8.4.2. I did fix the BELR issue though.

Thanks!

Timo

**Comment by ohadshemmer** [comment]
@tanguita 

Would you mind also verifying that the "AGN Clustering" section is now gone too (I think it was 8.5.1 in the version I read - not sure - currently traveling...). Thanks!

**Comment by tanguita** [comment]
@ohadshemmer 

Indeed AGN Clustering is part of the Future Work section.

**Comment by ohadshemmer** [comment]
@tanguita 

Can you please comment it out completely?
We removed the "clustering" section back in Nov. around the Tucson meeting,
in consultation with Michael Strauss.

**Comment by tanguita** [comment]
@ohadshemmer DONE
