### ISSUE TITLE
Feedback on Galaxy Section 4.2 Populations in the Disk

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#428]
Hi @ebellm ! Thanks for agreeing to do some section reviewing :-) Would you mind taking a look at Section 4.2 of the Galaxy chapter, please? I pushed the internal review milestone back to June 3rd, so you've got until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit. 

What we are looking for at this stage is to address the following questions about each science section:

1. Does the chapter tell a coherent story about the science that is being planned? 

2. Each science section (eg Sections 3.2 - 3.7 inclusive) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  

3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 

4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of the pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread; the chapter editors @willclarkson and @akvivas can then follow along. 

Thank you!

**Comment by ebellm** [comment]
Hi @willclarkson, @caprastro, @cbritt4, @chomiuk, here's are my (mostly minor) comments on Section 4.2:

Overall the section does a nice job advocating for improved Plane coverage with some detailed presentation of several science cases.  The draft figures of merit are well-developed (although they indicate the challenges of doing population-level analysis with the MAF!).

One question the chapter doesn't really address is the following: should the Galactic Plane be a special survey?  It's conceptually (and maybe politically) simpler to fold it in to the WFD, as you suggest in the qLMXB section, but is that scientifically the best choice?  One could imagine alternative Plane surveys that prioritize the redder bands to reduce the time between revisits, for instance.  I'd suggest discussing more extensively the range of possibilities while emphasizing that WFD is already quantifiably better than the current baseline..

I'd suggest running an even more simplified version of FoM 1.1 to further bolster the case for ditching the current baseline.  Namely, you could run the periodicStarMetric on a pure sine with period and amplitude appropriate for a qLMXB.  While not capturing the lightcurve shape, my guess is that the (single-band) period recovery would be low with the baseline cadence, and would really hammer home its deficiency even for variability science in the Plane.

Specific comments:

- I would remove the discussion of the Milky Way supernova saturating LSST near peak; followup of such an event would be plentiful.  LSST's unique contribution would be in pre-explosion imaging.

- the "Possible Higher-Order FoMs" have a fair number of sentence fragments which could be made into complete thoughts,

- I'm not certain if `TripletMetric` is the right metric to use in FoM 2.2--it's not a control time, but a pure count of observation triples satisfying some separation criteria.  So if OpSIM run 1 gives a higher TripletCount than run 2, it is better--but the values don't allow you to calculate the actual relative rates.  Maybe @lundmb can correct me here.

- Finally, and this is an issue for @drphilmarshall, we should standardize our FoM numbering.  In the Transients chapter, for instance, we used Chapter.Section-FOM (6.1-1).  I'll make a top-level issue.

**Comment by willclarkson** [comment]
Thanks @ebellm ! You make a number of excellent points here. 

Regarding the filter-set issue, one possibility might be to do periodicStarMetric for a very red or very blue fiducial object (like a qLMXB at some fiducial apparent magnitude). We could even scale the recovery fraction with the stellar density (so basically the Galactic Supernova case with the sinusoid replacing the transient). Then the FoM would distinguish naturally between the strategies in terms of the science hit on very blue populations under different strategies. @cbritt4 @caprastro @chomiuk , what do you think?

I think it's clear that a number of alternative plane strategies should probably be proposed for the OpSim folks with different tweaks to the filter balance for the plane, but I am uncertain on the timescale this would require. We also don't know just yet what range of strategies would be good. For example, have one in which (0.7, 0.3) of the exposures in (u, g) are apportioned to the redder filters? Input is welcome! 

cc @akvivas

**Comment by lundmb** [comment]
@ebellm does make a point I should''ve noticed in there. I'm a little bit
uncertain of the intent, but TripletMetric may be getting slightly misused
in this context. It might help to know what the desired goal is from
TripletMetric a bit more. There is some issue that the current instance
doesn't address overlaps in the triplets.

**Comment by willclarkson** [comment]
Thanks @lundmb - the intention there was to use a metric that returns the fraction of events of type X that could be noticed by LSST. 

I thought that's what TripletMetric does, based on the time distribution of the observing dates only (so a rise might be noticed if events separated by delta-t1 and a fall noticed if separated by delta-t2). 

From this discussion, however, it sounds like it returns a pure count of triplets of some specification, not the fraction of events that were covered by observations at decent cadence. 

I think I picked TripletMetric in that FoM sketch because I thought it would be faster to evaluate than the other metrics that require the fiducial lightcurve. Would you recommend using one of the transient metrics instead for this purpose then?

**Comment by lundmb** [comment]
Correct, the value it returns is how many triplets fit that specification.
It may be possible to base something off of that, however, and it may be
best at this point to just specify what the needed metric would do, as I
think you're right in that something can be done in a general form that
will be quick to calculate if all you're requiring is some pattern in
observations, and don't need to use the lightcurve itself.

**Comment by willclarkson** [comment]
Thanks @lundmb  - OK it sounds like it's best just to change the discussion in there from calling TripletMetric explicitly. I should be able to get to that either tonight or tomorrow (06/03).

**Comment by willclarkson** [comment]
Hi @caprastro @cbritt4 @chomiuk - unless I hear otherwise from you, I will make as many of the changes as I can in Chapter 4.2 by the end of the day. 

Thanks!! - Will

**Comment by cbritt4** [comment]
I think getting an OpSim run using redder filters towards the Plane is a
good idea. The periods of interest are short, even down to a couple hours.
Having a special survey where we just hammer on even just one part of the
Plane is worth considering. I agree that the bluer filters in this case
should be swapped for more frequent visits in redder ones. The sampling
pattern is, of course, crucial at such short periods.

**Comment by ebellm** [comment]
Just to be clear, I don't think you guys need to specify your preferred alternative cadence to WFD in the Plane.  I just think a few sentences outlining possible cadence tweaks will help make the case for future OpSIM tests at the project level.

**Comment by willclarkson** [comment]
Thanks @ebellm and @cbritt4 - your comments came in while I was editing! 

I suspect github has already informed you, but I just merged a pull request that implements @ebellm 's suggestions (pull request #465). The material on filter alternatives is at the end of the section (in Section 4.2.4). 

@cbritt4 - for the medium-term (probably not the Pub Board deadline!) it would be good to know what sort of strategy one might propose for. I expect the compact object science cases are going to be the ones that suffer most from low blue-filter coverage.

**Comment by ebellm** [comment]
Looks good to me, @willclarkson!  Closing this issue.
