### ISSUE TITLE
Feedback on Galaxy Section 4.3 Positions, Proper Motions and Parallax

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#429]
Hi @dnidever  Would you mind doing some section reviewing, please? It would be great if you could take a look at Section 4.3 of the Galaxy chapter, and give them some feedback. I think you'd be good to do this, given that the primary science case that you and Knut identified for the Magellanic Clouds was also astrometry-focused. I pushed the internal review milestone back to June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (eg Sections 3.2 - 3.7 inclusive) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of the pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread; the chapter editors @willclarkson and @akvivas can then follow along. You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thank you!

**Comment by akvivas** [comment]
Thanks @drphilmarshall and @dnidever. We are expecting also comments from Todd Henry on this sub-section. We will merge both Todd and David's comments.

**Comment by dnidever** [comment]
I'm super busy until the beginning of July.  So I'd happy to help then but that doesn't seem to fit into your timescale.  Sorry.

**Comment by drphilmarshall** [comment]
OK, thanks for letting us know, @dnidever . 
@akvivas can you please point Todd at [the first comment in this thread](https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/429#issue-156591560) so he can see what we want the reviewers to think about, as well as the technical details of the science case. Thanks!

**Comment by bethwillman** [comment]
I made some minor text edits and have a few comments, for now, on Section 4.3:

There are a large number of lists in Section 4.3.  These lists alternately use letters, numbers (both Roman and normal), bullets, and combinations thereof.  Please edit for consistency.  In places where there are just 2 items in a list, consider just presenting that information as a short paragraph.

What is the difference between A and B in the Section 4.3.2 list and 1 and 2 in the Section 4.3.3 list?  Perhaps these are not sufficiently different to list them in more than one table, and reference them different.

Section 4.3.3 lists Proper Motion and Parallax Errors at apparent magnitude of 21.0 as metrics, and presents them in Figures.  Section 4.4.4 lists these same quantities as Figures of Merit that build on metrics previously presented.  These subsections should be edited for redundancy and conflicting information.

Table 4.7 doesn't include units.

**Comment by willclarkson** [comment]
Thanks @bethwillman ! I should be able to implement these edits early in the coming week.
