### ISSUE TITLE
Feedback on Transients Chapter 6

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#436]
Hi @MichelleLochner 

Would you mind please taking a look through the Transients chapter 6 and giving some high level feedback to the editors, @fedhere and @ebellm ? The individual sections are out for review already, but it would be great if you could skim the whole thing, and comment briefly on the introduction and further work sections. Does it all hang together well? Is there anything missing? 

Thanks very much for helping with this! :-)

**Comment by MichelleLochner** [comment]
Oops! Sorry I didn't reply. No problem, I'll get feedback to you all by the end of this week. :)

**Comment by MichelleLochner** [comment]
Feedback given in #464!
