### ISSUE TITLE
Feedback on Cosmology Weak Lensing Section 9.3

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#444]
Hi @jasondrhodes    Would you be willing to help out with the internal review of the white paper, please? It would be great if you could take a look at Section 9.3 (weak lensing) of the Cosmology chapter, and give the writing team ( including @jmeyers314 ) some feedback. Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. The goal is for the various science sections of the white paper to be somewhat homogeneous in style and structure - you might find it helpful to compare this section with 9.4 and 9.6, for example. 

You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf), or you can just comment on the current version in the `master` branch (no-one is editing this section right now). 

Thanks very much for helping out with this! :-)

**Comment by jasondrhodes** [comment]
Phil-  Sorry I cannot do it on this time scale.  The annual Euclid Consortium meeting is next week in Lisbon and as US lead for Euclid, this is typically my busiest week of the year. Could I suggest a couple of alternatives:

Tim Eifler
Michael Schneider

Sorry to skirt this responsibly, but I don’t want to commit to something that I don’t have time to do well on the needed timescale.
Jason

**Comment by drphilmarshall** [comment]
Thanks for letting me know, Jason!

@mdschneider, would you be willing and able to review the WL section of the
Observing Strategy white paper? Details further up this issue thread.
Thanks!

**Comment by mdschneider** [comment]
@drphilmarshall Yes, I can review this by next week.

**Comment by drphilmarshall** [comment]
Super! Thank you, Michael :-)

**Comment by mdschneider** [comment]
@StephenRidgway @jmeyers314  
In the WL section of the Observing Strategy document, did you consider adding a discussion of survey depth vs area tradeoffs? @tonytyson wrote a document to the DESC WL list about a year ago describing many of the considerations in this aspect of global survey design that have potentially large impacts on the WL science. And, it seems that considering the total survey area and depth might  drive other metrics such as the DE FOM because the existing shear systematic bias metric is less directly tied to the DOE FOM for such survey-wide design considerations.

Even if the total survey area is considered immutable for the purposes of the Observing Strategy document it might be nice to include a reference to Tony's report on how the overall depth drives WL science.
