### ISSUE TITLE
Feedback on WFIRST Weak Lensing Section 11.2 (and also introduction 11.1)

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#448]
Hi @tonytyson    Would you mind doing a spot of white paper section reviewing, please? It would be great if you could take a look at Sections 11.1 and 11.2 (WFIRST introduction and weak lensing science section) of the WFIRST chapter, and give the writing team ( including @jasondrhodes  ) some feedback. I think you'll enjoy seeing how the synergy with LSST is being explored. 

Our internal review milestone has a due date of June 3rd, so you'll have until the end of next week - although the sooner you can get back to us, the sooner we can get this section finished and ready to submit :-)

What we are looking for at this stage is to address the following questions about each science section:
1. Does the chapter tell a coherent story about the science that is being planned? 
2. Each science section (such as Section 6.3) needs to briefly describe a planned science project, including the primary measurement or discovery that is being sought. How well we expect to achieve this science goal needs to be quantified by a Figure of Merit, which will depend on the details of the observing strategy. Is it clear what the Figure of Merit is, for each science case? There are other, "diagnostic" metrics that help us understand how well the observing strategy will permit the science to be done. Are these defined and explained clearly?  
3. We are working towards calculating Figures of Merit given various simulated observing strategies, captured in the output databases of the `OpSim` operations simulator. Some science sections will contain  metric analyses of these outputs (which are sometimes referred to as "cadences"). What comments do you have on these analyses? In the cases where the Figures of Merit and/or diagnostic metrics have been defined, but not yet calculated, is a plan for future work presented? 
4. We expect each science section to close with a brief discussion of how the observing strategy could be changed to improve the forecast results, and of how this might impact other science cases. Is this provided, and does it make sense?

If you find any of these pieces missing, it'd be great to write an issue asking for them;  likewise, if anything needs cleaning up, explaining better, or otherwise fixing, please do issue those things too. You can also give high level feedback on this issue thread. The goal is for the various science sections of the white paper to be somewhat homogeneous in style and structure - you might find it helpful to compare this section with 9.4 and 9.6, for example. 

You can get the [v0.8 internal review edition PDF file here](https://github.com/LSSTScienceCollaborations/ObservingStrategy/raw/issue/415/draft-for-review/whitepaper/LSST_Observing_Strategy_White_Paper.pdf). 

Thanks very much for helping out with this! :-)

**Comment by tonytyson** [comment]
Phil,
I'd be pleased to do by next week.
Tony

**Comment by drphilmarshall** [comment]
Excellent, thanks Tony.

**Comment by tonytyson** [comment]
Here are comments on section 11.1

It would be good to mention the plate scale in WFIRST imaging:   0.11 arcsec/pixel. 

The H4RG chips have serious neighboring pixel capacitive crosstalk, which correlates noise and signals.   This is a problem when doing WL at 0.1 arcsec/pixel on galaxies with half light radii of ~0.1 arcsec.   Some mention of this systematic should be made.   For WL, WFIRST measures the second intensity moments at a much smaller radius (at higher surface brightness) than LSST.  So these measurements are quite complementary, and could help with the H4RG shear systematics.

The planned WFIRST cadence for tiling the sky during the initial 2 year survey of 2200 sq.deg should be mentioned.  This is important for systematics detection and removal when coordinating with LSST observations.

**Comment by tonytyson** [comment]
Here are comments on section 11.2

In the 3rd sentence of paragraph 2, "help to provide better LSST photozs" should be changed to "help to provide better LSST photozs in the shared area"

The 4th sentence is incorrect and should be removed. "A further benefit ... reduced need for LSST observations at the reddest..."   The LSST planned depth in LSST z and Y observing is very deep, and the thick CCDs have good QE at 1 micron.    I recommend replacing this sentence with "Joint pixel analysis of z and Y band LSST and WFIRST imaging will aid in understanding the systematics."

"in the shared area" should be appended to the last sentence in the 2nd introductory paragraph of section 11.2.

It would be good to mention a shear joint metric in section 11.2.1.   I suggest:
"A detailed metric for shear systematics detection should be developed.  Joint imaging of the same galaxies and stars with LSST and WFIRST in bands from 0.7 - 1.1 micron offers the chance to detect and study PSF and shear systematics.  A plan for validating the metric using simulations should be made."

The first half of the last paragraph is incorrect.
