### ISSUE TITLE
AGN as non-periodic variables?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#45]
Hey @StephenRidgway, @tanguita and @ohadshemmer want to refer to the non-periodic variables section from AGN. I put a flag i there for you to address - what do you think? I guess AGN are both variable and occasionally transient! This issue cropped up in #36, where you can see the commit I made.

**Comment by StephenRidgway** [comment]
Added AGN to the non-periodic variable table, add comment to text, and made other adjustments to change this from a "stellar" section to a more general "non-periodic variable" section.
