### ISSUE TITLE
Feedback on Transients Chapter

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#464]
### Feedback on Transients chapter 6

Here's some suggested changes for the transient chapter for @fedhere and @ebellm!
## General comments
- Overall the chapter hangs together very well. Some work still remains for the editors to smooth over the style, as there are many different voices in the chapter. This is of course true for every chapter in the white paper and will most likely come right after a few iterations. 
- It might be good to bring everything together in a conclusions section after the future work, and link what you've found back to the introduction. Transients is an interesting science case in that there are already some tensions in cadence requirements within the chapter. It would be nice to highlight the recommendations made throughout the chapter (e.g. observing in 3 filters per night, two the same and one different etc.) and if there's any tensions there. 
- Important conclusions and recommendations are often highlighted (which is useful), but quite inconsistently. Sometimes they're in bold, italics or both. Please choose a consistent format.
## Section level comments

**6.1 Introduction**
- The introduction gives a very nice overview and ties in well with the following sections.
- There's some inconsistent capitalisation in this section
- Table 6.1 is a nice overview, but could perhaps benefit from some more numerical information, for example the actual energy ranges of these events, and how common is common really? I realise this particularly might be tricky but you could perhaps list roughly how many of each object has been observed to date to give a non-expert reader an idea for how common these events really are.
- The bullet points in section 6.1.2 could be made much clearer.
- The metrics in 6.1.3 are used extensively throughout but could use a slightly more detailed description here.
- In section 6.1.4, the figures and table could be discussed a bit more, I found it difficult to gain much intuition about how good these metrics are for transient science just by looking at them. 

**6.2 Young transients**
- This section could be broken down into a couple of short subsections
- Figure 6.4 is very important but a bit confusing and could use more description (for example, I don't know what a .Ia is and there are three different SN II on the plot but it's not clear which three objects they are). Please just explain this plot a bit more either in the text or caption.

**6.3 Supernovae**
- Please check spelling and grammar throughout
- I think "The key questions concerning LSST SN science" should be "The main factors _affecting_ LSST SN science". This has a slightly different meaning.
- In the first paragraph on page 137, there are a couple of acronyms you don't really use which makes the paragraph a little harder to read.
- Section 6.3.1 is really interesting. Could you add a little more detail on how you did your simulations? For example, you state you generate several populations, but in what fields do you place the SNe in the OpSim run? What rates do you assume? Do you have a look at the difference between the deep drilling fields and the main survey?
- In figure 6.6, it might be nice to see a residual plot showing the interaction alone, so that we know which part of the light curve is important (I know it's mentioned in words but a visual representation might be useful).
- The actual statistical analysis is a little confusing and could be more clearly explained, especially in the caption of table 6.3, which is one of your main results. It might just be me, but I found the use of σ to describe a fraction of population unnecessarily confusing, given how often it's used to describe the standard deviation of a population. Perhaps just use _f_ to represent the fraction.
- There may be a better way to represent the results than table 6.4, in particular the notes are not very clear. This table should be descriptive enough to stand alone without the text.

**6.4 Gamma-Ray Burst afterglows**
- This section is clear and well-presented.
- Perhaps just specify in the OpSim analysis what you assumed about the distribution of GRBs relative to the OpSim run (i.e. where did you put your GRBs?).

**6.5 Gravitational wave sources**
- Please write a separate subsection for the metric and opsim analysis, as in other sections

**6.6 Future work**
- Sections 6.6.1 and 6.6.3 may be a little long and could be made more concise
- In section 6.6.1, a figure of an example TDE would be useful
- Section 6.6.2 discusses the interesting time scales for CVs. This would be easier to read in bullet points or a table
- The TDE metric is not explained very clearly. There's no reason why this description couldn't be in a subsection as well...
- Please check the spelling and grammar of section 6.6.3
- Section 6.6.3 has a long description of the science case (which could maybe be shortened) but without references when describing models.

**Comment by fedhere** [comment]
addressed most of 6.3, except

Section 6.3.1 is really interesting. Could you add a little more detail on how you did your simulations? For example, you state you generate several populations, but in what fields do you place the SNe in the OpSim run? What rates do you assume? Do you have a look at the difference between the deep drilling fields and the main survey?

I did not have the time to look into it yet, but I should

**Comment by ebellm** [comment]
I addressed the bulk of these comments in the PR; @fedhere, can you review for me?
