### ISSUE TITLE
Feedback on Solar System

### ISSUE THREAD

**Issue by solontoi** [LSSTScienceCollaborations/ObservingStrategy#469]
@rhiannonlynne @davidtrilling

Great work, the section is really coming together, and here are my first pass thoughts and comments on it. 

Also, Lynne, if you want I may be able to help out with the comet section to add some meat to the JFC and LPC discussion. E-mail me (lastname at gmail) if you want some words. I’m in the process of moving right now, but should be able to squeeze in some time for something like that.
## Section three overall comments:

Overall the section looks to be working well, with the sections moving from Science -> Metric -> Figures and Discussion. The largest “top level” comment I have is that some of the sections seem to end abruptly, and may benefit from some sort of final important conclusion or recommendation of how the observing strategy could be implemented or changed to improve this science case (and what it may do to others).

**Other (smaller) section-level comments:**
- The section introduction (3.1) and the subsection introductions (3.X.1) could use references.
- NEA and NEO are switched between. I suggest NEO for the most general population as the only sub-pop really addressed are PHAs.
- Tables in the section (3.1 & 3.2 vs. 3.3) use different formats from each other and other chapters.
- Figures 3.1-3.4 are inline figures, while figures 3.5-3.9 are at the end.
## Specific Section Comments

 **3.2 Linking Solar System Objects**
- First paragraph on discovery “but almost the entire science benefit to planetary astronomy would be lost” might be a touch strong. While there is vast amounts of science expected from LSST as an object discovery platform, there is still great science to be done with present and future known objects.

**3.2.2** 
- H magnitudes are first used here, and I suggest that footnote 3 in section 3.3 be moved to here in order to define them upon their first use. 
- “compared to the total number of objects in the population at that H magnitude” Which models and assumptions are being used to form the basis of the population being sampled? Something similar to how Section 3.3.1 discusses the manner in which PHAs were generated could be added.
- Recommend not using X for the threshold H magnitude at the end of the first paragraph (e.g. H=X) as X was just used to represent number of detections at the start of the paragraph.

**3.2.3**
- Text discusses how completeness is sensitive to how the observations are acquired and directs reader to the figure of merit 3.2. The figure only shows the result of the different cadences and discovery criteria for the NEO population. Do the similar plots of the MBA and TNO populations show the same thing as the NEO, or are there differences due to the why the populations themselves are distributed?

**3.2.4**
- Nice summary putting the section into context of the cadence discussion.

**Figure 3.2**
- The line colors are extremely similar and make it very difficult to assess which line corresponds to which discovery criteria.

**Figure 3.3**
- Which simulation is this from? (assuming minion_1016)

**3.3 Discovery of PHAs**
**3.3.3**
- The discussion could be expanded a bit to include the results of Table 3.3 in context of the goals.
- “the simulation with quads” – is this enigma_1282? Only the caption of Figure 3.1 specifically calls out (in this section) that enigma_1282 specifically runs with acquiring quads in mind.

**Figure 3.4**
- Figure title and legend disagree with each other. Title has plots at year 10, legend indicates each line is at a different “years completed” of the survey sim. 

**Figure 3.5**
- The legend and the caption don’t match here, and the plot seems to be a duplicate of Figure 3.4. Several  **??** appear in the caption as well. 

**3.4 Orbital Accuracy**
**3.4.3**
- Discussion here stands out in only using kilometer size of the bodies instead of H magnitudes  as the rest of Section 3 does. May wish to add them here for consistency
- I believe this analysis is reflected in Figure 3.6, which could be referenced here.

**3.4.4**
- Another possible figure of merit would be positional uncertainty (or average positional uncertainty) vs. time to show the effects of extending the arc in time as the sim progresses.

**3.5 Cometary Activity**
- Second Paragraph: Many of the comments and discussion of color measurement in section 3.7 apply to measuring the dust-to-gas ratio here. Although rotation is much less of an issue one still needs to have a u detection and an r,i, or z detection in order to do this science.
- Third paragraph: Tj > 3 used as a criteria here, need to define the orbital Tisserand parameter being used, or explain in another way, as it has not been introduced or used before here.

**3.5.1**
- Last paragraph moves from a general conversation of outgassing bodies to addressing properties of Active Asteroids only. Suggest that a paragraph, similar to the final one about active asteroids, be added that describes the outgassing period of JFC and LPC as well.

**3.5.2**
- In addition to the two ACTIVITY metrics, the two metrics from 3.2 (DETECTION and COMPLETENESS) would allow addition quantification of cometary populations, and the COLOR metric from 3.7 would play a roll in taxonomy of active asteroids and in determining which active comets we may be able to get a color measurement to allow a gas-to-dust ration to be estimated.
- Question: Assuming the distribution of known MBC is representative of the whole MBC population, do they have different detection and completeness % than the Main Belt as a whole? Is there a metric for assessing just outer belt asteroids (or Hildas)?

**3.5.3**
- Only really deals with MBC, we should have metrics and discussion of JFC and LPC here as well.
- Is there noticeable, or any change in the results in the other simulations? 

**Figure 3.7**
- Text states these plots are from minion_1016 - may wish to include that in the caption. 

**3.5.4**
- The tensions discussed here are less of an issue (I assume) for JFC and LPC, as there are active over significantly larger (potentially all) of their orbit. Short timescale activity that could be detected on these comets during a more frequent observations would be the detection of outbursts and sudden changes to the cometary environment.
- Since the comets themselves need to be detected in order for activity to be determined how do the results of this section change or depend on the choice of detection method as discussed in 3.2? 
- Can MOPS deal with extended sources? This could lead to problems in both finding active comets, and continuing to link observations of the same comet during both the inactive and active portions of its orbit.

**3.6 Measuring Asteroid Light Curves and Rotation Periods
3.6.2**
- “∼100 measurements of an asteroid over ∼years … is sufficient to generate a coarse shape model.” Is this requirement / metric for a single band, or is it ok to include all observations that are better than the stated accuracy?

**Figure 3.8**
- Need to specify which simulation is on the right and on the left respectively.
- Question: the MBA population shows that ~100% have the potential to be inverted above a threshold H magnitude, but what about those missed? 3.2 indicates that the MBA will be observed at about 90% completeness at those H magnitudes.

**3.6.4**
- “further work should be done to determine if this is sufficient, or if observations must occur in a single filter.” Goes along with my comment in 3.6.2, with multiple filters is there a metric available to be able to tell if we are successfully distinguishing between flux changes due to geometry and those due to geology?

**3.7 Measuring Asteroid Colors**
-  Second paragraph: Not only will the asteroid be observed at arbitrary rotational phase, but at a different phase angle as well (less of a problem for more distant objects).

**3.7.1 to end**
- Discussion from here to the end of the section focuses on TNO, and the metrics and figure of merit are on them as well. I think what is happening is that the metric is being informed by TNO studies (as discussed in the first paragraph of 3.7.1) and are being applied to “asteroids” in the more general sense (solar system bodies). I think that this connection could be made a bit clearer, as I was a bit puzzled by it on first reading.

**3.8 Future Work**
- Since the subsection only contains 3.8.1 Deep Drilling, that might be a better title for the subsection.

**Comment by rhiannonlynne** [comment]
Thanks @solontoi - appreciate your comments, and we'll definitely be happy to take you up on your offer to write some words for the comet section.  I am also moving this week! But we'll try to figure out when to squeeze this in -- it sounds like there's some push to make the deadline for submission to the pub board a little later, which would be great for me.

**Comment by rhiannonlynne** [comment]
(regarding text - the easiest way to do that is for you to make a personal fork this repo, make your edits there, then submit a PR back from your personal fork to this repo. make sure to add yourself into the author list if you're not already there ;-))
