### ISSUE TITLE
Should we consider pushing the deadline for submitting to pub board forward?

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#471]
Hi all

I'd personally like a little more time to address internal referee's comments before submitting to the LSST publication board. Is there any reason why we can't push the current milestone (currently 10th of June) forward to, say the end of June? What does everyone else think?

**Comment by StephenRidgway** [comment]
With all due respect for our deadline, I notice that the pub board has received a dozen or more draft SPIE papers for review in the last couple of weeks.

**Comment by willclarkson** [comment]
I agree with @MichelleLochner - we would really benefit from an extension to the end of June from the Galaxy chapter as well. Has there been any movement on this issue? 

Thanks!! cc @akvivas

**Comment by drphilmarshall** [comment]
As you just saw in #483, the answer to your excellent question is a resounding "yes"! I just moved the milestone back to a week after Tucson, as we have some solid cross-chapter editing to do first.
