### ISSUE TITLE
Opsim observing strategy and commissioning strategy sections disappeared!

### ISSUE THREAD

**Issue by rhiannonlynne** [LSSTScienceCollaborations/ObservingStrategy#475]
Looks like 
555e90f46ac86f468dcf07fd2b71ae63e76f0abe
was the commit where the dirty deed was done. 

Is there a reason that these sections were removed? 
It makes the links on the front page README not work (i.e. you cannot "Suggest an opsim run")

@yoachim @drphilmarshall

**Comment by drphilmarshall** [comment]
Looks like an accidental removal of some folders. @yoachim can you please make amends? Thanks!

**Comment by yoachim** [comment]
yikes! That's a merge gone mad!
Looks like my local repo lost all the directories except for whitepaper.  I'll try to git-ninja it back.

**Comment by yoachim** [comment]
Files restored.

Technically it was commit 4b42265f4643946f8238580cb4592dbe5c3bf3da

**Comment by drphilmarshall** [comment]
Thanks @yoachim! :-)
