### ISSUE TITLE
Galaxy / astrometry synergy

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#48]
@dgmonet @willclarkson @akvivas:

Thanks very much for checking in your excellent chapter notes. I know Dave will be at the Bremerton meeting next week - will you, Kathy and Will? I think before we meet up you should set yourselves the homework of reading each others chapters (3, The Galaxy, and 4, Mapping Our Galaxy) closely: both need sections defining, that correspond to individual science projects, and how we arrange all your content between the two chapters needs some thought, and discussion, I think. 

For example: should we be looking at two chapters, or one? If two, is there a more natural division than the one we have at present? You may find it helpful to define your science projects, and then sort them - I don't know.

Many permutations are possible! Hopefully you can figure out an optimal plan together - fee free to make suggestions in reply to this thread, so that others (eg @bethwillman @ivezic) can follow along too. Thanks!

**Comment by akvivas** [comment]
@drphilmarshall yes, that is an important point to discuss. I can see advantages and disadvantages of merging both chapters. If keeping them apart, we need to check there are no repetitions. It would be good idea to discuss this further. I'll arrive in Bremerton Tuesday afternoon.

**Comment by drphilmarshall** [comment]
Great! @dgmonet will arrive Wednesday I believe, but is heavily overbooked.
Not sure about Will. This discussion could be a very good one for one of
the parallel "unconference" sessions at the workshop, I think - let's look
for an opportunity on the schedule! Great if we can coordinate *before* the
Friday plenary, but no great shakes if we can't - we can just say "we're
going to hash this out today in the parallel session".

**Comment by akvivas** [comment]
@willclarkson and I had also discussed if Local Group Science (not currently in any chapter) should be included within 3 The Galaxy. Agree to reserve some time for discussing this in a parallel session. The earliest the better (right after the plenary on Friday?)

**Comment by willclarkson** [comment]
I will get into Bremerton Tuesday afternoon. An unconference session on this issue would be good! 

On the Galaxy/Plane chapter issue: my personal preference at this stage is for two separate chapters; in my own mind the Galaxy chapter deals more with the disposition of exposures within and among the different MW *science cases* (how many exposures, which filters, total time, etc.) while the Plane chapter provides needed detail about how to set up observations to make needed *measurements,* whatever the science case (e.g. crowded-field brightness measurements are presumably equally needed for the LMC/SMC science chapter as they are for the Galaxy).

But I'm very willing to be convinced otherwise!! 

-- Will

**Comment by drphilmarshall** [comment]
I think there will be plenty of material for two galactic chapters! :-)

How to organize the white paper is a question that @StephenRidgway and I
have been going back and forth on for several weeks now. Science topic, or
by type of measurement?

I think we can postpone some of that organisational decision by defining
all the science cases that we're really interested in, assigning each one
to a section, and then seeing what we've got.

BTW when *I* say science case, I mean science projects like "Measurement of
AGN Accretion Disk Sizes" or "Detection of Fast Transients" (which can also
be thought of as "Measurement of the Abundance of Fast Transients"). I'm
talking about investigations that you are effectively proposing (in the
usual astronomical proposal sense) to do with observational data.

Perhaps I should better use the word "inference" in place of
 "measurement", so that we can reserve "measurement" for the things you are
thinking of, Will (crowded field brightness, parallax, etc). This is not
the first time I have caused confusion in this way :-)

So, we could divide galactic science into science projects in the
disk+bulge vs those in the halo, or science projects that need brightness
vs science cases that need positions, or science projects that need long
campaigns vs those that need short ones, and so on - but that division will
be easier once we have a shopping list of science projects that we want to
elevate to the status of `\sections`. Are you suggesting that we separate
"basic measurements"  from "complex inferences" and put them in the two
chapters?

**Comment by drphilmarshall** [comment]
@willclarkson @akvivas As I recall, there was some movement towards merging the astrometry chapter into the Galaxy chapter - certainly @dgmonet seemed to think that astrometry stood out from the other chapters as ot being science-focused, but rather technique-focused. Can you please have a go at merging the two chapters so we can see what they look like as one? Thanks!

**Comment by drphilmarshall** [comment]
Looks like this is getting addressed in #182. Closing here!
