### ISSUE TITLE
Has there been much discussion of spectroscopic follow-up?

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#49]
Does anyone know if there has there been much discussion in the project about spectroscopic follow-up, for example in the original science book or on confluence somewhere? I'm specifically thinking from the supernova perspective where we need some spectroscopic sub-sample, but we'll also need host galaxy redshifts and presumably the photo-z team (who's working on that btw?) also needs a training sample. I'm just wondering what has been discussed/ decided in the past.

**Comment by drphilmarshall** [comment]
For papers on getting galaxy spectroscopic redshifts to support LSST
cosmology I'd say check out the DESC White Paper, and citations to it by
Newman, Cunha et al (who wrote something specific about this after the
white paper came out).

For the LSST cosmological SNe follow-up plan I think our best bet is to
mine the brains of Wood-Vasey (@wmwv) and Jha (@saurabhwjha).

More generally, I'm not sure - maybe @ivezic has some more pointers?

**Comment by wmwv** [comment]
Nothing has been decided.  Exploratory thinking has been done and written down.  More quantitative planning is needed, in coordination with photo-z considerations in general.

There is also the NOAO Spectroscopic White Paper of Matheson et al.:

"Spectroscopy in the Era of LSST"
http://arxiv.org/abs/1311.2496

which includes a section on supernova and the "Snowmass" planning paper of Kim et al.:

"Distance Probes of Dark Energy"
http://arxiv.org/abs/1309.5382
(Section 3.2)
"Report from the "Dark Energy and CMB" working group for the American Physical Society's Division of Particles and Fields long-term planning exercise ("Snowmass"). Accepted for publication in Astroparticle Physics"

But the short answer is, much more thinking needs to be done here.

 - Michael

**Comment by janewman-pitt-edu** [comment]
More specifically for the photo-z side of things, we have a white paper which was put together later than Matheson et al., also for the Snowmass process: http://arxiv.org/abs/1309.5384 / http://adsabs.harvard.edu/abs/2015APh....63...81N .

Best,

Jeff

**Comment by drphilmarshall** [comment]
Thanks very much, @janewman-pitt-edu ! Very glad to have you watching along.

On Fri, Aug 14, 2015 at 1:21 PM, janewman-pitt-edu <notifications@github.com
> wrote:

> More specifically for the photo-z side of things, we have a white paper
> which was put together later than Matheson et al., also for the Snowmass
> process: http://arxiv.org/abs/1309.5384 /
> http://adsabs.harvard.edu/abs/2015APh....63...81N .
>
> Best,
>
> Jeff
>

**Comment by yoachim** [comment]
We do have a relevant metric relating to follow-up that was started at last year's workshop. This lets you compute the number of observatories that would be available to follow up an alert produced from each visit. 
https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/science/Transients/Followup%20Observatories.ipynb

**Comment by MichelleLochner** [comment]
Thanks everyone. That's a very useful metric Peter. Definitely something to fold into future, more complex supernova simulations.
