### ISSUE TITLE
Start Chapter Summaries

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#495]
Chapter Editors: at the editorial meeting, we identified the need for each chapter to present a very short executive summary at its beginning, that draws on each science case's conclusions and makes it easy to see the main issues facing your chapter's science theme. @egawiser suggested that we start writing these sections sooner rather than later, and so use them to identify the science sections that need attention. This issue is therefore related to #494 (getting your section teams going on answering @ivezic 's questions). Please write a short (1 paragraph) executive summary of your chapter's results at the start of your chapter, with placeholder text where necessary, and check your name off the list when you are finished! Thank you :-)
- [ ] Solar System @davidtrilling @rhiannonlynne
- [x] The Galaxy @akvivas @willclarkson
- [ ] Variable Objects @AshishMahabal @lmwalkowicz
- [ ] Eruptive and Explosive Transients @ebellm @fedhere
- [x] AGN @ohadshemmer @tanguita 
- [ ] Cosmology @MichelleLochner @egawiser
- [ ] Special Surveys @drphilmarshall
- [x] Synergy with WFIRST @jasondrhodes

**Comment by jasondrhodes** [comment]
@drphilmarshall let me know if my pull request to do this was successful.

**Comment by willclarkson** [comment]
I have added an executive summary to the beginning of the Milky Way chapter (was pull request #502).

@caprastro , @ctslater, @cbritt4 and @chomiuk , can you do me a favor please and take a look at this summary, and let me know if there's anything missing there about your ongoing efforts that you'd add? 

Thanks!! Will
cc @akvivas

**Comment by drphilmarshall** [comment]
Dear @LSSTScienceCollaborations/observing-strategy-white-paper-editors 

Hope you're all doing well! Quick update on the white paper: Zeljko is working hard to synthesize the answers to his questions that so many sections have now provided, and Beth is working on the "policy" part of the introduction ( #522 ) that will describe how the white paper will function as a communication channel to the project (including who will assess its recommendations, and what would happen after that). 

To help them out, we need to continue working to get the document into shape for submission (there's a number of things that need tidying up). One very useful thing you could all do is compose an abstract-length executive summary for the start of your chapter, that gives the reader  the 30-second version of your chapter's bottom line, based on the 10 answers that each of your sections provided. We can use this issue #495 to track this - please check off your box when you've merged your PR. (Pro-tip: click through to GitHub to see the checklist in the first comment of this thread.) 

What else do you see that needs attention?

Thanks, all!

**Comment by drphilmarshall** [comment]
Looks like the call for chapter summaries got only a few responses; I will leave in the ones that were written, and comment out the placeholder text in the other chapters before closing this out.
