### ISSUE TITLE
Science case conclusions: 4.2 (The Galaxy: Disk populations)

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#497]
Dear WP section 4.2 team (@caprastro, @chomiuk, @cbritt4 and @willclarkson):

To help produce conclusions in a form suitable for tradeoffs to be assessed, the chapter editors have been asked (issue #494) to task our writing teams with providing short (~1-2 sentence) answers to a list of 10 questions produced by @ivezic, about the material in our chapter sections. 

I think this is probably best done through this GitHub system, by entering text straight into this "issue."  Therefore, **please make an attempt at the questions below, by editing this issue text.** (There should be a little crayon-like icon on the far right of the gray title bar for this issue - that's the "edit" button.) 

To make this process easier, Zeljko has provided sample answers to the questions, which you can find in the original issue #494. Below is the original request text from @drphilmarshall, followed by the questions.

Cheers -- Will

"@ivezic would like to know how each science case constrains the observing cadence in several specific ways, and has provided a list of ten questions he would like answered for each science case - his list is below. Not all the questions will be relevant to every science case, but every science case must present its conclusions, and this list of questions is a very good framework to base them on! Some of the questions address relatively simple fine tuning of survey parameters, 
while others offer the possibility of dramatic changes. It is particularly valuable to identify 
constraints or tradeoffs that hold across a broad swath of science programs, and to understand 
which options, if any, are neutral to the science - by having every science case answer these questions, we will be better able to do that.

To illustrate the expected detail level of answers, we also provide an example for each 
question (which attempted to reflect real constraints, but are not binding in any way)."

_**UPDATE (2016-08-05)**_ - initial answers from @cbritt4 -- Thanks Chris!!

**_1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?_**

If only coadded depth is considered, then the choice is straight forward for study of transients in that more sky coverage helps but _coadded_ depth loses important temporal information, but if the more general "number of visits" is what's really being asked about here then it's thornier. It is possible to constrain which approach is better, yes, and FoM have been outlined in the chapter that describe how this could be done. However implementation is still in progress.

**_2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts)._**

The frequency of sampling is critical for the science cases in 4.2, while the sky coverage is merely important. A FoM to quantify the relative importance of each has been outlined in the chapter, but I haven’t yet produced these figures.

**_3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise._**

This is very line of sight dependent close to the Plane, especially in u band. At low Galactic latitudes, u band is unlikely to be of value at any reasonable exposure time because of high reddening.  At redder bands in low extinction areas, below i=24 or so is no longer as valuable because it starts to punch through the Galactic Bulge for dwarf novae and going deeper no longer adds as many new systems. That’s still very dependent on line of sight extinction, though, and isn’t true at all in the central 2 degrees of Galactic latitude. My sense is that more frequent visits are more important than depth of a given exposure, but this is something that should be quantified, for DNe at least, if the OpSims with this tension exist.   

**_4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)?_**

Yes, the above questions were all answered specifically in regards to the Galactic Plane. The science in 4.2 isn’t really doable outside the Plane.

**_5) Can you place constraints on the fractions of observing time allocated to each band?_**

Having 2 red filters would help tremendously in breaking degeneracies between distance and luminosity since the spectrum of the outbursts discussed here is typically vega-like, so any r-i should be the result largely of interstellar reddening. Much of the population science can be done without this information, though.

**_6) Can you place constraints on the cadence for deep drilling fields?_**

For the transient science in 4.2, any deep drilling cadence will be sufficient. To recover ellipsoidal variables at short periods, however, the shortest gap in observations should be ~20 minutes. Not all observations need to be so close together, but it’s important to have at least a few baselines that short in order to reliably recover periods between 80 minutes and 2 hours, where the majority of CVs (and potentially a new population of X-ray faint short period XRB outbursts) should be.

**_7) Assuming two visits per night, should they be obtained in the same band or not?_**

Pro colors: having color information can help distinguish object class and the timescale of the variables discussed in much of this section is days rather than hours. Pro same filter: for orbital period recovery, especially of ellipsoidal variations of counterparts to eRosita sources, having observations within the same night is crucial. If the color variation with phase is smaller than the orbital variations, then having the colors could give the best of both worlds. 

**_8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area?_**

10 years on a field would allow accessing the low duty cycle (and therefore low X-ray luminosity) CVs, which is poorly understood and is probably where most of the remaining gap between population models and observations of dwarf novae lies. My sense is that baseline is also more important than high cadence in discovering Galactic Novae, though Jay knows better than I do.  I think doing 10 years on a single field still enables these science cases, especially since a well chosen field would have a disproportionately high source density (e.g. l=0, b=3).  The same is also true for a small area, high cadence survey for the periodic variables rather than the transients.

**_9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?_**

I think the difference imaging will make any conditions useful to some extent for the transient cases in the Plane, so I wouldn’t put any constraints on observing conditions.

**_10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?_**

I think the science cases in 4.2 can tolerate variable depth limits without suffering much.
## 

Finally, if your science would benefit from a cadence methodology not covered by these questions, 
please enter a description of this methodology at http://ls.st/yqq

**Comment by willclarkson** [comment]
@cbritt4 has provided some initial answers -- thanks Chris!! All - feel free to edit.

**Comment by willclarkson** [comment]
Update to all: if you're finding you cannot edit the issue with your response, you should be able to upload your answers as a comment to this thread - or you could just email me directly. For some reason GitHub is only making a small subset of the authors available to actually assign this issue. Thanks all! Will

**Comment by willclarkson** [comment]
I have synthesized this into a stab at the 10 questions in the summary for Section 4.2. This pull request has been merged with the main branch so should be visible to all readers (answers are in blue font).

**Comment by cbritt4** [comment]
Thanks Will! I’m still reading over it, it looks good!

**Comment by willclarkson** [comment]
I'm closing this issue for now - comments are of course still welcome!
