### ISSUE TITLE
Science case conclusions: 4.3 (The Galaxy:Astrometry)

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#498]
Dear WP section 4.3 team (@dgmonet, @DanaCD, @jgizis, @caprastro, Mike Liu, @yoachim and  @willclarkson):

To help produce conclusions in a form suitable for tradeoffs to be assessed, the chapter editors have been asked (issue #494) to task our writing teams with providing short (~1-2 sentence) answers to a list of 10 questions produced by @ivezic, about the material in our chapter sections.

I think this is probably best done through this GitHub system, by entering text straight into this "issue." Therefore, **please make an attempt at the questions below, by editing this issue text.** (There should be a little crayon-like icon on the far right of the blue title bar for this issue - that's the "edit" button.)

To make this process easier, Zeljko has provided sample answers to the questions, which you can find in the original issue #494. Below is the original request text from @drphilmarshall, followed by the questions.

Cheers -- Will

"@ivezic would like to know how each science case constrains the observing cadence in several specific ways, and has provided a list of ten questions he would like answered for each science case - his list is below. Not all the questions will be relevant to every science case, but every science case must present its conclusions, and this list of questions is a very good framework to base them on! Some of the questions address relatively simple fine tuning of survey parameters, while others offer the possibility of dramatic changes. It is particularly valuable to identify constraints or tradeoffs that hold across a broad swath of science programs, and to understand which options, if any, are neutral to the science - by having every science case answer these questions, we will be better able to do that.

To illustrate the expected detail level of answers, we also provide an example for each 
question (which attempted to reflect real constraints, but are not binding in any way)."

**_1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?_**

Our answer comes here:

**_2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts)._**

Our answer:

**_3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise._**

Our answer:

**_4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)?_**

Our answer:

**_5) Can you place constraints on the fractions of observing time allocated to each band?_**

Our answer:

**_6) Can you place constraints on the cadence for deep drilling fields?_**

Our answer:

**_7) Assuming two visits per night, should they be obtained in the same band or not?_**

Our answer:

**_8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area?_**

Our answer:

**_9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?_**

Our answer:

**_10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?_**

Our answer:

**_Finally, if your science would benefit from a cadence methodology not covered by these questions, 
please enter a description of this methodology at http://ls.st/yqq_**

**Comment by willclarkson** [comment]
Update to all: if you're finding you cannot edit the issue with your response, you should be able to upload your answers as a comment to this thread - or you could just email me directly. For some reason GitHub is only making a small subset of the authors available to actually assign this issue. Thanks all! Will

**Comment by willclarkson** [comment]
Update: I have input answers to these 10 questions, in MW_Astrometry.tex . Astrometry co-authors will shortly be contacted to request comments and edits.

**Comment by willclarkson** [comment]
Update - comments from co-authors are coming in... Expect updates to WP chapter 4.3 conclusions by this evening (Sat Jan 28th 2017)...

**Comment by willclarkson** [comment]
Update 3:30pm Mon Jan 30th - Dana's input incorporated into conclusions Answer 1.

**Comment by drphilmarshall** [comment]
Excellent! I see it all, Will. Feel free to close out once you have changed
the text color back to black! Thanks for your efforts on this.

**Comment by willclarkson** [comment]
I am closing this issue for now. Co-authors, please feel free to provide comments at any time.
