### ISSUE TITLE
Use gh-pages to make workshop website?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#5]
Look what a nice job Jake VdP did with gh-pages for the [Astro Hack Week](http://astrohackweek.github.io/) last September. We could even pinch his background image.

**Comment by ivezic** [comment]
Yes, very nice and yes, we should steal it. And he will not even know - he just announced
that he's taking two months long parental leave. 
So, did you steal such pages before? If I were to do it, I'd have to start from scratch...

**Comment by drphilmarshall** [comment]
I have not, but the source for [Jake's AstroHackWeek website](http://astrohackweek.github.io/) is all checked in [here](https://github.com/AstroHackWeek/astrohackweek.github.io). It looks as though Jake's site is not running on gh-pages, though. What we could try is starting a github pages branch, and then just stealing Jake's html and css, that he generated with Nikola. It looks fairly hackable, see the [index.html](https://github.com/AstroHackWeek/astrohackweek.github.io/blob/master/index.html) for example. I think the main reason Jake built it all with Nikola was to get the blog functionality. We don't necessarily need that, so could just pinch the static parts. In principle.

**Comment by drphilmarshall** [comment]
OK, we now have a [basic website.](http://lsstsciencecollaborations.github.io/ObservingStrategy/) Hopefully, hacking in Jake's nicer stylesheet, images etc, won't be too hard. Someone should issue themselves with that :-)

**Comment by ivezic** [comment]
I just talked to Suzanne Jacoby about having this website on our own. 
She's ok with it and they will simply add a link to it from the AHM2015
webpage managed by the Project. 

Phil, I am reassigning this issue back to you since you have already singled
yourself out by your masterful command of web art, infectious energy,
and just being a super LSST champ all around :)  Do you think you can
accept this burden?

**Comment by bethwillman** [comment]
Phil *is* a super LSST champ.

On Mon, Mar 9, 2015 at 3:17 PM, Zeljko Ivezic <notifications@github.com>
wrote:

> Reopened #5
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/5#event-248790104>
> .
>



-- 
Beth Willman
Associate Professor of Astronomy
Chair, Physics and Astronomy Department
Haverford College
610-896-1201

**Comment by drphilmarshall** [comment]
Hah! Flattery will get you everywhere. OK, challenge accepted - will close this out and issue myself with a bunch of webwork.
