### ISSUE TITLE
Author contributions

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#503]
@jhrlsst has pointed out that for the supernova section (and probably many other sections too), we have received contributions of many different forms (from advice, to help with OpSim, to code etc.) from several different people that we'd like to correctly acknowledge. 

We could include them in the author list and use the standard paper approach of letting author order dictate amount of contribution. However @jhrlsst suggests splitting into two lists of lead authors and contributing authors (similar to how the chapters are already split into editors and contributing authors). What do people think of using a split like this at the section level?

**Comment by drphilmarshall** [comment]
Hi Michelle - I think either way of splitting section co-authors could work. I'd say that the lead author(s) of each team should make a suggestion, and then if there are any disputes, the chapter editors should be able to resolve them. I would say that section author lists should be short, though: try and capture direct contributions only (eg new text, new ideas, new implemented metrics etc). Sound good?
