### ISSUE TITLE
Science Case Conclusions: 9.2 (Cosmology: Large scale structure)

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#504]
Dear WP section 9.2 team (@HumnaAwan,  @egawiser, @PeterKurczynski, @rhiannonlynne ):

Shamelessly copying Will Clarkson's idea and post, I'm issuing the section authors in exactly the same way to collect responses to this. Once we have responses from each section, @egawiser and I can collate them into a chapter summary.

To help produce conclusions in a form suitable for tradeoffs to be assessed, the chapter editors have been asked (issue #494 ) to task our writing teams with providing short (~1-2 sentence) answers to a list of 10 questions produced by @ivezic, about the material in our chapter sections.

I think this is probably best done through this GitHub system, by entering text straight into this "issue." Therefore, please make an attempt at the questions below, by editing this issue text. (There should be a little crayon-like icon on the far right of the blue title bar for this issue - that's the "edit" button.)

To make this process easier, Zeljko has provided sample answers to the questions, which you can find in the original issue #494. Below is the original request text from @drphilmarshall, followed by the questions.

Cheers -- Michelle

"@ivezic would like to know how each science case constrains the observing cadence in several specific ways, and has provided a list of ten questions he would like answered for each science case - his list is below. Not all the questions will be relevant to every science case, but every science case must present its conclusions, and this list of questions is a very good framework to base them on! Some of the questions address relatively simple fine tuning of survey parameters, while others offer the possibility of dramatic changes. It is particularly valuable to identify constraints or tradeoffs that hold across a broad swath of science programs, and to understand which options, if any, are neutral to the science - by having every science case answer these questions, we will be better able to do that.

To illustrate the expected detail level of answers, we also provide an example for each 
question (which attempted to reflect real constraints, but are not binding in any way)."

**1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?**

Our answer comes here:

**2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts).**

Our answer:

**3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise.**

Our answer:

**4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)?**

Our answer:

**5) Can you place constraints on the fractions of observing time allocated to each band?**

Our answer:

**6) Can you place constraints on the cadence for deep drilling fields?**

Our answer:

**7) Assuming two visits per night, should they be obtained in the same band or not?**

Our answer:

**8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area?**

Our answer:

**9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?**

Our answer:

**10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?**

Our answer:

Finally, if your science would benefit from a cadence methodology not covered by these questions, 
please enter a description of this methodology at http://ls.st/yqq

**Comment by rhiannonlynne** [comment]
Best not to assign this to me. I have another chapter I'm more responsible
for, plus I'm on maternity leave. Plus, the large scale structure thing is
more directly @egawiser's baby.

**Comment by drphilmarshall** [comment]
@MichelleLochner I'm going to close this issue and the WL one because their conclusions are done. You and @egawiser can always open new issues if you need clarification when composing your chapter summary. Thanks!
