### ISSUE TITLE
Science Case Conclusions: 9.3 (Cosmology: Weak Lensing)

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#505]
Dear WP section 9.3 team (@jmeyers314,  @tonytyson @StephenRidgway):

Shamelessly copying Will Clarkson's idea and post, I'm issuing the section authors in exactly the same way to collect responses to this. Once we have responses from each section, @egawiser and I can collate them into a chapter summary.

To help produce conclusions in a form suitable for tradeoffs to be assessed, the chapter editors have been asked (issue #494 ) to task our writing teams with providing short (~1-2 sentence) answers to a list of 10 questions produced by @ivezic, about the material in our chapter sections.

I think this is probably best done through this GitHub system, by entering text straight into this "issue." Therefore, please make an attempt at the questions below, by editing this issue text. (There should be a little crayon-like icon on the far right of the blue title bar for this issue - that's the "edit" button.)

To make this process easier, Zeljko has provided sample answers to the questions, which you can find in the original issue #494. Below is the original request text from @drphilmarshall, followed by the questions.

Cheers -- Michelle

"@ivezic would like to know how each science case constrains the observing cadence in several specific ways, and has provided a list of ten questions he would like answered for each science case - his list is below. Not all the questions will be relevant to every science case, but every science case must present its conclusions, and this list of questions is a very good framework to base them on! Some of the questions address relatively simple fine tuning of survey parameters, while others offer the possibility of dramatic changes. It is particularly valuable to identify constraints or tradeoffs that hold across a broad swath of science programs, and to understand which options, if any, are neutral to the science - by having every science case answer these questions, we will be better able to do that.

To illustrate the expected detail level of answers, we also provide an example for each 
question (which attempted to reflect real constraints, but are not binding in any way)."

**1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)?**

Our answer comes here: On the scale of thousands of sq.deg, the WL signal and control of systematics is enhanced by deeper (larger cosmological volume) rather than wider surveying. These considerations led to the 18,000 sq.deg per ten years baseline.

**2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts).**

Our answer: WL is generally agnostic on this issue.  Total good IQ x depth is most important, and this might benefit from rolling cadences if the mean airmass is lower, resulting in a higher IQ.

**3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise.**

Our answer: 30-sec or longer u band exposures will help S/N.

**4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)?**

Our answer: WL ugrizy imaging must avoid low Galactic latitudes due to stellar crowding, bright stars, and dust.  Data at low latitudes will not be used for WL. 

**5) Can you place constraints on the fractions of observing time allocated to each band?**

Our answer: This depends on the relative system throughput vs wavelength. For the case of high u band QE CCDs, approximately u10%, g10%, r22%, i22%, z18%, y18%. The comes from 80, 80, 184, 184, 160, 160  ugrizy 30-sec visits per 9.6 sq.deg fields over 18,000 sq.deg per ten years -- from the SRD, driven by required low surface brightness shear measurement and the needed S/N for photo-z for the gold sample of galaxies.  The longer integrations at longer wavelengths is due to the red color of the sky background.

**6) Can you place constraints on the cadence for deep drilling fields?**

Our answer: It will be helpful if the individual exposure times in all bands are similar to the main survey. A long series of exposures in each filter would be good.  Dithering in x-y-theta between exposures using “intelligent dithering” is needed in order to detect low level systematics and to help calibrate the main survey galaxy blending.  Emphasis on excellent seeing is important. Spreading the DD observing over many half nights, maximizing the HA coverage, will be needed.

**7) Assuming two visits per night, should they be obtained in the same band or not?**

Our answer: Not necessarily.   In fact, occasional back-to back gr exposures help calibrate systematics from chromatic refraction.

**8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area?**

Our answer: Yes, ugrizy full depth over at least 1000 sq.deg.   Suppression of WL systematics will depend on early detection of issues.  This, and the development and validation of MultiFit pipline, shear measurement algorithms, cosmological analysis algorithms, and associated covariances will rely on early deep surveying of a few thousand square degrees. This also benefits co-analysis with WFIRST or Euclid data.

**9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?**

Our answer:  WL benefits significantly from good uniform seeing, IQ, and depth in the r and I bands. For example, imaging in the r and i bands in seeing worse than 1 arcsec is not productive, and revisits to that field should await better seeing.  The associated photo-z relies on uniform depth spatially. This means low airmass.

**10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?**

Our answer: Yes. Uniform residual shear is even more important than depth. Dithering in x-y-theta between exposures using “intelligent dithering” is needed in order to detect low level systematics and to help calibrate the main survey galaxy blending. In intelligent dithering the scheduler is aware of the past history of the IQ in that field in the two bands used for WL shear (nominally r and i). The algorithm tries to uniformly sample camera angles relative to north with uniformly good IQ.  Rotation angles of previous poor IQ visits need to be repeated.

Finally, if your science would benefit from a cadence methodology not covered by these questions, 
please enter a description of this methodology at http://ls.st/yqq

**Comment by tonytyson** [comment]
Michelle,
You need to add me as an assignee so I can edit.
Tony Tyson

**Comment by drphilmarshall** [comment]
Hi @tonytyson - I just sent you an invitation to the "Editors" team, who have write access to this repository. By default, people make contributions by "forking" the repository, pushing changes to this fork, and then submitting a "pull request" from this fork to the base repository. The nice thing about this way of working is that it shows your colleagues very cleanly what you have done. In the interests of time I'm happy to give you direct write access, but if we get a few minutes in Tucson I'll show you how to make pull requests from your own fork. In the meantime, don't forget to pull before you push! Thanks for taking on Zeljko's questions :-) 

@jmeyers314  you'll want to keep an eye on this issue so you can see what Tony has written. Thanks!

**Comment by MichelleLochner** [comment]
@drphilmarshall I think Tony was referring to being able to edit the issue itself. Sorry @tonytyson, I thought I had assigned you but I obviously missed you. Are you able to edit it now?

**Comment by tonytyson** [comment]
Yes I can edit now and will insert our WL 10 replies tonight.
-Tony

**Comment by drphilmarshall** [comment]
Great, pleased to hear it.

In case it wasn't clear, the answers to your questions will make excellent
content for the conclusions section of your science case latex file!

**Comment by tonytyson** [comment]
Good idea.

**Comment by tonytyson** [comment]
just updated comment with our 10 replies.

**Comment by tonytyson** [comment]
i'm now going to edit the wl.tex to add a conclusions section
