### ISSUE TITLE
Cadence exploration writeup

### ISSUE THREAD

**Issue by ivezic** [LSSTScienceCollaborations/ObservingStrategy#51]
Dear all,
a preliminary report on 2015 LSST cadence exploration is available as
http://www.astro.washington.edu/users/ivezic/lsst/cadexp2.pdf

I think it would help you to see prior to the workshop what kind of analysis we 
can do with OpSim and MAF. Eventually, most of that material will be ported to 
our white paper, and Phil encouraged me to do so before Bremerton, but I simply 
run out of time. 

Looking forward to seeing you all there!  
     Cheers, Zeljko

**Comment by drphilmarshall** [comment]
Thanks @ivezic ! If you `git add` the latex and figures, I can help merge them into the white paper.
