### ISSUE TITLE
WFIRST microlensing questions

### ISSUE THREAD

**Issue by jasondrhodes** [LSSTScienceCollaborations/ObservingStrategy#512]
@drphilmarshall  I have asked @mtpenny and David Bennett to do the following:

-update the WFIRST microlensing section with a new survey strategy based on simulations being run by @mtpenny right now

-include answers to the questions Zeljko asked.  

-push the latex changes by next week, with the caveat that the final numbers may changed as the simulations are finished and analyzed. 

Hope this is ok.

**Comment by drphilmarshall** [comment]
Thanks Jason, that sounds good to me. @mtpenny you can see Jason's own answers to Zeljko's questions in his WFIRST HLS section - the project are looking for actionable conclusions, and the thought is that these questions might draw these out. Thanks for helping with this!

**Comment by mtpenny** [comment]
I have created a pull request with the answers to Zeljko's questions that Dave Bennett wrote, and @rpoleski and I modified slightly. I have not updated the text with the new survey strategy, so this shouldn't be resolved yet.

**Comment by drphilmarshall** [comment]
I'm going to close this out - your answers looked in pretty good shape to me. @ivezic and the OpSim team can always issue you with clarifying questions as they look through them. Thanks! :-)
