### ISSUE TITLE
WFIRST SN questions

### ISSUE THREAD

**Issue by jasondrhodes** [LSSTScienceCollaborations/ObservingStrategy#513]
@drphilmarshall I have asked @rubind to provide me with text for the WFIRST SN section based on the questions Zeljko asked recently.  I'll incorporate that text when I get it and update the WFIRST section.

**Comment by jasondrhodes** [comment]
@drphilmarshall I just got the following from @rubind .  Is there time to include this in the white paper?

1) Can you place constraints on the tradeoff between the sky coverage and coadded depth?
For example, should we maximize the sky coverage (to ~30,000 sq. deg., as e.g. Pan-STARRS)
or the number of detected galaxies (the current baseline with 18,000 sq. deg.)? 
We will only get good LSST light curves in the DDFs, so to good approximation both strategies would be fine. There are secondary considerations (such as constraining extinction in the Milky Way and probing isotropy) that may prefer a larger number of square degrees, but I wouldn’t advocate making the weak-lensing science worse (by going to 30,000 rather than 18,000) without a strong quantitative argument.

2) Can you place constraints on the trade between uniformity of sampling and frequency of 
sampling? For example, a rolling cadence can provide enhanced sample rates over part or all 
of the survey part of the time, at the cost of reduced sample rate the rest of the time (while 
maintaining the nominal total visit counts).
For the main survey, I don’t think there would be much preference for the SN Ia program.

3) Can you place constraints on the tradeoff between the single-visit depth and the number 
of visits? Especially in the u band, where longer exposures would minimize the impact of the 
readout noise.
For the main survey, I don’t think there would be much preference for the SN Ia program. SNe Ia evolve over a period of weeks in the rest-frame; as long as there is one observation at least every few days (per filter) in the DDFs, the SN Ia science would not be harmed by having longer exposures and less-frequent visits.

4) Can you place constraints on the Galactic plane coverage (spatial coverage, temporal 
sampling, visits per band)?
For the main survey, I don’t think there would be much preference for the SN Ia program.

5) Can you place constraints on the fractions of observing time allocated to each band?
For the main survey, I don’t think there would be much preference for the SN Ia program. For the DDFs, constraints can be placed on the observing time allocation, but I have not done any simulations of this. Based on experience with other programs, the reddest filters (z and Y) should receive the most time.

6) Can you place constraints on the cadence for deep drilling fields?
To obtain good light curves, we would want at least one observation every few days per filter. This is also a requirement for photometric typing to obtain reasonable purity if WFIRST spectroscopy is to be triggered. NB: of all the questions, this one is the most important to the program.

7) Assuming two visits per night, should they be obtained in the same band or not?
For the main survey, I don’t think there would be much preference for the SN Ia program. As long as there is one observation at least every few days (per filter) in the DDFs, there is also no preference.

8) Would your science benefit from a special cadence prescription during commissioning or 
early in the survey, such as: acquiring a full 10-yr count of visits for a small area (either in all or in selected bands); a greatly enhanced cadence for a small area?
For the main survey, I don’t think there would be much preference for the SN Ia program. For the DDFs, such observations might help provide deep SN-free (template) images or host-galaxy photometric redshifts. I have not made a quantitative study of this question.

9) Do you have constraints for sampling of observing conditions (e.g. seeing, dark sky,
airmass), possibly as a function of band, etc.?
As long as the DDF observations reach the targeted depths, there is no benefit to the SN Ia science from having specific observing conditions.

10) Do you have science drivers that would require real-time exposure time optimization 
to obtain nearly constant single-visit limiting depth?
We do not currently know of any benefit to the SN Ia science from doing this.

**Comment by drphilmarshall** [comment]
Excellent! If one of you could paste this content into a conclusions
subsection of the WFIRST SN section that would be perfect. Thanks!

**Comment by jasondrhodes** [comment]
Thanks Phil.  David, could you paste those into the Sn section please?

Jason

**Comment by drphilmarshall** [comment]
Hi @rubind @jasondrhodes - It looks like you did not enter these conclusions into the `WFIRST_supernovae.tex` file before Zeljko's deadline a few weeks ago, so his overall conclusions (now in Chapter 12) don't refer to them. However, his conclusions are strongly influenced by the needs of the other supernova groups, so I don't think they would have been changed much anyway! So, I'm going to close this out; for version 2 of the white paper you may have some more quantitative  answers in any case. Thanks!
