### ISSUE TITLE
New OpSim Reference Run, minion_1016

### ISSUE THREAD

**Issue by cathypetry** [LSSTScienceCollaborations/ObservingStrategy#516]
A new Operations Simulator (OpSim) Reference Simulated Survey, minion_1016, has been approved and placed under change control.  This simulated survey should be used as the baseline cadence instead of enigma _1189 or other older simulations. More information can be found on the [LSST website](https://www.lsst.org/scientists/simulations/opsim/opsim-survey-data).

**Comment by drphilmarshall** [comment]
Thanks very much, Cathy! In the Tucson workshop unconference session last
Thursday the group decided that we *should* present results for at least
`minion_1016` in whichever sections MAF is employed - I'll be issuing this
in various places over the coming week, as required. I see that the page
you linked to contains a path to the OpSim 3.3.5 benchmark surveys:

https://www.lsst.org/scientists/simulations/opsim/opsim-v335-benchmark-surveys

This is great for people wanting to test against the other "Tier 1" runs.
Will you also add the Tier 2 outputs, including the "normal galactic
plane" run `astro_lsst_01_1004` as well as the initial "Swiss Cheese"
rolling cadence experiments? It would be great if Tier 1 and Tier 2 were
presented consistently between the white paper and the LSST online
documentation, so I'd suggest two html tables on this same v3.3.5 webpage.
I'll make sure that Chapter 2 of the WP points at the above link, so people
can find it easily.

Thank you!!

**Comment by drphilmarshall** [comment]
PS. @cathypetry see #524 for some clamoring for the Tier 2 run data :-) Thank you!

**Comment by rhiannonlynne** [comment]
We should not use the old Swiss cheese runs. Please see comment in PR 524.

**Comment by drphilmarshall** [comment]
Looks like almost all analyses use minion_1016 over enigma_1189 now - good enough.
