### ISSUE TITLE
Leave out rolling cadence sims from the first version of the whitepaper?

### ISSUE THREAD

**Issue by ebellm** [LSSTScienceCollaborations/ObservingStrategy#524]
I know the sims team has produced some early "swiss-cheese" rolling cadence OpSim runs.  However, they don't yet appear at https://www.lsst.org/scientists/simulations/opsim/opsim-survey-data  

@ivezic, are these first rolling cadence sims blessed by the project for evaluation in the whitepaper?  I do see some initial discussion of them in Chapter 2.5, but it's not clear how they are configured or what the differences between them are.

**Comment by drphilmarshall** [comment]
Hi @ebellm - I've asked for the Tier 2 OpSim runs to be posted on the web for us, in person last week and in #516 just now, so please keep an eye on both threads. I'll point Cathy Petry at this request of yours too, as evidence! Thanks :-)

**Comment by rhiannonlynne** [comment]
The original Swiss cheese experiments should not be used. They have inconsistent sky brightness, seeing and m5 values with newer runs (and even different schema). We could try to replicate them, or replace. This is an issue for @kemcook to look at.

**Comment by ebellm** [comment]
Thanks, @rhiannonlynne!  @drphilmarshall, maybe we let this slide until "real" rolling cadences are available in Opsim v4 (and hence v2 of the whitepaper)?

**Comment by drphilmarshall** [comment]
Sounds like a good idea! I have not seen many people try to use them
anyway. The brief analysis in Ch 2 can stay but well need to put a caveat
in the text about using the db's.

**Comment by ebellm** [comment]
Agreed.  I think along with the project-contributed timeline we should include a corresponding  plan for the whitepaper, so readers of v1 know to expect rolling cadence evaluation in v2.

Closing out this issue for now.

**Comment by jhrlsst** [comment]
I am not sure if "Section 2.5 Temporarily Denser Time Sampling: Rolling Cadence" belongs there or not. This section doesn't present opsim runs as the rest of Section 2 presents opsim run.
This is more likely conclusion of our white paper, but it was written without referring each section (for example, of Section 2.5.4 which did not cite the SN cosmology Section 9.5).  As @ebelim, @drphilmarshall have discussed above, this may belong to v2 white paper. If they are needed in v1, I suggest to move them to the end of white paper.

**Comment by ivezic** [comment]
I agree that we should comment out that text until v2 - initially, we hoped
that we'd have rolling cadence runs too for v1, but we don't.

**Comment by drphilmarshall** [comment]
Sounds good to me. Re-opening and renaming this issue, and self-assigning the editing work. Good catch, @jhrlsst !

**Comment by StephenRidgway** [comment]
As the possible author of that section, I would say that it was written before 90% of the white paper, and before it was clear that there would be no rolling cadence simulations for a year.  I agree that this section mith be deleted in favor of having rolling cadence a recommendation of the white paper, or might be recast as part of the conclusion.

**Comment by cathypetry** [comment]
Hi @drphilmarshall - I just re-read some of these threads and I would like to verify that you have access to the runs that you need.  I did match the data access page on lsst.org to the runs listed in Chapter 2, but if this has changed or if you need updated runs could you please reiterate that here?  Also, I was not clear what you meant by "Tier 2" runs. Thanks!

**Comment by drphilmarshall** [comment]
Returning to this after some time: Many science sections refer to "rolling cadence" so I think we do actually need an introduction to the concept in chapter 2. No-one actually ever used the experimental (and flawed!) "swiss cheese" opsim runs though, so I commented out this part of the section in chapter 2. PR is on the way.

**Comment by StephenRidgway** [comment]
I see that an introduction to rolling cadences still exists in chapter 2.  Could you be more specific about what is missing?

**Comment by drphilmarshall** [comment]
Hi Steve! Not sure what you mean by "missing" - I commented out the
description of the swiss cheese runs, but left the general introduction to
rolling cadence so that all the science sections (and the conclusions) can
refer to the term. For me, the question is: does the white paper read OK
how it is now, with the shortened RC section in chapter 2? I think so.

**Comment by StephenRidgway** [comment]
I agree, sorry for misreading you rcomment.

**Comment by drphilmarshall** [comment]
Great! Thanks for taking a look. I think your tradeoffs discussion works
well after Zeljko's conclusions too - thanks for producing that :-)

**Comment by ivezic** [comment]
Agreed - I think Steve's pieces are very thoughtful!
