### ISSUE TITLE
Broken link on workshop schedule

### ISSUE THREAD

**Issue by StephenRidgway** [LSSTScienceCollaborations/ObservingStrategy#53]
Hi, there is a broken link "Notes on the Operations Simulator development plan can be found here." on the workshop page http://lsstsciencecollaborations.github.io/ObservingStrategy/

**Comment by drphilmarshall** [comment]
Fixed this in https://github.com/LSSTScienceCollaborations/ObservingStrategy/commit/9ec9f6c7a1cc0dcd02efe742ee5c2f1bb20d938c by commenting out the offending line...
