### ISSUE TITLE
Section 8.4 AGN Size & Structure needs reviewing

### ISSUE THREAD

**Issue by AstroVPK** [LSSTScienceCollaborations/ObservingStrategy#536]
Hey @drphilmarshall ,
     Can you please have someone review Section 8.4 AGN Size & Structure?

**Comment by tanguita** [comment]
Hi @AstroVPK,

This has been reviewed by George Chartas. I have already input his comments.

**Comment by drphilmarshall** [comment]
Great, thanks @tanguita !
