### ISSUE TITLE
guidelines for authorship

### ISSUE THREAD

**Issue by reneehlozek** [LSSTScienceCollaborations/ObservingStrategy#574]
Just a note that it states that the guidelines for getting involved are in the preface, but that only contains a link to sec:guidelines, rather than the info directly (or rather, the preface linked from the readme seems to end before the guideline section itself).

**Comment by drphilmarshall** [comment]
Yep, some clean-up required here. Thanks for issuing! We could use a lot more help like this, fixing up the details before we submit.
