### ISSUE TITLE
Everyone: make sure our author lists are complete

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#575]
Hi @LSSTScienceCollaborations/observing-strategy-white-paper-editors @LSSTScienceCollaborations/observing-strategy-white-paper-contributors 

There are a few people who have contributed to the science sections that are not currently listed as authors, because they have not been using GitHub but instead have been providing valuable input by email etc. If there are people who need to be accredited for their work in your section's author list please make sure that they are listed, both in the section latex file and also in [`authors.tex`](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/whitepaper/authors.tex). I suggest that the first author of each section take this on as a responsibility, but all of you can help out by letting your section lead know who needs to be accredited. Thanks everyone - it's very important that people are not left out, and now is the time to make sure they are not! When the paper hits the archive it's author list *must* be complete.

**Comment by drphilmarshall** [comment]
I know the SN cosmology section author list was found to be incomplete two weeks ago - is it now fixed, @rbiswas4 ?  The section header lists:

> Lead authors: Jeonghee Rho, Rahul Biswas, Michelle Lochner
> Contributing authors: Pierre Antilogus, Seth Digel, Ryan Foley, Eric Gawiser, Ren ́ee Hlozek, Zˇeljko Ivezi ́c, Saurabh Jha, Richard Kessler, Alex Kim, Ofer Lahav, Alex Malz, Jason McEwen, Jeffrey Newman, Hiranya Peiris, Kara Ponder, Robert Schuhmann, Christopher Stubbs, Michael Wood-Vasey


Others: can you please double check your sections to make sure that everyone is correctly accredited for their work? Thank you!

**Comment by rbiswas4** [comment]
@drphilmarshall I have addded a name, a few addresses and removed a name on request along with some text updates in a commit (which is being reviewed by others). I will issue a PR as soon as that is confirmed.

**Comment by drphilmarshall** [comment]
Great, thanks Rahul. I hope that everyone else is happy with their author
lists - and that your unmentioned colleagues are also happy!

**Comment by drphilmarshall** [comment]
Hi all - as you saw, we've now submitted v0.99 of the white paper to the SAC for review, but during the review period we can continue to fix things like author lists. If you have not updated your section/chapter author list yet, please do submit a PR ASAP! Thanks :-)

**Comment by drphilmarshall** [comment]
Hi everyone! As you can see, we have received lots of good feedback from our SAC and LSST Project reviewers, which is being farmed out to be addressed by the end of May. Thanks very much for helping out with this in the next couple of weeks! While you are editing your files, you might also double-check your section and chapter author lists. Thank you!
