### ISSUE TITLE
Create a GW followup section in the cosmology section, coordinating with the authors of 6.5

### ISSUE THREAD

**Issue by ehneilsen** [LSSTScienceCollaborations/ObservingStrategy#576]
GW followup of kilonovae has important cosmological applications; the GW signal allows measurement of distance independent of the "distance ladder" or indeed any calibration of standard candles. If LSST can identify host galaxies, redshifts can be obtained, and H0 measured. So, section 6.5 should at least be referenced in the cosmology section; perhaps a new cosmology subsection should be created that discusses these cosmological implications, and references 6.5.

**Comment by egawiser** [comment]
Closing this ancient issue, which has now been addressed in various white papers.
