### ISSUE TITLE
Fix arxiv references to contain the arxiv ID

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#604]
Preferably also with a hyperlink to the paper on astroph...

See request from Tim Jenness on jira [here.](https://jira.lsstcorp.org/browse/PUB-42?focusedCommentId=73990&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-73990)

**Comment by rbiswas4** [comment]
@drphilmarshall Do you already have a bst file which hyperlinks them to the numbers?

**Comment by drphilmarshall** [comment]
I suspect the problem is that we are using `apj.bst`, which doesn't display
the ID or URL. Perhaps we should try and hack this?

**Comment by rbiswas4** [comment]
OK ... I put the bst file I usually use and shows the arxiv number only in https://github.com/rbiswas4/ObservingStrategyOld/tree/trydiffbst . Two things (a) I don't know what you would like to display before the number like 'arxiv' ? (b) I had some errors compiling the latex on my computer before I changed the bst file, as well as after.

**Comment by drphilmarshall** [comment]
Thanks Rahul! :-)

a) I think I'd like it to say "astro-ph/1104.56782" with hyperlink to the
arxiv abs page

b) Let's deal with those once you have opened the PR. Would you mind,
please? Thanks very much!

**Comment by rbiswas4** [comment]
(a) (Even though astro-ph does not appear in the newer arXiv references which look like   arXiv:1703.06139 [pdf, other] while the older ones look like  arXiv:astro-ph/0608007 [pdf, ps, other]). Sure, I can make it look that way.

**Comment by drphilmarshall** [comment]
Ah. Hmm. Maybe `arXiv:1703.06139` and `arXiv:0608007` is a better scheme
then. Thanks!

**Comment by timj** [comment]
I've just made a change like this to the LSST bst file: lsst/lsst-texmf#26
You may also be able to use the `urlbst` tool from @nxg from http://ctan.sharelatex.com/tex-archive/biblio/bibtex/contrib/urlbst/urlbst.pdf

Both these pick up the `eprint` and `archiveprefix` entries used in ADS bibtex files.

**Comment by drphilmarshall** [comment]
Thanks for the link, @timj. I ended up going with [yahapj.bst](https://github.com/AASJournals/yahapj), for its more compact hyperlinks in the references list. Good that you pushed for this, it's much better to have the links in there.
