### ISSUE TITLE
Discuss Science Book in introduction

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#61]
@michaelstrauss asked about this during the Thursday white paper plenary ( #58 ). 

* [x] Want to take on a suitable paragraph/subsection on this in the introduction, Michael? 

* [x] We could then also think about comparing the growing WP with the SciBook. @michaelstrauss would you mind issuing this as well, and include your thoughts on how faithful we should be to the Science Book? Thanks!

**Comment by michaelstrauss** [comment]
In response to Phil's request:
  Yes, I have drafted a few paragraphs for the preamble of the White Paper introduction, describing the relationship of this document to the science book.  I make it clear that this is not an update to the science book per se, but will connect to the science book where appropriate, and describe where our thinking has evolved (e.g., in the specific science cases, or where our understanding of the LSST system performance has changed).  

I will next go through the White Paper and Science Book, to see if I can identify major science themes in the latter that are not yet mirrored in the former.
