### ISSUE TITLE
Comments on Chapters 1, 2 and 12

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#611]
Hello all,
 A PDF scan of my hand-written comments is attached.  This is the first posting from the SAC review of the whole white paper.  These chapters are an introduction (1), conclusion (12), and a discussion of the OpSim runs (2).  Apologies that this is not split into separate small issues.  
Overall, they are well-written and clear, and many of my comments are minor suggestions on wording, etc.  
 My more substantive concerns are as follows:
  -The text is inconsistent about whether the airmass limit of the main survey is 1.4 or 1.5.  
  -The basic parameters of the baseline cadence survey (declination limits, full definition of the mini-surveys, observing cadence in deep fields, etc., etc) are never explained. 
  -Most of Chapter 2 reads as it was written about 2 years ago.  minion_1016 is described as a “candidate” for the baseline cadence (it has since been officially adopted), and there are a lot of no-longer interesting references to the older baseline cadence.  Many of the problems described in this chapter are solved with V4 of OpSim, but that is never mentioned.  
   -Dithering is mentioned in passing multiple times in Chapter 2, but never properly explained. 
   -Chapter 12 needs a final forward-looking section, describing next steps: what experiments can now be done with V4, how complete we are with relevant metrics, etc.

[0781_001.pdf](https://github.com/LSSTScienceCollaborations/ObservingStrategy/files/924292/0781_001.pdf)

**Comment by drphilmarshall** [comment]
This is _great_, thank-you Michael! :-) I will look through these comments with @bethwillman and @ivezic and issue the fixes you recommend. If we have questions we'll use this thread. Thanks again!

**Comment by drphilmarshall** [comment]
Whoever addresses Michael's comments on the introduction could also fix issue #616
