### ISSUE TITLE
Comments on special surveys chapter from Niel Brandt

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#614]
This is part of the SAC review of the white paper.  He writes:

There is some potentially great stuff in this chapter, and it was
good to re-read it. But overall it reads as a bit of a hodgepodge
presently, and there is a lot of work to be done here.

[special-surveys-chapter-feedback01.pdf](https://github.com/LSSTScienceCollaborations/ObservingStrategy/files/935084/special-surveys-chapter-feedback01.pdf)

**Comment by drphilmarshall** [comment]
Thanks Michael. I can't argue with @nielbrandt 's overall assessment! I'll talk to @bethwillman and @ivezic about how to address the hodgepodge nature of the chapter, and report back to this thread. I suspect we can come up with a more coherent structure now we know more about the overall timeline of the observing strategy process, and how "mini-surveys" fit in to that.

**Comment by ivezic** [comment]
Good comments, and it shouldn't take too much work to address them. 
It seems that we should make sure that the following coauthors are aware of these comments:
- David Trilling and Lynne Jones @davidtrilling @rhiannonlynne 
- Chris Stubbs @astrostubbs 
- Suzanne Hawley, Ruth Angus, Jim Davenport @suzannehawley @RuthAngus @jimdavenport

**Comment by davidtrilling** [comment]
i'm on it and will coordinate with lynne.

david

**Comment by drphilmarshall** [comment]
I see David and Lynne's changes, thanks! I added some explanatory text at the start of the chapter to mitigate hodgepodginess, and cross-referenced the twilight solar system survey with Stubbs' more general twilight observing section. I think this should pass muster now! Thanks everyone.
