### ISSUE TITLE
Comments from Jason Kalirai (SAC) on preface

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#615]
- The Preface jumps right into the content of the paper and assumes that the reader is familiar with a lot of terminology ("Project members", "Collaboration", "OpSim", etc..  This is a major publication following the LSST science book and deserves some type of extended "Executive Summary".  This is especially important for the many scientists in the community that haven't been following LSST closely, and will want to read a summary.  This should begin with an inspirational paragraph about the telescope and its survey, and then all of the various terms and communities should be defined explicitly.  The Preface itself is probably OK after such a summary, although I think the word "you" towards the end should probably be replaced with "our community" or similar.

  (Note from Michael: I made a similar comment)

**Comment by drphilmarshall** [comment]
Thanks, Michael! (And please pass on our thanks to Jason as well for his review :-) ) 

I've self-assigned this for now: I think the executive summary is a good idea and would indeed be much appreciated. We'll need an abstract for the arxiv posting too...  I'm not sure that the Executive Summary is exactly the right place to define terms (that seems more like the introduction's job), but I'll definitely keep this in mind as I try to write something sensible.
