### ISSUE TITLE
Comments from Jason Kalirai (SAC) about Chapter 11 (WFIRST)

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#619]
- 11.1 – should update the WFIRST filter and grism wavelengths.  The filter set now includes a filter extending from 0.5 – 0.75 microns and the grism covers 1-2 microns
 
- Given the breadth of the LSST science program, it would be nice to have more balance in the discussion here.  The dark energy and microlensing programs are two examples of surveys that benefit from overlapping LSST-WFIRST data sets, but there are many more.  We wrote an entire paper on this topic (https://arxiv.org/pdf/1501.07897.pdf) which is not referenced in this section (apologies if I missed it).  This includes ways that combined WFIRST and LSST data could impact studies of the variable universe, stellar astrophysics, Milky Way science, galaxy and quasars, strong lensing, etc.  It would be great to include some of that so the mentions of other HLS science themes are more specifically called out.  J. Rhoads has probably already requested such input from the WFIRST FSWG, but I suggest a second call now that there is a white paper taking shape.  Alternatively, maybe we could ask Bhuv Jain to write a summary before jumping into the dark energy and microlensing discussions.
 
- Related, it would be great to get more specific feedback from the **LSST community** on how WFIRST overlap can **help them**.  Right now, large parts of this section are written to benefit WFIRST.  Surely, 0.1" imaging down to 27th mag over 10% of the LSST survey will serve as a "truth image" for many things in the Science Book.

**Comment by drphilmarshall** [comment]
Thanks Jason! (via Michael)

@jasondrhodes I agree with Kalirai (above) that the WFIRST chapter comes across a bit lop-sided - because the WFIRST team arrived, full of ideas for useful synergy but naturally starting from the WFIRST dataset. I'm not sure what to do about this: it's perhaps an indication that only a few people feel that the WFIRST data will "belong" to them. It would be great if we could somehow use the introduction to the WFIRST chapter to encourage the community outside the teams actively planning for WFIRST to think about the WFIRST data set in the right way. What do you think about the specific suggestions in the review above?

**Comment by jasondrhodes** [comment]
I will make the changes to the filter wavelengths and put in some introductory text encouraging the community to think about ways of leveraging the combined WFIRST/LSST data.  however, my understanding of the purpose of this white paper and the WFIRST section was NOT to talk about WFIRST/LSST synergy but to suggest ways that the LSST cadence or sky coverage could be modified to enhance benefits with specific planned WFIRST surveys.  I don't think this LSST Observing Strategy White paper is the right venue to open up discussions about the full range of WFIRST/LSST synergy in all areas of science.  I suggest we stick to making arguments aimed at LSST's observing strategy.

**Comment by drphilmarshall** [comment]
Good, OK - I think some notes in the introduction from you will help reposition the chapter well enough. Over time, and as LSST simulations appear that include improved coverage of the WFIRST area and campaign period, we can expect other science cases to begin to refer to synergy with WFIRST. Thanks, Jason!

**Comment by jasondrhodes** [comment]
I have addressed these issues and created a pull request.

**Comment by drphilmarshall** [comment]
Thanks Jason! PR now merged.
