### ISSUE TITLE
Bright object/twilight survey to extend dynamic range?

### ISSUE THREAD

**Issue by astrostubbs** [LSSTScienceCollaborations/ObservingStrategy#62]
Hi folks. I have a proposal for extending the LSST dynamic range in magnitudes by using twilight time to take short exposures. Here is a Figure that shows available dynamic range vs. time from twilight
and exposure time. PDF file with a description is available at 
physics.harvard.edu/~stubbs/short_exposures.pdf
![stubbs_fig2](https://cloud.githubusercontent.com/assets/7434450/9396169/f150c17c-4760-11e5-94f8-bc8a16dadb8a.jpg)

**Comment by drphilmarshall** [comment]
Interesting! What twilight observations are currently included in the `OpSim` runs we have? @rhiannonlynne @connolly ?

**Comment by drphilmarshall** [comment]
Also: @astrostubbs which science projects would *most* benefit from such an addition?

**Comment by ivezic** [comment]
We don't have twilight observations yet. Adding this is on our to-do list.

**Comment by astrostubbs** [comment]
Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

**Comment by rhiannonlynne** [comment]
Current opsim surveys observe to sun altitude of -11 deg, however we do not have a good twilight sky model (just do a step function to a bright value).  Coming soon!

**Comment by jhrlsst** [comment]
Hi,
Are the presentations at the meeting available somewhere? 
Jeonghee

**Comment by ivezic** [comment]
Not at this very moment, but we'll make sure they are up tonight.

**Comment by connolly** [comment]
@astrostubbs twilight is in the sky model that @yoachim is building but it is not incorporated in opsim

**Comment by drphilmarshall** [comment]
I think twilight observing has been clocked as something to include in the opsim experiments now: I'm closing this issue, but @astrostubbs you might like to keep an eye on the white paper as it evolves to make sure it gets discussed in the appropriate place. You can always open a new issue. In the meantime, well done on a very good hack, all! :-)

**Comment by astrostubbs** [comment]
Link to current white paper draft on Github seems dysfunctional. 

Christopher Stubbs
Samuel C. Moncher Professor of Physics and of Astronomy
17 Oxford Street
Harvard University
Cambridge MA 02138
stubbs@physics.harvard.edu

If you think this email is terse, see http://emailcharter.org

**Comment by drphilmarshall** [comment]
I'll take this link down, thanks for reminding me. git pull and make to get
the latest version.

**Comment by StephenRidgway** [comment]
Well, I protest - it requires a degree of competency to not end up with a different content pdf.  A master pdf was unambiguous and a  confirmation that my contributions were registering.

**Comment by AshishMahabal** [comment]
I second Steve. Its useful to have the master PDF.

**Comment by drphilmarshall** [comment]
Like I said, I'm looki g into providing a continuously built PDF hosted on
a SLAC web server. The whole repository had grown to 0.45 gigabytes in
size, which is itself something of a barrier to entry. Thanks for your
patience and understanding, everyone!
