### ISSUE TITLE
Comments from Jason Kalirai (SAC) on Chapter 4 (Milky Way)

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#620]
- overall, this is a really great effort.  I like the organization of a broad set of Milky Way science cases into three bins; populations that are only found within the plane, a wide range of astrometry applications, and mapping of structures in the halo.  Although this doesn't capture all of the science cases in the Science Book, it is a reasonable approach to represent a significant fraction of Milky Way science in driving cadence choices.  The one component that I see as missing, which is briefly acknowledged by the authors, is the static science.  The overall uniformity and depth through a survey of the Milky Way plane will inform a number of areas in Galactic structure and statistics from studies bulk populations (e.g., IMF).  At least one example of such a science case will be important to develop, so we can look at the trade space b/w optimization for variability studies vs static science.  For example, one of the conclusions from section 4.2 is that the co-added depth is a lower priority than other measurements; I'm sure this will be cause tension with the static science needs.  My comments below are mostly just endorsements of things said in the chapter.
 
- the authors correctly point out some of the limitations of the baseline strategy in minion_1016, which allocates most of the inner plane observations over a short time period (through the special survey).  This is very bad for temporal studies (i.e., proper motions). One thing that will be interesting to review after we have stellar population simulations (see below) is what the special survey looks like vs a simple extension of the primary survey to the plane.
 
- the specific analysis of metrics to drive cadence choices requires relevant simulations of Milky Way populations.  This has been lacking for a number of years now but discussions are starting up again.  Simulations with different levels (and types) of crowding would greatly inform the conclusions on how to set and evaluate metrics. The group is discussing over email how to move this forward, and that will help refine the summary.  This is important for assessing 1.) photometric sensitivity, 2.) completeness, 3.) star/galaxy separation, and 4.) proper motions (i.e., astrometry of quasars/galaxies to define a zero motion frame of reference).
 
- section 4.4 – would be good to get a specific tie in to the WFIRST opportunity of 2000 sq deg high latitude survey at high resolution for halo mapping w/ LSST.  In this case, the optical-IR baseline would aid in the characterization of the stellar populations also.
 
- section 4.5 – important to develop this further.

**Comment by willclarkson** [comment]
Good comments! 

I've opened up a new issue ( #626 ) to address the static science issue, help is very much welcome.

The comment on the 2000 sq deg WFIRST opportunity is very interesting... would anyone like to provide more information on this? @jasondrhodes - I see you've thought about this overlap from the cosmological point of view (chapter 11.2), are yourself or any others doing any work on the WFIRST-HLS for stellar population work?

**Comment by drphilmarshall** [comment]
Thanks Will. Jason R is taking a look at more of Jason K's comments in #619, but a note on WFIRST synergy in the Galaxy Chapter somewhere (Further Work?) woudl be good - if only to let the readers know what is possible. Regarding the other comments: if you have edits to address them, please do go ahead with a PR, or close this out! Thanks :-)

**Comment by willclarkson** [comment]
Thanks Phil - what is the deadline to implement the static Figure of Merit
in our response to Jason's comments? If it's soon, then it might be better
to write in as a specification.

Best

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
--
Students: please put your course number in the title of messages to me

**Comment by drphilmarshall** [comment]
The only deadline we have as a group is Friday 26th May, to complete v1.0
of the white paper so it can be posted to the arxiv. Any analysis that
can't be done by then should be spec'ed, and then issued for later, exactly
as you say. Thanks!

**Comment by akvivas** [comment]
Galaxy chapter has now a brief mention to WFIRST synergy in section 4.4. Some references were added accordingly. This is pull request #644

**Comment by drphilmarshall** [comment]
Looks like this Jason's review has been addressed - thanks both!
