### ISSUE TITLE
Comments from Anže Slosar (SAC) on Section 11 (WFIRST)

### ISSUE THREAD

**Issue by slosar** [LSSTScienceCollaborations/ObservingStrategy#622]
I'm uploading this directly to save Michael Strauss some work.

In general, the chapter is good, albeit it could do with some polishing. See also Issue #619. In particular:

 * The paper on all possible synergies between surveys (Jain et al) should be cited and introduction expanded by listing synergies. However, I feel there is no need to be excessively verbose since majority of the synergies do not impact the observing strategy considerations. E.g. clusters, strong lensing, etc. are all covered by the faster integration on HLS. 

* As a general comment: only 11.4 provided FoM. Not sure how useful these are as they need to have the same units (as you correctly note in one of the intro section). (Also not sure if measuring them in bits added is useful, you could add many bits to measurements of Hubble parameter and some stellar population person might still consider those bits wasted... Not to mention they depend on priors, etc.)

* As a general comment: I have some very vague notion that perhaps GO programs in WFIRST could also benefit from LSST's help. You could imagine some process by which LSST director would be able to see those proposals and perhaps burn some of director's discretionary time on that. Not really actionable, but perhaps something to think about.

* Section 11.2.: 
  * There is some allusion of reducing integration in y/z in the WFIRST overlap area, but as far as I can see this idea has not been elaborated. In particular, if this can save some time, it should be pursued (i.e. one of the rare opportunities to save, rather than spend time). Of course, there needs to be a sufficient area of the overlap with full depth in all bands for calibration/sanity/systematics checks, but perhaps not the full WFIRST area, if WFIRST imaging is going to be so much better there. So, this should be worked on further.
  * Answer A7

* Section 11.3: this is the weakest (in the sense of least converged, not least interesting) section. 
  *  Sentences like "(DR still working on...)" need to go. 
  * Spell out acronyms (CC=core collapse, LC=light curve?).
  * I think discussion of why things were abandoned for WFIRST due to slew speed, etc, need not be in the LSST obs strategy.
  * Add responses to questionnaire (or provide clear understanding that that in 9.5 suffices, though I'm unsure about that).

*  Section 11.4.:  
   * Clarify that Fig 11.1 is a simulation.
   * Not sure if you need equations in this section. Simply stating that given this and that you can work out mass is sufficient at this level

**Comment by jasondrhodes** [comment]
@slosar  and @michaelstrauss thanks for these comments.  I have addressed most of them. Jain reference and short discussion added. The discussion of GO programs is left out, but I agree it is a fruitful one to pursue.  Please don't hesitate to contact me about how we might best coordinate.  Regarding the possibility of y/z integration reduction, this can be worked jointly, especially in the overlap area, but I have not further addressed it in the paper.  Please let me know if more discussion is needed in the paper.  Again, happy to coordinate in another venue. 

@rubind please take a look at section 11.3 and address the concerns.  I think we should include a FOM in this section and answers to the series of questions that are requested in each section

@mtpenny I added the explanation that the figure 11.1 is a simulation, can you see if the equations can be reduced.

**Comment by drphilmarshall** [comment]
Thanks for addressing Anze's comments, @jasondrhodes - I merged in your commits from #623. 

Matt, David - here are Jason's queries for you again. Great if you can submit a quick PR each with any required fixes! Thank you :-)

> @rubind please take a look at section 11.3 and address the concerns. I think we should include a FOM in this section and answers to the series of questions that are requested in each section

> @mtpenny I added the explanation that the figure 11.1 is a simulation, can you see if the equations can be reduced.

**Comment by mtpenny** [comment]
Hi Phil, Jason,

Sorry, I've not been checking email too much while travelling and its hard to spot the important LSST github ones. Look for a pull request today or tomorrow.

Cheers,
Matthew

**Comment by drphilmarshall** [comment]
Excellent, thanks very much Matthew!

Pro-tip: I filter my email threads for the string `@drphilmarshall` - this
helps me catch "important issues" ie the ones I am mentioned in.

**Comment by mtpenny** [comment]
I have submitted the pull request. @rpoleski and Dave Bennett should review the changes (they can be seen on my fork while waiting for the pull request to be accepted: https://github.com/mtpenny/ObservingStrategy).

**Comment by drphilmarshall** [comment]
I merged @mtpenny 's PR ( #646 ). Today is deadline day, @rubind ! Can you please edit the WFIRST tex file to address your reviewer's comments on section 11.3 please? Here they are again:

> Section 11.3:
>
* Sentences like "(DR still working on...)" need to go.
* Spell out acronyms (CC=core collapse, LC=light curve?).
* I think discussion of why things were abandoned for WFIRST due to slew speed, etc, need not be in the LSST obs strategy.
* Add responses to questionnaire (or provide clear understanding that that in 9.5 suffices, though I'm unsure about that).

This looks like straightforward clean-up to me. Thanks!

**Comment by drphilmarshall** [comment]
Clean-up was indeed straightforward, Jason had done a good job. Thanks all!
