### ISSUE TITLE
Comments on dithering section of cosmology chapter, from Timo Anguita (SAC)

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#624]
Very good section. I don’t really have much to add. My main concern here is not with the section but whether these dithering patterns will be added to the OpSim. It would be very interesting to have an OpSim output with dithering to measure how other science cases will be affected.

The acronym “OS” for observing strategy is not used through-out the whitepaper. I would remove it here for consistency.

**Comment by drphilmarshall** [comment]
Thanks Michael. @humnaawan @ajc do either of you know if/when dithering will be added to OpSim? Looks like a useful sentence to add to the LSS science case of the white paper. Humna, great if you could take a minute to unpack the "OS" acronym, too - thanks! :-)

**Comment by MichelleLochner** [comment]
@humnaawan or @connolly do you have a minute to quickly fix the use of OS and submit a PR?

**Comment by humnaawan** [comment]
@MichelleLochner I just issued a PR with the abbreviation fix. Please let me know if there are any problems.

@drphilmarshall as far as I know, all the translational dithers are currently available through MAF Stackers; only one kind comes with the OpSim database automatically (as a result of an afterburner on the simulator output). I did some work with @SimonKrughoff and @rhiannonlynne to extend the afterburner to replace the original translational dithers with newer ones and add random rotational dithers but I am unaware of whether that will be used for the next OpSim run. Perhaps @connolly can say how best to mention this in the paper?

**Comment by connolly** [comment]
I'll take a look and update the text based on where the scheduler is going
with dithering (and what is currently there).

**Comment by connolly** [comment]
There is a PR with text on OpSim dithering plans

**Comment by drphilmarshall** [comment]
Thanks all! Let's close this out then.
