### ISSUE TITLE
Comments on strong lensing section of cosmology chapter, from Timo Anguita (SAC)

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#625]
Very interesting and advanced metrics. I do have some comments that I believe will help the non-expert reader.

The section needs a bit more detail on some concepts:
For example, on how the metrics (A, P, f) are actually calculated. It is true that the interested reader will refer to Liao et al. 2015 and the future publication with the TDC2 results, nevertheless a bit more self containment would benefit the section. 
Several readers will not be familiar with time delay distance and its relation to the Hubble constant. I would write this as an equation(s) on the section and add references, including current measurements with the method.
This also applies to sentences like: “...can be roughly equated to the statistical uncertainty on the Hubble constant”. I would either be more explicit or add a reference.
A question: How can the number of lenses using ugrizy be less in 10 years than it will be in 5? It is not a big difference, but somewhat surprising. Is it due to the slightly lower precision in 5 years?
The labeling of the color bars in the healpix plots (Figure 9.23) need to be fixed.
Answer 4 typos: “inasmuch” and “night-to-nght’
Answer 7: The answer should be “no”
Answer 8: “we’d”-->”we would”

I really miss in this section at least a comment on how the observing strategy would (if at all) change the number of lensed quasars to be found on the first year, five years or end of survey given the candidate observing strategies. I.e. do the results from Oguri and Marshall 2010 still valid for the current observing strategy? By the way this work is not mentioned in the text.

I also miss more on lensed supernovae, but I guess that would be a little bit harder to include at this stage, but it is certainly something to crosstalk about with the supernovae section.

**Comment by MichelleLochner** [comment]
@drphilmarshall do you also need editor prodding? ;)

**Comment by drphilmarshall** [comment]
Yes, yes I do. Thank you Michelle!

**Comment by MichelleLochner** [comment]
@drphilmarshall also don't forget the figures as in #545! :)
