### ISSUE TITLE
Comments from Mansi Kasliwal (SAC): Chapters 1 and 2

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#627]
# Section 1.3:
Survey Strategy Committee - as we had discussed in March, it may not be the best idea for the LSST PS to chair this committee. Was this discussed further after we sent the minutes? The document has not been updated.

# Also add to Section 1:
Some mention of what timescale will the survey strategy be reviewed and possibly revised during operations (1 year? 2 years? Not at all?)
 
# Also clarify in Section 1:
As we discussed in March, the point about whether DDF includes or excludes mini-surveys (NE spur, Galactic plane etc.) should be made more clear. Also the point about whether DDFs include or exclude ToOs should be made more clear.

#Section 2: Summary
The mention of 40% margin relative to the SRD best-case scenario is unbelievable and is mentioned here only casually. Are current simulations (e.g. minion_1016) also carrying this 40% margin or doing a more realistic simulation of the available time? I am assuming the answer is yes but this should be made more clear. 

# Section 2.1 Table:
kraken_1045 and kraken_1059 have identical descriptions - add to the kraken_1059 description that it conserves total number of u-band visits. 

# How is minion1016 better than the old baseline cadence? The discussion that is written down here seems to suggest it is worse?

# I like the details about various simulations changing one parameter at a time. But I don't understand why the new proposed baseline cadence doesn't take into account lessons learned from this set of simulations. For example the u-band perturbation. These simulations should already help somewhat constrain the multi-dimensional parameter space for future rolling cadence simulations. 

# Section 2.5:
Add mention of scientific merits of faster cadence in bluer filters and slower cadence in redder filters

#Section 2.5:
This section discusses very generally what rolling cadence means. But it does not discuss any specifics on what rolling cadences are actually going to be simulated over the next year or so. I thought there was more of a plan here than the document suggests?

**Comment by drphilmarshall** [comment]
Thanks Mansi (via Michael)!

@ivezic I think you are probably best placed to address Mansi's comments - would you mind submitting a quick PR with the required fixes and then raising any remaining problems on here with (say) Beth and/or Andy? Thanks!

**Comment by ivezic** [comment]
I addressed all these comments. And updated the schedule table (fig. 1.1)
I just did: 
git push origin master:ivezic-627-response
