### ISSUE TITLE
Comments from Mansi Kasliwal (SAC): Chapter 12

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#629]
#Section 12
Missing in A2: Discovering transients also requires rolling cadence. In particular, a simulation with faster cadence in bluer filters in a shorter rolling window and slower cadence in redder filters in a longer rolling window may help address many of the trade-offs in TDA.

**Comment by StephenRidgway** [comment]
A very promising cadence idea - I suggest formulating it in sufficient detail to propose a simulation experiment: https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/README.md <https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/README.md>

**Comment by drphilmarshall** [comment]
Hi Steve! I'm not sure Mansi will get back to this in time for submission of the white paper to the arxiv at the end of this month - would you mind instead adding a note in Chapter 12 along the lines she suggests, so that it is there in the text to inspire further work? Thank you!

**Comment by drphilmarshall** [comment]
@StephenRidgway I inserted Mansi Kasliwal's comment about blue and red rolling cadence into the rolling cadence item in the Conclusions chapter, as follows:

> Also, a rolling cadence can concern any number of filters; for example, one filter could be used to provide short bursts of rapid sampling, while other filters could maintain a uniform distribution.  In particular, for discovering transients a simulation with faster cadence in bluer filters in a shorter rolling window and slower cadence in redder filters in a longer rolling window may help address many of the trade-offs involved.

I think we may need to propose the OpSim experiment ourselves, can you make a note to track this when rolling cadence simulations are being designed, please? Thanks!

**Comment by StephenRidgway** [comment]
Phil, I am continuously tracking progress on simulations, with special interest in rolling cadences.  As the number of parameters  increases (esp different cadences for different filters) the order of complexity increases also - it will be essential to guide the requested simulations as it will not be possible to explore all of parameter space.
