### ISSUE TITLE
Comment from Charles Liu (SAC) on AGN chapter: "regular (non-quasi) periodicity"

### ISSUE THREAD

**Issue by michaelstrauss** [LSSTScienceCollaborations/ObservingStrategy#631]
I've read through the AGN chapter now - a few times, actually - and I don't have anything substantive to add to the comments that Niel Brandt has already shared - I saw a few additional typos here and there but I'm sure those will be fixed in a future iteration.  What I can't shake, though, is a nagging feeling that at least one significant observing mode has been left out; I just am not sure how significant it is.  Quasi-periodic oscillations are of course important; what about regular (non-quasi) periodicity - for example, possibly to probe the population of binary SMBHs?  I feel it wasn't addressed much in the chapter.  If it's potentially important, what would be a good cadence to do that science?  Or, is it better to use other modes to pick up QPOs, then just trigger them out to other facilities for longer-term monitoring for periodicity?

**Comment by drphilmarshall** [comment]
Thanks Michael.

@ohadshemmer Can you or one of your team please comment on Charles' question please? Might be worth a note in the AGN chapter intro, or a longer paragraph in the "Further Work" section. Thanks!

> "What I can't shake, though, is a nagging feeling that at least one significant observing mode has been left out; I just am not sure how significant it is. Quasi-periodic oscillations are of course important; what about regular (non-quasi) periodicity - for example, possibly to probe the population of binary SMBHs? I feel it wasn't addressed much in the chapter. If it's potentially important, what would be a good cadence to do that science? Or, is it better to use other modes to pick up QPOs, then just trigger them out to other facilities for longer-term monitoring for periodicity?"

**Comment by drphilmarshall** [comment]
OK, I added a comment at the end of the chapter discussion, as part of an invitation to think about more AGN science cases :-)
