### ISSUE TITLE
Address Stubbs' feedback on Chapter 12 (Conclusions)

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#636]
Chris Stubbs provided feedback on the LSST Jira [here](https://jira.lsstcorp.org/browse/PUB-42?focusedCommentId=76123&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-76123) - @StephenRidgway @ivezic Would you be able to respond to any of Chris's 17 points? Let me know, by PR if you are feeling energetic! :-) 

Thanks, Chris :-)

**Comment by StephenRidgway** [comment]
I’m pretty grid-locked but will try to do it tomorrow.

What is PR  - another messaging system?

**Comment by drphilmarshall** [comment]
Thanks Steve! Apologies for the jargon: a "PR" is a "pull request", which
is how I've been encouraging people to make changes so that they can be
most easily visualized. If you prefer, you can also simply push to master
and let us know when you are done. Thank you!

**Comment by StephenRidgway** [comment]
Hi, pulled the current draft and updated.  Not clear to me if push worked.

Steve





[dhcp-3-217:~/github/ObservingStrategy/whitepaper] Steve% git commit -am "Fix points from ChrisS/MansiK"
[master 65abef0] Fix points from ChrisS/MansiK
 1 file changed, 38 insertions(+), 49 deletions(-)
[dhcp-3-217:~/github/ObservingStrategy/whitepaper] Steve% git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
[dhcp-3-217:~/github/ObservingStrategy/whitepaper] Steve% git push origin master
Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.12 KiB | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
To git@github.com:LSSTScienceCollaborations/ObservingStrategy.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:LSSTScienceCollaborations/ObservingStrategy.git'

**Comment by rhiannonlynne** [comment]
Master is protected and you cannot push directly to master. You need to
push on a branch. Do you want some help with that? Alternative is that Phil
could unprotect master long enough to let you push, and then put it back.

**Comment by StephenRidgway** [comment]
Well, I followed the exact commands that worked for several years - must have been unprotected all that time - it did seem a little odd.

I’ll wait for somebody to tell me wat to do or to volunteer to do it for me.

steve

**Comment by drphilmarshall** [comment]
Ah yes - sorry! I turned on protection for the master branch once we moved into this review/response phase: its easier to see what's changed in a pull request, but you do need to be familiar with branches to do that. Try the following, Steve:
```
git push origin master:ridgway-ch12-response
```
I *think* this should create a branch called `ridgway-ch12-response` in the repo at GitHub, and we can then start a pull request from there. If this does not work, don't worry - I also enabled push access to `master` just for you, Steve, so your original `git push` should now work. But do try the new branch first, so we can better appreciate your modifications! :-) Thanks for your efforts on this, Steve.

**Comment by StephenRidgway** [comment]
No problem.

I executed the command you gave me:

[Stephen-Ridgways-MacBook-Pro:~/github/ObservingStrategy/whitepaper] Steve% git push origin master:ridgway-ch12-response
Counting objects: 8, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.52 KiB | 0 bytes/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
To git@github.com:LSSTScienceCollaborations/ObservingStrategy.git
 * [new branch]      master -> ridgway-ch12-response
[Stephen-Ridgways-MacBook-Pro:~/github/ObservingStrategy/whitepaper] Steve% 

BTW, I posted Chris’ comments with my responses to https://jira.lsstcorp.org/browse/PUB-42 <https://jira.lsstcorp.org/browse/PUB-42>   

There was one comment that I felt deserved action that I did not take.

5) page 2 Q5: What are these "tracer populations" and why do we care? It's unclear.

I agree it’s unclear. I’m not sure who the author was. I hesitate to propose a change.

steve

**Comment by drphilmarshall** [comment]
Excellent, thanks Steve! PR is now open in #639. I'll take a look on Monday. 

Regarding the "tracer population" confusion - I think @ivezic can clear this up quickly, it looks as though he left a piece of case-specific jargon in when summarizing all the responses to his Q5:

> Q5: Does the science case place any constraints on the fraction of observing time allocated to each band?
> Generally, the baseline time allocation is satisfactory. Potential improvements depend on tracer population and the required imaging depth. The case for deeper u band data (both single-visit and coadded depth) has the strongest drivers. The fraction of visits in red bands should be higher for deep drilling fields than for the main survey.

**Comment by ivezic** [comment]
I addressed the "tracer population" comment and pushed to master using
git push origin master:ivezic-ch12-response

**Comment by drphilmarshall** [comment]
Closed via #639!
