### ISSUE TITLE
missing "thisversion.tex"?

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#641]
Hi @drphilmarshall -- compiling the WP gives a "file missing" error for file "thisversion.tex" .

I notice "thisversion.tex" is in the .gitignore for the repository. Is this an error, or should \include{thisversion.tex} be commented out in LSST_Observing_Strategy_White_Paper.tex ?

thanks - Will

**Comment by willclarkson** [comment]
Hi Phil - I'm using "pdflatex" to compile the whitepaper, here's a few lines of output:

<begin output:> 
(./LSST_Observing_Strategy_White_Paper.out)
(./LSST_Observing_Strategy_White_Paper.out)

LaTeX Font Warning: Font shape `OT1/cmr/bx/sc' undefined
(Font)              using `OT1/cmr/bx/n' instead on input line 28.


! LaTeX Error: File `thisversion.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name: 

</end output>

At this stage I just hit "Enter" and the compilation continues, presumably without thisversion.tex included.

Although now I suspect I might be following the wrong procedure to build the document...?

**Comment by willclarkson** [comment]
Aha, yes - there I see the compilation instructions in the whitepaper/README.md file, I *was* doing it wrong. When I simply type "make" as instructed, the document compiles fine. I'm closing this issue.

Sorry for the frivolous issue!!

**Comment by drphilmarshall** [comment]
Not at all! Glad the documentation fixed the problem. I wouldn't be
surprised if this came up again though...
