### ISSUE TITLE
Check `kraken_1059` u-band depth gain: 0.18 or 0.6 mag?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#652]
@ivezic While merging in Michael Reuter's comments in #609 I found a small discrepancy in the write up of `kraken_1059` (now re-labelled everywhere as `db:DoubleUbandExptimeSameVisits`. We write that doubling the u-band exposure time while retaining the Baseline number of visits would improve the coadd depth in this filter by 0.6 mag. However, the analysis seems to show that "the main survey coadded $u$ band image is 0.18 mags deeper." Do you know why this was? Then, in the conclusions of that little section, we write that "when the $u$ band exposure time is increased from
30 seconds to 60 seconds, and the number of visits is kept unchanged, the single-visit and coadded depths would be improved by 0.6 mag" without mentioning the apparent 0.18 mag gain. If we can resolve the discrepancy we should be able to rephrase the conclusions I think. Thanks!

**Comment by ivezic** [comment]
Yes, there was a problem due to the fact that meanwhile MAF learned how to 
properly account for the impact of readout noise. In the end, the text is simpler
now (also, we had kraken_1045 and kraken_1059 switched!).  I just did 
git push origin master:ivezic-PR652-response
