### ISSUE TITLE
Higher night-to-night cadence in extragalactic sky?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#66]
Just how bad for solar system and fast transient science do you think it would be if we divided the WDF survey area into "extragalactic" and "ecliptic+galactic" sky, and then kept the intranight visit pairs (or triplets, or quads) in the latter, and *forbade visit pairs* in the former? Supernovae would like to spread the visit pairs over several nights, to effectively double the night-night cadence, I *think* - but others can comment further. @MichelleLochner @rbiswas4 ? @rhiannonlynne ? @lmwalkowicz ?

**Comment by lmwalkowicz** [comment]
In our unconference session this evening, we discussed something similar-- not necessarily forbidding pairs entirely, but rather only requiring them in a band along the ecliptic, then making most exposure 30 seconds with a somewhat longer revisit time, potentially in a different filter so you get a color for transients of interest. Would require changing filters somewhat more often, but if revisit time was on the order of hours as opposed to ~20 min, then the increase in overhead devoted to filter changes wouldn't be too bad (and would still be less than the efficiency gained in overhead you get back from not having to take two separate exposures). @ivezic is a fan of making this a future OpSim run!

**Comment by drphilmarshall** [comment]
Sounds interesting! How about we just extend my ["NoExtragalacticVisitPairs" OpSim experiment proposal](https://github.com/LSSTScienceCollaborations/ObservingStrategy/blob/master/opsim/Proposal_NoExtragalacticVisitPairs.md) (and maybe change its name)? Have at it! :-)

**Comment by drphilmarshall** [comment]
Actually, @lmwalkowicz, let's leave my "No visit pairs" OpSim suggestion alone, and instead write down your "Colorful Transients" suggestion instead, as a separate one. I won't issue it just yet though - if you're really interested in it, you'll suggest it yourselves! :-)
