### ISSUE TITLE
Transients Chapter 6.4: Gamma-ray bursts & orphan afterglows

### ISSUE THREAD

**Issue by ebellm** [LSSTScienceCollaborations/ObservingStrategy#67]
I'm interested in developing a section on LSST's ability to constrain the beaming fraction of gamma-ray bursts through identification of a sample of off-axis ("orphan") afterglows.  Since these are rare (hence usually faint) and fast-fading, LSST is potentially a powerful tool for this task.  However, the need to constrain the lightcurve shape through multiple observations means that the science return will depend strongly on LSST's cadence.

An initial metric to consider would be the number of characterizable orphan AG lightcurves observed over the 10-year survey.

c.f. LSST Science Book 8.3.1

cc @cenko

**Comment by yoachim** [comment]
We took an initial stab at configuring the transient metric to look for GRB afterglows. I think the tricky part is figuring out what you need to confirm it is a GRB and not something else. 

https://github.com/LSST-nonproject/sims_maf_contrib/blob/master/science/Transients/GRBTrans.ipynb

**Comment by StephenRidgway** [comment]
Probably the first thing you need is time variability on a short time scale.  Is the 15 second baseline long enough, and is the 30 minute baseline short enough?  If no to both, then deep drilling is the only current cadence plan that might work.

**Comment by sethdigel** [comment]
This search would not require measuring measuring very short time scale variability.  The afterglows happen after the burst itself and their time scales for rise and fall are probably measured in days.  If the afterglows relate to detectable (on-axis) GRBs then the bursts probably will be detected and localized by some other instrument like Swift BAT (and the afterglow light curve measured by some other telescopes based on the then-known location).

**Comment by StephenRidgway** [comment]
So I think you are saying that search by LSST only need apply to off-axis sources?  Does that change the problem?

And time sampling ~ 1/day would be needed.  That is one of the most difficult cadences for LSST. After taking a data point in a filter, typically you would return in another filter in 3-4 days, and in the same filter in about a month.  

So this program might be adressed by a special rolling cadence that sampled daily.  That would necessarily be only for short intervals, weeks on any given field, as you run out of available visits pretty fast.

Steve

**Comment by sethdigel** [comment]
Well, as pointed out in that section of the Science Book that @ebellm referenced, a main goal of the search (characterizing the beaming fraction of GRBs) requires figuring out what fraction of afterglows do not correspond to bursts detectable in gamma rays.  I was pointing out that detectable GRBs will have light curves measured by other telescopes, but I guess that is only a little relevant.  

I'd guess that few day time sampling would be adequate.  Overall this kind of measurement of the average beaming fraction will be challenging because for whatever the cadence ultimately is, the detection efficiency for afterglows will need to be understood quantitatively, as well as the overlap with coverage by GRB detectors (which cover a lot of the sky all the time but not all of the sky all the time).

**Comment by ebellm** [comment]
The notebook pointed to by @yoachim is a good start, but the timescales are way off.  On-axis GRB afterglows fade by magnitudes in hours, not 10 days!  And they rise virtually instantaneously.  

LSST will see both on- and off-axis afterglows.  It is not clear to me that at LSST's sensitivity that we can assume that we can use high-energy detections to identify the on-axis cases.  

At minimum, then, I think the cadence this program prefers is triplets (or more) on the same night.  But we can quantify this with a metric.  We'll want to do something like control time calculations over a population of sources distributed in a cosmological volume.

As a starting point, note that  http://arxiv.org/pdf/1504.02096v1.pdf estimate a 50 yr^-1 detection rate for OA with LSST, but don't appear to make any particular assumptions about revisits.

**Comment by drphilmarshall** [comment]
Interesting. Want to have a go at sketching out this science project in a section file, @ebellm? Looks like you have a small team of enthusiasts available to help you once you've made a start :-)

**Comment by drphilmarshall** [comment]
PS. Assigning @StephenRidgway as editor of the relevant chapter - he can review and merge @ebellm 's pull request when it arrives! :-)

**Comment by ebellm** [comment]
Working on it--I'm trying to track down some of the modelling used in the science book to fold against the cadence.

**Comment by drphilmarshall** [comment]
Hey @ebellm @StephenRidgway how's this section looking? I guess it's somewhere in the V&T chapter, which has a multitude of editors who are probably interested in how this fits with their other sections @AshishMahabal @lundmb @lmwalkowicz @fedhere

**Comment by ebellm** [comment]
Okay, I have drafted some text and will now turn to a zeroth order MAF analysis.  Because these are cosmological the maf.metrics.TransientsMetric is not really the right way to do this (time dilation matters, brightnesses change, rates evolve with redshift), but it's at least achievable by tomorrow.

**Comment by fedhere** [comment]
outstanding!

On Thu, Nov 19, 2015 at 4:48 PM, Eric Bellm <notifications@github.com>
wrote:

> Okay, I have drafted some text and will now turn to a zeroth order MAF
> analysis. Because these are cosmological the maf.metrics.TransientsMetric
> is not really the right way to do this (time dilation matters, brightnesses
> change, rates evolve with redshift), but it's at least achievable by
> tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/67#issuecomment-158236356>
> .
>



-- 

 /\|/\
   |*  Please consider the environment before printing this e-mail
