### ISSUE TITLE
Which branch for pre-arXiv corrections & updates?

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#671]
Hi @drphilmarshall - I've made a number of edits to Chapter 4 following recent comments from co-authors, which I would like to be included in the arXiv submission version. I have submitted those so far as pull request #665 to the **master** branch. I believe they need review before merging (I don't currently have merge privileges).

However I'm now worried I've sent these to the wrong branch, as I see there's also an **arxiv-cleanup** branch on the repository now. Is *that* branch the one we're supposed to be using to update pre-arXiv?

Either way, I would like #665 to be reviewed and merged with whichever branch _is_ to end up on the arXiv.  How do chapter editors ensure that pre-arXiv edits are indeed considered for inclusion in the arXiv-posted version?

Reference: #621

**Comment by drphilmarshall** [comment]
Thanks Will! I think I did the right thing by merging your PR (#665) just now.
