### ISSUE TITLE
Poll: can we drop Python 2 support in LSST Simulations code?

### ISSUE THREAD

**Issue by danielsf** [LSSTScienceCollaborations/ObservingStrategy#683]
I apologize for using this repo for my own nefarious purposes, but this seemed like the best way to reach you all.

By 2020, most of the third-party packages we know and depend on (Jupyter, astropy, etc.) will have officially dropped support for Python 2 and will release in a Python 3-only mode.

http://www.python3statement.org/

We (LSST) are also discussing dropping support for Python 2 in the near future (best estimate is that this transition is a year down the line).  I would like to get a sense of how a quicker transition would impact the simulations user community, so that I have a quantitative answer to "how would dropping Python 2 affect simulations?"

If you have reservations about dropping Python 2 support by the end of spring 2018, please email me your concerns at

scottvalscott _at_ gmail.com

I will tabulate the results and pass the concerns along to the broader LSST software team.

Thank you.

**Comment by rhiannonlynne** [comment]
This has been done. Python 3!
