### ISSUE TITLE
Mechanism to collect commissioning observing ideas

### ISSUE THREAD

**Issue by cclaver** [LSSTScienceCollaborations/ObservingStrategy#69]
Connolly and Marshall have created a section to collect suggestions for new OpSim runs with different observing strategies.   Paula Szkody asked about filling in time sampling during the commissioning period.

We should create a parallel section where people can upload suggestions for special programs that would be done during commissioning.  These special programs should span the full gambit of opportunities from programs requirement an hour to those requiring a week or more.

**Comment by drphilmarshall** [comment]
We can do this no problem. The Suggestion Board for OpSim Experiments is in the opsim folder `issue64` branch, which @connolly is checking and merging today. We can copy this into a "commissioning" folder - and then advertise this in the README. @cclaver, why don't we pair code this together this evening in the unconference?

**Comment by drphilmarshall** [comment]
Also yes, we could add a special chapter on ideas for commissioning to the white paper - let's see how we go gathering suggestions first.

**Comment by cclaver** [comment]
@drphilmarshall sounds good lets plan to do this at the "unconference"

**Comment by drphilmarshall** [comment]
Nailed by @cclaver in #78 !
