### ISSUE TITLE
Github Familiarity

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#7]
* [x] Site overview. Edit files in place. Issues. Clone URL.
* [x] Cloning. SSH. Keys
* [x] Git workflow: status, add, commit. Push, pull, remote.
* [x] Issues: labels, assignment, mentions, references. Markdown. Milestones.
* [x] Commit messages: references, closes/fixes.

**Comment by StephenRidgway** [comment]
Do I skype you or do you skype me?

**Comment by drphilmarshall** [comment]
I'll skype you. Just waiting for @bethwillman to accept my contact request.

**Comment by drphilmarshall** [comment]
You can refer to other issues: #1

**Comment by drphilmarshall** [comment]
@bethwillman @StephenRidgway:

The one thing we didn't really get to in our tutorial the other day: you can (and should!) also close issues via commit messages. For example:

    git commit -am "Added website link to README, closes #5 "

The magic words to put just before the issue number are "fixes", "fixed", "closes" or "closed". Have fun!
