### ISSUE TITLE
Metric to calculate depth of a difference image template for a hybrid focal plane

### ISSUE THREAD

**Issue by connolly** [LSSTScienceCollaborations/ObservingStrategy#70]
Create a metric that will estimate the area of sky that is cover by a particular sensor and its depth if we have a hybrid focal plane. With @yoachim

**Comment by connolly** [comment]
Work so far http://nbviewer.ipython.org/a457cab27853cb92b2d5

**Comment by drphilmarshall** [comment]
Looks to me like this one got done! And shoudl be useful in some way for the WL people at least. Thanks @connolly and @yoachim! :-)
