### ISSUE TITLE
Incorporating discussion of specific metrics (existing & proposed) into Transients & Variables chapter

### ISSUE THREAD

**Issue by lmwalkowicz** [LSSTScienceCollaborations/ObservingStrategy#71]
The current chapter on transients contains skeletal text and is not tied to performance of specific metrics, though some of those metrics do exist and work has been done to apply them to various kinds of sources (mostly by @lundmb). I am going to edit the existing chapter to include a discussion of the existing metrics and associated considerations, so that people wishing to contribute (either metrics, analysis for specific science cases, or other) can identify whether there are metrics that address common temporal behavior of interest.

**Comment by AshishMahabal** [comment]
It may also be worth looking at metrics developed last year and use/include some of those.
https://docs.google.com/presentation/d/1M7RS17tja5aNgp8sTeTzz2yedNmJCkrsSqVKOzaLucg/edit#slide=id.g373573e6b_40

**Comment by lmwalkowicz** [comment]
thanks @AshishMahabal! I think some of these are captured in @lundmb's paper-- there are also metrics described already in the existing draft by @StephenRidgway. Steve, where did these metrics originate? Are they proposed metrics or have they been coded into MAF already..?

**Comment by StephenRidgway** [comment]
Those metrics in my tables are made-up short descriptions of what I thought was needed.  But in writing them down, I thought that most could be put together from existing MAF metrics.  I am not currently a MAF user so can’t do it along the way.

Steve

**Comment by lmwalkowicz** [comment]
OK @StephenRidgway thanks! I'm going to create a subsection in the introduction that outlines existing and proposed metrics so we can provide more detailed descriptions, then the tables in your subsections can indicate which of the described metrics might be applicable. I think we can more easily sort out whether yours can be constructed from existing ones once there's a more comprehensive description of what exists...

**Comment by lundmb** [comment]
For the Phase Gap metric that's outlined, the largest phase gap and the mean phase gap are both outputs from varMetrics.PhaseGapMetric

It should be trivial (and I'll try doing so in a moment) to add a median calculation as well to this.

**Comment by lundmb** [comment]
varMetrics.PhaseGapMetric now calculates the median phase gap, as is suggested in the metrics section on Phase Gaps.

**Comment by lmwalkowicz** [comment]
I've included some discussion of the metrics into the introduction of the chapter. This update does not close this issue however, as there is more description needed (@fedhere I saw your transient metric and created a placeholder for it, but it would be great if you would elaborate; same for your phase gap metric @lundmb). I collated @StephenRidgway's single sentence imagined metrics into a "Proposed Metrics" section, so they can be made more specific/codeable.

**Comment by fedhere** [comment]
point taken! in my defense i literally checked the metric in git hub with
one foot on the ferry...

that is actually a "utility" metric: it enables the user to use an ascii
file for the input lightcurve, and select the desired criteria for
detection on the fly. as such it does not belong as it is written in the
paper, but we may end up using it to build metrics that will be in the
paper.

f

On Sat, Aug 22, 2015 at 12:34 PM, Lucianne Walkowicz <
notifications@github.com> wrote:

> I've included some discussion of the metrics into the introduction of the
> chapter. This update does not close this issue however, as there is more
> description needed (@fedhere <https://github.com/fedhere> I saw your
> transient metric and created a placeholder for it, but it would be great if
> you would elaborate; same for your phase gap metric @lundmb
> <https://github.com/lundmb>). I collated @StephenRidgway
> <https://github.com/StephenRidgway>'s single sentence imagined metrics
> into a "Proposed Metrics" section, so they can be made more
> specific/codeable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/71#issuecomment-133724764>
> .
>



-- 

 /\|/\
   |*  Please consider the environment before printing this e-mail

**Comment by lundmb** [comment]
Was sick today, but yesterday I was waiting for your updated version to the
secion first, Lucianne, so I'll go through now (or more likely, on my train
tomorrow) and update with specifics for my metrics

**Comment by drphilmarshall** [comment]
Yes! Specific metrics for transients. What's the status of this issue, please?
