### ISSUE TITLE
Building a SN metric

### ISSUE THREAD

**Issue by rbiswas4** [LSSTScienceCollaborations/ObservingStrategy#72]
Attempt to build a SN metric that is quantitative: described more here
- https://github.com/rbiswas4/BuildingSNMetric

**Comment by drphilmarshall** [comment]
Nice! Looks like you'll want to document this as you go in the relevant WP section - you can hyperlink to your working repo with: 

    This metric is being developed at \href{https://github.com/rbiswas4/BuildingSNMetric}{this repository}

**Comment by rbiswas4** [comment]
https://github.com/rbiswas4/BuildingSNMetric/issues/1

**Comment by drphilmarshall** [comment]
Hi @rbiswas4 I guess you will be working on this next week, before during and after the face to face meeting, right? I'll re-milestone.

**Comment by drphilmarshall** [comment]
I am assuming this has been left behind long ago!
