### ISSUE TITLE
Plan for supernova cosmology section

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#73]
A place for ideas about the supernova cosmology section and how to get from OpSim to cosmology metric.

**Comment by drphilmarshall** [comment]
Here's an editable list of possible science project sections:

* [ ] Photometric Classification of SNe. FoM: area under ROC curve?
* [ ] Type IA SNe (and Host) Photometric Redshifts. FoM: mean photo-z accuracy?
* [ ] Measuring Type IA SN Light Curve Parameters. FoM: DETF?
* [ ] Dark Energy Parameters from Type IA SNe. FoM: DETF?

Let's edit/extend/re-arrange as the discussion proceeds! Then we can check them off as they are implemented as section files.

**Comment by drphilmarshall** [comment]
Also, see the discussion in #97 - should SN cosmology be a chapter, or should its science projects be subsections in a SN section of a cosmology chapter, or should all the science projects be wrapped into one science project, where classification, photo-zs, light curve analysis etc are simply quantified by *diagnostic* metrics rather than FoM's? If all we care about is the DE parameters, the latter choice seems appropriate...

**Comment by MichelleLochner** [comment]
1) Initially, we want to develop an intuition for how changes in observing strategy affect SN cosmology. See #72 for more details of the plan, but the main idea is to run Lynne's OpSimObs code to quickly generate sets of observations and then simulate a single light curve to see how errors in the distance modulus change in different cases of observing strategy. 
2) We then would like to understand how classification is affected using a similar strategy. Classification is more complex, because it takes longer and requires more complex simulations, but we could test a number of strategies with OpSimObs.
3) These investigations will allow us to make general statements about requirements for good light curve classification and characterisation. From there, we can develop a full end to end pipeline to go from OpSim run to SN cosmology metric. 
4) The exact form of this metric is yet to be decided, but may take the form of DETF FoM. We'd also be interested in trying out both the traditional method of SN cosmology and newer Bayesian approaches (e.g. BEAMS, UNITY etc.)

**Comment by drphilmarshall** [comment]
Aha! Here is the "define metrics" issue that you need, team supernovae. I will re-milestone this to the Tucson meeting. I strongly suggest that you write some subsections about the metrics you want to try and calculate (even if they are still conceptual at this stage) - the white paper must be produced! :-)

**Comment by drphilmarshall** [comment]
I assume you have moved on from this!
