### ISSUE TITLE
Adding the healpixIds from the Carroll et al., Awan et al. to OpSim output

### ISSUE THREAD

**Issue by rbiswas4** [LSSTScienceCollaborations/ObservingStrategy#74]
described here:
- https://github.com/rbiswas4/AddingHealpixIdsToOpsims

**Comment by drphilmarshall** [comment]
What do you think, @yoachim?

**Comment by rbiswas4** [comment]
https://github.com/rbiswas4/AddingHealpixIdsToOpsims/blob/master/README.md

**Comment by rhiannonlynne** [comment]
I have thoughts on this. First question is why exactly do you want to do it? What will you gain? 
We do essentially this in maf, but we iterate though each healpixel and report visits which overlap, rather than calculate (and save) the healpix values associated with each visit. If you precomputed the information, you will have to choose your healpix resolution at that time and stick with it. You would also have to recompute these healpix ids if you change the dithering pattern. And if you want to look up visits by healpixid, you well have to make an additional table based on healpix ids (which will be rather large, as Eric pointed out). Does having this table buy you more than calculating it on the fly using maf?

If you just want the visit history of the visits which overlap a particular point on the sky, have a look at just using the user defined points slicer with the pass metric.

**Comment by rbiswas4** [comment]
@rhiannonlynne 
> I have thoughts on this. First question is why exactly do you want to do it? What will you gain? 

SN simulation programs reorganize the observation sequence output from either a survey or survey plan such as opsim into the time series of observations in each spatial region. This is then used to perform simulations. Currently the units of spatial regions over which this reindexing is done are the LSST fields. Using higher resolution information would enable adding in dither/overlap information. That is what we want. 

The plan that we have is to have a code to calculate this extra information and add it to the OpSim output in a convenient way (for example after discussion with @egawiser we decided to have two tables so that we could use joins), so that we can run other programs to serialize this information in just the same way we serialize this for opsim outputs.

> We do essentially this in maf, but we iterate though each healpixel and report visits which overlap, rather than calculate (and save) the healpix values associated with each visit. If you precomputed the information, you will have to choose your healpix resolution at that time and stick with it. You would also have to recompute these healpix ids if you change the dithering pattern. And if you want to look up visits by healpixid, you well have to make an additional table based on healpix ids (which will be rather large, as Eric pointed out). Does having this table buy you more than calculating it on the fly using maf?

I have not done the full thing yet, so I may be overlooking something and be completely wrong, but my guess was that this way is a lot less work for me. The important thing is that this reorganized information is not an end product but an input to other codes. For this to play nice, it has to be serialized in a certain format.  I am not entirely sure about what you mean by 'on the fly', but If I have to serialize to a particular format  so that other codes can use it, then I don't really need more freedom than what has been proposed. The serialization should take some inputs and right now opsim outputs are the input to this, and therefore having things in similar formats is probably easiest. 

Storing overlapping visits only is smart, but to get other codes to use this data format is much more work, whereas increasing the number of spatial regions is less work because everything works out of the box. Now, it might so happen that we find that these dumb ways will start breaking down if
we start going to very high resolutions  (and larger number of fields), and that would definitely be a point to look at other ways of doing this.

That said, it is possible to use functions from the maf module to do the calculation of assigning healpixels within a field, and we definitely plan to give that a try. I am not sure if that will be convenient/efficient compared to the healpix function querydisc that Eric was using, but plan to play with both.

More generally speaking (though completely irrelevant to me and this conversation), I think this functionality of being able to look at spatial regions of higher resolution etc.  in MAF is more general and can be very useful for applications (such as the one we are discussing) than the metric analysis framework. Therefore this should probably be outside maf in a more general package (MAP?) that should be imported by MAF and other users.  The point is that if I were an outsider trying to do simulation, I probably would need these kinds of functionality but would be unlikely to search for this in a metric analysis framework. 
 
> If you just want the visit history of the visits which overlap a particular point on the sky, have a look at just using the user defined points slicer with the pass metric.

Indeed, thanks to previous conversations with you and Peter, a point by point method like this is the default on how the supernovae simulations within catsim will address this issue, (subject to tests on speed once other things work faster which may require a hybrid method). But this does not work with other setups, so we still need alternatives.

**Comment by drphilmarshall** [comment]
Will you be continuing this discussion in Tucson, or can you report and close this out?

**Comment by drphilmarshall** [comment]
Closing this while everyone gets on with things - feel free to reopen if this is still actually an issue!
