### ISSUE TITLE
TOO mode for OpSim

### ISSUE THREAD

**Issue by soares-santos** [LSSTScienceCollaborations/ObservingStrategy#75]
We suggest implementing a TOO mode into next OpSim runs. The example science case is Gravitational Wave observations triggered by LIGO.

**Comment by drphilmarshall** [comment]
Thanks @soares-santos ! How do you like the proposal that @ebellm submitted in #77? Feel free to close this our when you are happy with the markdown files.

**Comment by drphilmarshall** [comment]
Hooray!
