### ISSUE TITLE
Hierarchical metrics

### ISSUE THREAD

**Issue by MichelleLochner** [LSSTScienceCollaborations/ObservingStrategy#79]
Many science metrics are highly dependent on other metrics. For example, reliable photometric redshifts are absolutely essential for a variety of science cases. Should we be building hierarchical metrics? For instance, you could build an overall dark energy metric, which depends on a variety of probes (supernovae, weak lensing etc.) which in turn depend on 'non-science' metrics like photometric redshifts.

**Comment by drphilmarshall** [comment]
@rhiannonlynne has thought a lot about this - she can explain the capabilities of "complex metrics" better than I can, but if you check out the lens time delays section you can maybe see what we managed to do. `cadence`, `season` and `campaign` are all metrics, as are `A`, `P` and `f` that depend on them via our equations.
