### ISSUE TITLE
Who do we want to attend the workshop?

### ISSUE THREAD

**Issue by bethwillman** [LSSTScienceCollaborations/ObservingStrategy#8]
List names, types of people, types of institutions, anything :)

**Comment by drphilmarshall** [comment]
@michaelstrauss pointed out in our April telecon that we (the SOC) have a part to play in getting people to attend this workshop. I have been focusing on the time-domain part of the Dark Energy science collaboration, trying to find active people who will be keen to contribute either white paper text or MAF metrics. A concerted push just after the Second Announcement goes out makes some sense, so we should think about putting this question onto the June WP section leads meeting agenda.
