### ISSUE TITLE
"The Galaxy" chapter - sharpen focus on non-SRD cases; example strawman metrics

### ISSUE THREAD

**Issue by willclarkson** [LSSTScienceCollaborations/ObservingStrategy#80]
Following discussion at LSST Strategy Workshop 2015-08-21, starting to make the following updates to galaxy.tex :

(i) started tightening the focus of The Galaxy chapter on science cases with requirements different to SRD numbers;
(ii) started incorporating some strawman metrics to provoke experts within the SMWLV collaboration
(iii) a few typo fixes

cc @akvivas @bethwillman

**Comment by drphilmarshall** [comment]
Nice - I suggest you close this from the last commit you make before merging the pull request in #99 (i.e. with `git commit -am "Closes #99"` )

**Comment by willclarkson** [comment]
UPDATE 2015-08-22 10:00am - following discussion, still some further trimming: see Issue 116
