### ISSUE TITLE
Pulsating white dwarfs and other short-period variables should be tabulated in section 6.3.1

### ISSUE THREAD

**Issue by keatonb** [LSSTScienceCollaborations/ObservingStrategy#82]
@lmwalkowicz 

Even though the LSST revisit rate in the main survey is too low to resolve a power spectrum of variability in (multi-)periodic variables with period(s) ~10 minutes, the photometric precision will allow detection of variability and some characterization (esp. in terms of color amplitudes and moments of measured brightness distributions).  I intend to write MAF metrics to evaluate the sensitivity of OpSIM runs to low amplitude, high-frequency variability.  Please include these objects (pulsating white dwarfs and other short-period variables) in the Table of Section 6.3.1 and I will supply more text and analysis later.

**Comment by StephenRidgway** [comment]
Added white dwarfs to table, and several other changes suggested by Paula.

**Comment by drphilmarshall** [comment]
Thanks @keatonb! Can I suggest that when you start working on the text, you open a pull request as soon as you have pushed your first commit? That way, all your work will be logged, and everyone else can follow along and comment. Will's following this model in #99 right now, for example. Good luck! :-)

**Comment by drphilmarshall** [comment]
Also, @lmwalkowicz  please do close this out if you're happy with how things look for now!

**Comment by drphilmarshall** [comment]
I guess Lucianne *was* happy!
