### ISSUE TITLE
Variability in pre-main-sequence stars

### ISSUE THREAD

**Issue by pmmcgehee** [LSSTScienceCollaborations/ObservingStrategy#84]
Attn: @StephenRidgway, @willclarkson, @akvivas

YSO variability is mentioned, but not quantified, in sections 4.3.4 [The Milky Way Disk] and 6.4 [Non-periodic variables] of the white paper. In order to assess the ability of LSST to 1) identify and 2) classify YSO we need to quantify the variability timescales and amplitudes of both Class I/II (stars with disks) and Class III (WTTS). Inclusion of eruptive variables (FUor/Exor) is appropriate as well - see section 8.10.2 in the Science Book. 

In brief, WTTS are quasi-periodic with amplitudes of 0.1 to 0.3 mag and periods 1 to ~15 days - so comparable to gamma Dor stars (see Figure 8.17 in the SB). Given the temporal evolution of cool spots, a period recovery analysis such as shown for RRL stars (se FIgure 8.20 in the SB) is likely difficult. The embedded systems and CTTS are irregular  variables but shown have distinctive colors due to extinction + UB/blue excess due to accretion shocks.

I will expand the treatment in section 4.3.4 of the whitepaper, adding a reference in section 6.4.

- Peregrine

**Comment by drphilmarshall** [comment]
Looks like @pmmcgehee is working on this in #93 !

**Comment by StephenRidgway** [comment]
I was asked to add amplitude and time scale info to the relevant table in chapter 6.  For YSOs I entered "small" and "weeks", in the rationale that the difficult phenomena would be small amplitude, and the "weeks" time scale would important and would be the most accessible to LSST cadence.  But it shorter time scales are high priority, maybe change this to days? or even hours?  (But rotational and flare activity is noted separately.)

**Comment by pmmcgehee** [comment]
This material has been added to the star formation history section of the refactored Galaxy chapter. I am taking the lead on this. This issue is now closed.

**Comment by pmmcgehee** [comment]
The timescales for YSO variability are dependent on the evolutionary state of the star and range from less than a day to ~2 weeks. Amplitudes are band dependent and range from ~0.1 mag to ~1 mag. The science goals based on LSST photometry are detection and characterization of the variability (quasi-periodic or irregular). There also are color differences between the classes of YSOs which will aid the classification.

YSOs with disks: amplitude is 0.1 to ~1 mag, timescales: < 1 day to weeks.
    (rotation of cold and hot spots, changes in accretion flow, variable extinction)
YSOs w/o disks: amplitude is 0.1 to 0.3 mag, timescales: 1 day to 2 weeks (rotation only)

**Comment by StephenRidgway** [comment]
Given that the chapter 6 reference is brief, it looks like change the characteristic time to ~1 day? I think 0.1 mag is fairly described as small amplitude.

**Comment by pmmcgehee** [comment]
![lc_days](https://cloud.githubusercontent.com/assets/13893593/9425082/3ddb4dd4-48b8-11e5-8a2e-acd2b746818a.png)

Yes - here are example YSO light curves from COROT in NGC 2264 [Alencar+2010]

**Comment by drphilmarshall** [comment]
Looks like this was resolved - closing unless @StephenRidgway or @pmmcgehee think it needs more work. Thanks!
