### ISSUE TITLE
"Photometric variability of cool dwarfs" should be moved to Chapter 6 (?)

### ISSUE THREAD

**Issue by keatonb** [LSSTScienceCollaborations/ObservingStrategy#85]
@willclarkson I notice that starspot modulation is the only topic of its type included in Chapter 4.  Perhaps this work would fit better with the other topic of intrinsic photometric stellar variability in Chapter 6?

**Comment by willclarkson** [comment]
Keaton - thanks for this! I think I agree that metrics in terms of
detectability of variability may be better located in the variability
chapter.

I really like the suggestion @MichelleLochner made (issue #79) about
hierarchical metrics. For example, I can imagine us in The Galaxy having a
metric like "width of instability strip" that in turn relies on a metric
from Variability like "fractional completeness of variation detection."

No idea how this might be accomplished... perhaps there is a clever
MAF-related way to make metrics depend on each other?

Cheers

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR421, PHYS150 or PHYS126).

**Comment by drphilmarshall** [comment]
@StephenRidgway can you please work with @willclarkson to make the suggested refactoring please? Thanks!

**Comment by drphilmarshall** [comment]
@StephenRidgway @willclarkson What's the status of this, please? Thanks!

**Comment by willclarkson** [comment]
@drphilmarshall and @StephenRidgway -- I believe @keatonb has submitted material on cool-star variability to Chapter 6, so I think this issue can be closed.

@keatonb , is this accurate?

Thanks!

Will

**Comment by keatonb** [comment]
No, I submitted content about cool pulsating white dwarfs, not starspot modulation and such sources of variability in cool (main sequence) dwarfs.  I think that this is what the *empty* subsection of Chapter 5 "Age-Mapping the Galaxy Using Gyrochronology" was meant to address, but no one wrote any content.  Sorry it's not my area of expertise.

**Comment by willclarkson** [comment]
My mistake, I must have read the discussion in a hurry... 
It sounds like the material on starspot modulation is still under development then for Chapter 5.

**Comment by drphilmarshall** [comment]
I'm going to assume this somehow got fixed. Closing out!
