### ISSUE TITLE
RR Lyrae stars in the plane

### ISSUE THREAD

**Issue by akvivas** [LSSTScienceCollaborations/ObservingStrategy#88]
I am starting a section on the detection of RR Lyrae stars in the galactic plane to be included in The Galaxy chapter. This will eventually make use of the crowding limit calculations at any point in the sky (issue #76) and metrics developed by the Variable Stars and Transients group (issue #71) @rblum5 @willclarkson @lmwalkowicz @StephenRidgway

**Comment by bethwillman** [comment]
Will evaluating the detectability of periodic variables in crowded regions
necessarily need to make use of the crowding calculations?  I was thinking
that a combination of a map of interstellar extinction, a set of RRL
templates (plus ranges of periods and amplitudes), and the 5 sigma
difference image limit in delta magnitude is what could be used for
calculating this metric.

On Fri, Aug 21, 2015 at 3:44 PM, Kathy <notifications@github.com> wrote:

> I am starting a section on the detection of RR Lyrae stars in the galactic
> plane to be included in The Galaxy chapter. This will eventually make use
> of the crowding limit calculations at any point in the sky (issue #76
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/76>)
> and metrics developed by the Variable Stars and Transients group (issue
> #71
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/71>)
> @rblum5 <https://github.com/rblum5> @willclarkson
> <https://github.com/willclarkson> @lmwalkowicz
> <https://github.com/lmwalkowicz> @StephenRidgway
> <https://github.com/StephenRidgway>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/issues/88>
> .
>



-- 
Beth Willman
AURA/LSST Deputy Director
Associate Astronomer, Steward Observatory
933 North Cherry Avenue
Tucson, Arizona 85721
520-318-8473

**Comment by akvivas** [comment]
The crowding limit will help to evaluate what are the faintest RR Lyrae stars we can detect (in combination of course of a map of interstellar extinction). This would answer how far can we detect RR Lyrae stars and how well can we sample the disk (can we detect distant stars on the other side of the disk?) @bethwillman

**Comment by akvivas** [comment]
ok... got your point now,  Beth. Differential imaging will be the way to go in crowded regions. Excellent!

**Comment by willclarkson** [comment]
@akvivas - I think this is an important point, that the crowding limit is
different for different kinds of investigation. Hopefully the metrics will
be sophisticated enough to deal with this.

e.g. pseudocode might be something like:
if (ThisMetric is Variability):
      deepLimit = CrowdingLimit(UsingDIfferenceImaging = True)
else:
      deepLimit = CrowdingLimit(UsingDifferenceImaging = False)




--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR421, PHYS150 or PHYS126).

**Comment by knutago** [comment]
So one way in which the confusion limit enters is for measuring the zero point of the brightness of the variable stars.  Difference imaging is great for measuring Poisson-limited changes in source brightness, but for measuring distances with RR Lyrae, you also need the mean apparent luminosity.  And a crowded field will have extra Poisson noise from neighboring sources...

**Comment by drphilmarshall** [comment]
A quick search of the PDF shows that RR Lyrae are currently only mentioned in the Special Surveys chapter. Are you  planning on checking in some Galaxy text, @akvivas?

**Comment by akvivas** [comment]
Closing this one since it is not within the current structure. May be re-opened later if needed.
