### ISSUE TITLE
Website background images

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/ObservingStrategy#9]
CSS might need adjusting too to get the full width effect. One image per section? And what is this Bremerton venue anyway?

**Comment by connolly** [comment]
If you need help with the css etc. I'd be happy to help - just hacked it up for another set of lectures I will be giving http://connolly.github.io/introAstroML/

cheers
Andy

**Comment by drphilmarshall** [comment]
Thanks Andy! I pinched the styles etc from teh astrohackweek crowd, and chose a nice LSST iomage for the background. I think it looks good enough!
