### ISSUE TITLE
Transients and variables: getting MAF metrics coded

### ISSUE THREAD

**Issue by AshishMahabal** [LSSTScienceCollaborations/ObservingStrategy#90]
There already exist some nice MAF metrics for use with transients and variables. What's the best way to proceed with a broad investigation of all the types of objects that are defined in Chapter 6?

Here's two possibilities:

* 1) We collect sample lightcurves and check them in for analysis by the sims team?
* 2) We could recruit more transients and variables scientists, and have them trained by the sims team to tweak and run the MAF metrics themselves?

I guess we need to decide how many different object types we want to explore, and which ones - and think about how to make this all as efficient as possible... Thoughts, @connolly @yoachim @StephenRidgway @lmwalkowicz @rhiannonlynne ? 

Thanks! 

Ashish and Phil

**Comment by lundmb** [comment]
For a point of clarity, when you say "we collect sample lightcurves", what
are you considering for these sample lightcurves? In particular, are we
presuming that any MAF metrics for transients and variables will require
light curve generation? I may just be misunderstanding the intent here.

- Mike Lund

**Comment by StephenRidgway** [comment]
Several years ago the ImSim group asked for variable star flux data for various types of stars, in order to simulate them.  Does anybody know if this advanced to include a good selection of object types?

Several groups have experimented with period finding for RR Lyr sampled according to opsim runs.  Probably we would need to provide our own custom analysis for detection of any particular parameter, and do the runs.

**Comment by lmwalkowicz** [comment]
@AshishMahabal I think it is the responsibility of the users to know, for their particular science case, what the value of a given metric means in terms of the success of their science. The sims team can evaluate metrics for a given run, but the metrics themselves are independent of any particular lightcurve. 

@StephenRidgway multicolor lightcurves were provided to ImSim, and I believe one or two of those were implemented. @simonkrughoff do you know what happened to these?

**Comment by drphilmarshall** [comment]
This is very relevant to #71 - let's complete this discussion here, close up and de-camp back to that thread ASAP.
