### ISSUE TITLE
expand tables ch. 6.

### ISSUE THREAD

**Issue by darkojev** [LSSTScienceCollaborations/ObservingStrategy#94]
Sorry if this was mentioned before - started to follow recently - I think that tables in chapter 6 (sections 6.2.2 6.3.1 and 6.5.1) should be expanded with characteristic time scale (and amplitudes). Also I would suggest one compile to be able to see what has changed so far.

**Comment by StephenRidgway** [comment]
Excellent suggestion.  (The tables were a really quick and dirty place holder).  Additional info would make them much more useful, especially important for topics that do not get expanded into dedicated sections.

**Comment by lundmb** [comment]
If people can characterize what constitutes small vs large amplitudes, I think that would be greatly beneficial. I think people from different science cases would interpret those as having very different meanings

**Comment by StephenRidgway** [comment]
Yes, definitely needed - to use metrics also.  Not sure how much information should go in the tables (assuming that they survive continued editing). I was about to try and put some values in, and realized that the range would be large in many cases, so I then thought, would the typical science application concern amplitudes that would be difficult or easy - which of course depends on how bright the typical objects are.  So I said that CV amplitudes were small (even though they often aren’t) thinking that the driving case would be flickering in faint objects.  Please anybody suggest/experiment with formats/contents - I expect that any topic that deserves much explanation should have its own section or subsection.  I hope to try to sketch out one or two of the topics and see what information seems better saved for narrative development.

**Comment by AshishMahabal** [comment]
This is indeed an important point, and should perhaps also be coupled with time-scales. This also 9perhaps obliquely) relates to what we call quiescent - Mike's triplet is an example metric that can explore it. @lundmb @StephenRidgway

**Comment by StephenRidgway** [comment]
Since the original request is complete (and Phil is leaning over my shoulder), I will close this issue, but feel free to reopen for new ideas, or just edit in a new format.
