### ISSUE TITLE
Should we have science cases as sub-sections instead of sections? 

### ISSUE THREAD

**Issue by akvivas** [LSSTScienceCollaborations/ObservingStrategy#97]
Right now each science case is a section in a chapter. In the case of The Galaxy, we would like to have a little more structure to group science projects in main areas (for example, The Bulge, The Halo, etc, etc.). This would make easier to locate a particular project in the white paper. Maybe the same is true for other chapters. Any thoughts? @drphilmarshall @willclarkson

**Comment by StephenRidgway** [comment]
It seems to me that as a topic grows, it can/should be considered for a chapter of its own.  Thanks to the modular structure of the files, it will be easy to move a section to chapter or the reverse.

**Comment by drphilmarshall** [comment]
Anyone else feeling the need for an additional level of hierarchy?

**Comment by drphilmarshall** [comment]
The cosmology chapter looks as though it might be in the same situation as Galaxy, in that SN cosmology have more than one science case to be MAF-quantified. For now, I suggest you stick with the "one section per science case" structure, but name your sections hierarchically. e.g "SN Ia: Classification" , "SN Ia: Light Curve Fitting" and so on. Hope this sounds OK!
